/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AxiosInstance } from 'axios';
import { NewSuggestedVendor, SuggestedVendor, Vendor } from '../model/index.js';
import { URL, EnumValue, IllegalArgumentError, PagedResults, Int32, CoreError, ParameterRequiredError, UnexpectedError, HttpMethod } from '@zerobias-org/types-core-js';
import { RequestFile, ObjectSerializer } from '../model/index.js';

export namespace VendorApi {
}

/**
 * VendorApi - interface
 * @export
 * @interface VendorApi
 */
export interface VendorApi {
  /**
   * Create a new suggested vendor
   * @summary Create a new suggested vendor
   * @param {NewSuggestedVendor} newSuggestedVendor 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.createSuggestedVendor(null);
   * ```
   * @openapi operation=createSuggestedVendor path=/catalog/suggestedVendors method=POST
   * @memberof VendorApi
   */
  createSuggestedVendor(newSuggestedVendor: NewSuggestedVendor): Promise<SuggestedVendor>;

  /**
   * Retrieves a list of suggested vendors
   * @summary Retrieves a list of suggested vendors
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {string} [keywords] Search like filter
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.listSuggestedVendors(1, 1, 'keywords');
   * ```
   * @openapi operation=listSuggestedVendors path=/catalog/suggestedVendors method=GET
   * @memberof VendorApi
   */
  listSuggestedVendors(pageNumber?: number, pageSize?: number, keywords?: string): Promise<PagedResults<SuggestedVendor>>;

  /**
   * List vendors
   * @summary List vendors
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {string} [search] A string to search for
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.listVendors(1, 1, 'search');
   * ```
   * @openapi operation=listVendors path=/catalog/vendors method=GET
   * @memberof VendorApi
   */
  listVendors(pageNumber?: number, pageSize?: number, search?: string): Promise<PagedResults<Vendor>>;

}

/**
 * VendorProducerApi - interface
 * Producer interface for Vendor
 * @export
 * @interface VendorProducerApi
 */
export interface VendorProducerApi {
  /**
  * Create a new suggested vendor
  * @summary Create a new suggested vendor
  * @param {NewSuggestedVendor} newSuggestedVendor 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=createSuggestedVendor path=/catalog/suggestedVendors method=POST
  * @memberof Vendor
  */
  createSuggestedVendor(newSuggestedVendor: NewSuggestedVendor): Promise<SuggestedVendor>;
  /**
  * Retrieves a list of suggested vendors
  * @summary Retrieves a list of suggested vendors
  * @param {string} [keywords] Search like filter
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=listSuggestedVendors path=/catalog/suggestedVendors method=GET
  * @memberof Vendor
  */
  listSuggestedVendors(results: PagedResults<SuggestedVendor>, keywords?: string): Promise<void>;
  /**
  * List vendors
  * @summary List vendors
  * @param {string} [search] A string to search for
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=listVendors path=/catalog/vendors method=GET
  * @memberof Vendor
  */
  listVendors(results: PagedResults<Vendor>, search?: string): Promise<void>;
}

export class VendorApiMappingImpl implements VendorApi {
  private producer: VendorProducerApi;
  constructor(producer: VendorProducerApi) {
    this.producer = producer;
  }

  /**
   * Create a new suggested vendor
   * @summary Create a new suggested vendor
   * @param newSuggestedVendor 
   * @openapi operation=createSuggestedVendor path=/catalog/suggestedVendors method=POST
   */
  public async createSuggestedVendor(newSuggestedVendor: NewSuggestedVendor): Promise<SuggestedVendor> {
    // verify required parameter 'newSuggestedVendor' is not null or undefined
    if (newSuggestedVendor === null || newSuggestedVendor === undefined) {
      throw new ParameterRequiredError('newSuggestedVendor');
    }
    return this.producer.createSuggestedVendor(newSuggestedVendor);
  }
  /**
   * Retrieves a list of suggested vendors
   * @summary Retrieves a list of suggested vendors
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param keywords Search like filter
   * @openapi operation=listSuggestedVendors path=/catalog/suggestedVendors method=GET
   */
  public async listSuggestedVendors(pageNumber: number = 1, pageSize: number = 50, keywords?: string): Promise<PagedResults<SuggestedVendor>> {
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<SuggestedVendor>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    await this.producer.listSuggestedVendors(bag, keywords);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
  /**
   * List vendors
   * @summary List vendors
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param search A string to search for
   * @openapi operation=listVendors path=/catalog/vendors method=GET
   */
  public async listVendors(pageNumber: number = 1, pageSize: number = 50, search?: string): Promise<PagedResults<Vendor>> {
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<Vendor>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    await this.producer.listVendors(bag, search);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
}

/**
 * Wrap producer with mapping implementation
 */
export function wrapVendorProducer(producer: VendorProducerApi): VendorApi {
  return new VendorApiMappingImpl(producer);
}

/**
 * VendorApiHttpImpl - Direct HTTP implementation
 *
 * Makes direct HTTP calls to the API using Axios.
 * Used by SDK clients for platform service access.
 */
export class VendorApiHttpImpl implements VendorProducerApi {
  private client: AxiosInstance;
  private headers: Record<string, string>;

  constructor(client: AxiosInstance, headers: Record<string, string> = {}) {
    this.client = client;
    this.headers = headers;
  }

  async createSuggestedVendor(newSuggestedVendor: NewSuggestedVendor): Promise<SuggestedVendor> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      ...newSuggestedVendor,
  };
  let _path = '/catalog/suggestedVendors';
  return this.client.post(
    _path,
    _bodyParams)
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'SuggestedVendor')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async listSuggestedVendors(results: PagedResults<SuggestedVendor>, keywords?: string): Promise<void> {
  const _body = {
      keywords,
  };
  let _path = '/catalog/suggestedVendors';
  return this.client.get(
    _path,
    {
      params: {
        ..._body,
        pageNumber: results.pageNumber,
        pageSize: results.pageSize,
      }
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<SuggestedVendor>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}/catalog/suggestedVendors`);
      results.httpMethod = HttpMethod.Get;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'SuggestedVendor');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async listVendors(results: PagedResults<Vendor>, search?: string): Promise<void> {
  const _body = {
      search,
  };
  let _path = '/catalog/vendors';
  return this.client.get(
    _path,
    {
      params: {
        ..._body,
        pageNumber: results.pageNumber,
        pageSize: results.pageSize,
      }
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<Vendor>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}/catalog/vendors`);
      results.httpMethod = HttpMethod.Get;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'Vendor');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
}
