/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AxiosInstance } from 'axios';
import { AlertBotExtended, BoundaryAlertBotUsageItem, ResultsColumnOptionsWrapper, SearchAlertBotUsageBody, SearchAlertBotsBody, SortObject } from '../model/index.js';
import { URL, EnumValue, IllegalArgumentError, PagedResults, Int32, UUID, CoreError, ParameterRequiredError, UnexpectedError, HttpMethod } from '@zerobias-org/types-core-js';
import { RequestFile, ObjectSerializer } from '../model/index.js';

export namespace AlertBotApi {
}

/**
 * AlertBotApi - interface
 * @export
 * @interface AlertBotApi
 */
export interface AlertBotApi {
  /**
   * Get alert bot
   * @summary Get alert bot
   * @param {UUID} alertBotId 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.get('00000000-0000-0000-0000-000000000000');
   * ```
   * @openapi operation=getAlertBot path=/alertBots/{alertBotId} method=GET
   * @memberof AlertBotApi
   */
  get(alertBotId: UUID): Promise<AlertBotExtended>;

  /**
   * list all alertBots
   * @summary list all alertBots
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {SortObject} [sort] Sort object
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.list(1, 1, null);
   * ```
   * @openapi operation=listAlertBots path=/alertBots method=GET
   * @memberof AlertBotApi
   */
  list(pageNumber?: number, pageSize?: number, sort?: SortObject): Promise<PagedResults<AlertBotExtended>>;

  /**
   * Returns options/filters for alert bots
   * @summary Returns options/filters for alert bots
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @openapi operation=searchAlertBotOptions path=/alertBotSearch/options method=GET
   * @memberof AlertBotApi
   */
  options(): Promise<ResultsColumnOptionsWrapper>;

  /**
   * Search alertBot usage
   * @summary Search alertBot usage
   * @param {SearchAlertBotUsageBody} searchAlertBotUsageBody 
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {SortObject} [sort] 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.usageSearch(null, 1, 1, null);
   * ```
   * @openapi operation=searchAlertBotUsage path=/alertBotUsageSearch method=POST
   * @memberof AlertBotApi
   */
  usageSearch(searchAlertBotUsageBody: SearchAlertBotUsageBody, pageNumber?: number, pageSize?: number, sort?: SortObject): Promise<PagedResults<BoundaryAlertBotUsageItem>>;

  /**
   * Returns options/filters for alert bots
   * @summary Returns options/filters for alert bots
   * @param {UUID} alertBotId 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.usageOptions('00000000-0000-0000-0000-000000000000');
   * ```
   * @openapi operation=searchAlertBotUsageOptions path=/alertBots/{alertBotId}/usage/options method=GET
   * @memberof AlertBotApi
   */
  usageOptions(alertBotId: UUID): Promise<ResultsColumnOptionsWrapper>;

  /**
   * Search alertBots
   * @summary Search alertBots
   * @param {SearchAlertBotsBody} searchAlertBotsBody 
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {SortObject} [sort] 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.search(null, 1, 1, null);
   * ```
   * @openapi operation=searchAlertBots path=/alertBotSearch method=POST
   * @memberof AlertBotApi
   */
  search(searchAlertBotsBody: SearchAlertBotsBody, pageNumber?: number, pageSize?: number, sort?: SortObject): Promise<PagedResults<AlertBotExtended>>;

}

/**
 * AlertBotProducerApi - interface
 * Producer interface for AlertBot
 * @export
 * @interface AlertBotProducerApi
 */
export interface AlertBotProducerApi {
  /**
  * Get alert bot
  * @summary Get alert bot
  * @param {UUID} alertBotId 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=getAlertBot path=/alertBots/{alertBotId} method=GET
  * @memberof AlertBot
  */
  get(alertBotId: UUID): Promise<AlertBotExtended>;
  /**
  * list all alertBots
  * @summary list all alertBots
  * @param {SortObject} [sort] Sort object
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=listAlertBots path=/alertBots method=GET
  * @memberof AlertBot
  */
  list(results: PagedResults<AlertBotExtended>, sort?: SortObject): Promise<void>;
  /**
  * Returns options/filters for alert bots
  * @summary Returns options/filters for alert bots
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchAlertBotOptions path=/alertBotSearch/options method=GET
  * @memberof AlertBot
  */
  options(): Promise<ResultsColumnOptionsWrapper>;
  /**
  * Search alertBot usage
  * @summary Search alertBot usage
  * @param {SearchAlertBotUsageBody} searchAlertBotUsageBody 
  * @param {SortObject} [sort] 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchAlertBotUsage path=/alertBotUsageSearch method=POST
  * @memberof AlertBot
  */
  usageSearch(results: PagedResults<BoundaryAlertBotUsageItem>, searchAlertBotUsageBody: SearchAlertBotUsageBody, sort?: SortObject): Promise<void>;
  /**
  * Returns options/filters for alert bots
  * @summary Returns options/filters for alert bots
  * @param {UUID} alertBotId 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchAlertBotUsageOptions path=/alertBots/{alertBotId}/usage/options method=GET
  * @memberof AlertBot
  */
  usageOptions(alertBotId: UUID): Promise<ResultsColumnOptionsWrapper>;
  /**
  * Search alertBots
  * @summary Search alertBots
  * @param {SearchAlertBotsBody} searchAlertBotsBody 
  * @param {SortObject} [sort] 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchAlertBots path=/alertBotSearch method=POST
  * @memberof AlertBot
  */
  search(results: PagedResults<AlertBotExtended>, searchAlertBotsBody: SearchAlertBotsBody, sort?: SortObject): Promise<void>;
}

export class AlertBotApiMappingImpl implements AlertBotApi {
  private producer: AlertBotProducerApi;
  constructor(producer: AlertBotProducerApi) {
    this.producer = producer;
  }

  /**
   * Get alert bot
   * @summary Get alert bot
   * @param alertBotId 
   * @openapi operation=getAlertBot path=/alertBots/{alertBotId} method=GET
   */
  public async get(alertBotId: UUID): Promise<AlertBotExtended> {
    // verify required parameter 'alertBotId' is not null or undefined
    if (alertBotId === null || alertBotId === undefined) {
      throw new ParameterRequiredError('alertBotId');
    }
    return this.producer.get(alertBotId);
  }
  /**
   * list all alertBots
   * @summary list all alertBots
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param sort Sort object
   * @openapi operation=listAlertBots path=/alertBots method=GET
   */
  public async list(pageNumber: number = 1, pageSize: number = 50, sort?: SortObject): Promise<PagedResults<AlertBotExtended>> {
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<AlertBotExtended>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    await this.producer.list(bag, sort);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
  /**
   * Returns options/filters for alert bots
   * @summary Returns options/filters for alert bots
   * @openapi operation=searchAlertBotOptions path=/alertBotSearch/options method=GET
   */
  public async options(): Promise<ResultsColumnOptionsWrapper> {
    return this.producer.options();
  }
  /**
   * Search alertBot usage
   * @summary Search alertBot usage
   * @param searchAlertBotUsageBody 
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param sort 
   * @openapi operation=searchAlertBotUsage path=/alertBotUsageSearch method=POST
   */
  public async usageSearch(searchAlertBotUsageBody: SearchAlertBotUsageBody, pageNumber: number = 1, pageSize: number = 50, sort?: SortObject): Promise<PagedResults<BoundaryAlertBotUsageItem>> {
    // verify required parameter 'searchAlertBotUsageBody' is not null or undefined
    if (searchAlertBotUsageBody === null || searchAlertBotUsageBody === undefined) {
      throw new ParameterRequiredError('searchAlertBotUsageBody');
    }
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<BoundaryAlertBotUsageItem>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    await this.producer.usageSearch(bag, searchAlertBotUsageBody, sort);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
  /**
   * Returns options/filters for alert bots
   * @summary Returns options/filters for alert bots
   * @param alertBotId 
   * @openapi operation=searchAlertBotUsageOptions path=/alertBots/{alertBotId}/usage/options method=GET
   */
  public async usageOptions(alertBotId: UUID): Promise<ResultsColumnOptionsWrapper> {
    // verify required parameter 'alertBotId' is not null or undefined
    if (alertBotId === null || alertBotId === undefined) {
      throw new ParameterRequiredError('alertBotId');
    }
    return this.producer.usageOptions(alertBotId);
  }
  /**
   * Search alertBots
   * @summary Search alertBots
   * @param searchAlertBotsBody 
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param sort 
   * @openapi operation=searchAlertBots path=/alertBotSearch method=POST
   */
  public async search(searchAlertBotsBody: SearchAlertBotsBody, pageNumber: number = 1, pageSize: number = 50, sort?: SortObject): Promise<PagedResults<AlertBotExtended>> {
    // verify required parameter 'searchAlertBotsBody' is not null or undefined
    if (searchAlertBotsBody === null || searchAlertBotsBody === undefined) {
      throw new ParameterRequiredError('searchAlertBotsBody');
    }
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<AlertBotExtended>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    await this.producer.search(bag, searchAlertBotsBody, sort);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
}

/**
 * Wrap producer with mapping implementation
 */
export function wrapAlertBotProducer(producer: AlertBotProducerApi): AlertBotApi {
  return new AlertBotApiMappingImpl(producer);
}

/**
 * AlertBotApiHttpImpl - Direct HTTP implementation
 *
 * Makes direct HTTP calls to the API using Axios.
 * Used by SDK clients for platform service access.
 */
export class AlertBotApiHttpImpl implements AlertBotProducerApi {
  private client: AxiosInstance;
  private headers: Record<string, string>;

  constructor(client: AxiosInstance, headers: Record<string, string> = {}) {
    this.client = client;
    this.headers = headers;
  }

  async get(alertBotId: UUID): Promise<AlertBotExtended> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/alertBots/{alertBotId}';
  _path = _path.replace('{alertBotId}', encodeURIComponent(String(alertBotId)));
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'AlertBotExtended')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async list(results: PagedResults<AlertBotExtended>, sort?: SortObject): Promise<void> {
  const _body = {
      sort,
  };
  let _path = '/alertBots';
  return this.client.get(
    _path,
    {
      params: {
        ..._body,
        pageNumber: results.pageNumber,
        pageSize: results.pageSize,
      }
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<AlertBotExtended>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}/alertBots`);
      results.httpMethod = HttpMethod.Get;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'AlertBotExtended');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async options(): Promise<ResultsColumnOptionsWrapper> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/alertBotSearch/options';
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'ResultsColumnOptionsWrapper')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async usageSearch(results: PagedResults<BoundaryAlertBotUsageItem>, searchAlertBotUsageBody: SearchAlertBotUsageBody, sort?: SortObject): Promise<void> {
  const _body = {
      searchAlertBotUsageBody,sort,
  };
  let _path = '/alertBotUsageSearch';
  return this.client.post(
    _path,
    {
      ..._body,
      pageNumber: results.pageNumber,
      pageSize: results.pageSize,
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<BoundaryAlertBotUsageItem>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}/alertBotUsageSearch`);
      results.httpMethod = HttpMethod.Post;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'BoundaryAlertBotUsageItem');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async usageOptions(alertBotId: UUID): Promise<ResultsColumnOptionsWrapper> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/alertBots/{alertBotId}/usage/options';
  _path = _path.replace('{alertBotId}', encodeURIComponent(String(alertBotId)));
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'ResultsColumnOptionsWrapper')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async search(results: PagedResults<AlertBotExtended>, searchAlertBotsBody: SearchAlertBotsBody, sort?: SortObject): Promise<void> {
  const _body = {
      searchAlertBotsBody,sort,
  };
  let _path = '/alertBotSearch';
  return this.client.post(
    _path,
    {
      ..._body,
      pageNumber: results.pageNumber,
      pageSize: results.pageSize,
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<AlertBotExtended>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}/alertBotSearch`);
      results.httpMethod = HttpMethod.Post;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'AlertBotExtended');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
}
