/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AxiosInstance } from 'axios';
import { ComplianceFeatureExtended, ComplianceFeatureTypeEnum, ComplianceFeatureVersionExtended, ResultsColumnOptionsWrapper, ResultsSearchOptionsWrapper, SearchComplianceFeatureBody, SortObject, VersionSlim } from '../model/index.js';
import { URL, EnumValue, IllegalArgumentError, PagedResults, Int32, UUID, CoreError, ParameterRequiredError, UnexpectedError, HttpMethod } from '@zerobias-org/types-core-js';
import { RequestFile, ObjectSerializer } from '../model/index.js';

export namespace ComplianceFeatureApi {
}

/**
 * ComplianceFeatureApi - interface
 * @export
 * @interface ComplianceFeatureApi
 */
export interface ComplianceFeatureApi {
  /**
   * Get compliance feature by id
   * @summary Get compliance feature by id
   * @param {UUID} complianceFeatureId 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.get('00000000-0000-0000-0000-000000000000');
   * ```
   * @openapi operation=getComplianceFeature path=/complianceFeatures/{complianceFeatureId} method=GET
   * @memberof ComplianceFeatureApi
   */
  get(complianceFeatureId: UUID): Promise<ComplianceFeatureExtended>;

  /**
   * Get a compliance feature version
   * @summary Get a compliance feature version
   * @param {UUID} complianceFeatureVersionId 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.getVersion('00000000-0000-0000-0000-000000000000');
   * ```
   * @openapi operation=getComplianceFeatureVersion path=/complianceFeatureVersions/{complianceFeatureVersionId} method=GET
   * @memberof ComplianceFeatureApi
   */
  getVersion(complianceFeatureVersionId: UUID): Promise<ComplianceFeatureVersionExtended>;

  /**
   * Returns compliance feature types
   * @summary Returns compliance feature types
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @openapi operation=listComplianceFeatureTypes path=/complianceFeatureTypes method=GET
   * @memberof ComplianceFeatureApi
   */
  listComplianceFeatureTypes(): Promise<Array<ComplianceFeatureTypeEnum>>;

  /**
   * List a compliance features versions slim
   * @summary List a compliance features versions slim
   * @param {UUID} complianceFeatureId 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.listVersionsSlim('00000000-0000-0000-0000-000000000000');
   * ```
   * @openapi operation=listComplianceFeatureVersionsSlim path=/complianceFeatures/{complianceFeatureId}/versions method=GET
   * @memberof ComplianceFeatureApi
   */
  listVersionsSlim(complianceFeatureId: UUID): Promise<Array<VersionSlim>>;

  /**
   * List all compliance features
   * @summary List all compliance features
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {SortObject} [sort] 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.list(1, 1, null);
   * ```
   * @openapi operation=listComplianceFeatures path=/complianceFeatures method=GET
   * @memberof ComplianceFeatureApi
   */
  list(pageNumber?: number, pageSize?: number, sort?: SortObject): Promise<PagedResults<ComplianceFeatureExtended>>;

  /**
   * Search compliance features
   * @summary Search compliance features
   * @param {SearchComplianceFeatureBody} searchComplianceFeatureBody 
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {SortObject} [sort] 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.search(null, 1, 1, null);
   * ```
   * @openapi operation=searchComplianceFeatures path=/complianceFeatureSearch method=POST
   * @memberof ComplianceFeatureApi
   */
  search(searchComplianceFeatureBody: SearchComplianceFeatureBody, pageNumber?: number, pageSize?: number, sort?: SortObject): Promise<PagedResults<ComplianceFeatureExtended>>;

  /**
   * Returns search options for compliance features by columnName and search
   * @summary Returns search options for compliance features by columnName and search
   * @param {string} columnName 
   * @param {string} search 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.searchColumnOptions('columnName', 'search');
   * ```
   * @openapi operation=searchComplianceFeaturesColumnOptions path=/complianceFeatureSearch/searchOptions method=GET
   * @memberof ComplianceFeatureApi
   */
  searchColumnOptions(columnName: string, search: string): Promise<ResultsSearchOptionsWrapper>;

  /**
   * Returns options/filters for compliance features
   * @summary Returns options/filters for compliance features
   * @param {UUID} [standard] 
   * @param {Array<UUID>} [products] 
   * @param {Array<UUID>} [segments] 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.searchComplianceFeaturesOptions('00000000-0000-0000-0000-000000000000', null, null);
   * ```
   * @openapi operation=searchComplianceFeaturesOptions path=/complianceFeatureSearch/options method=GET
   * @memberof ComplianceFeatureApi
   */
  searchComplianceFeaturesOptions(standard?: UUID, products?: Array<UUID>, segments?: Array<UUID>): Promise<ResultsColumnOptionsWrapper>;

}

/**
 * ComplianceFeatureProducerApi - interface
 * Producer interface for ComplianceFeature
 * @export
 * @interface ComplianceFeatureProducerApi
 */
export interface ComplianceFeatureProducerApi {
  /**
  * Get compliance feature by id
  * @summary Get compliance feature by id
  * @param {UUID} complianceFeatureId 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=getComplianceFeature path=/complianceFeatures/{complianceFeatureId} method=GET
  * @memberof ComplianceFeature
  */
  get(complianceFeatureId: UUID): Promise<ComplianceFeatureExtended>;
  /**
  * Get a compliance feature version
  * @summary Get a compliance feature version
  * @param {UUID} complianceFeatureVersionId 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=getComplianceFeatureVersion path=/complianceFeatureVersions/{complianceFeatureVersionId} method=GET
  * @memberof ComplianceFeature
  */
  getVersion(complianceFeatureVersionId: UUID): Promise<ComplianceFeatureVersionExtended>;
  /**
  * Returns compliance feature types
  * @summary Returns compliance feature types
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=listComplianceFeatureTypes path=/complianceFeatureTypes method=GET
  * @memberof ComplianceFeature
  */
  listComplianceFeatureTypes(): Promise<Array<ComplianceFeatureTypeEnum>>;
  /**
  * List a compliance features versions slim
  * @summary List a compliance features versions slim
  * @param {UUID} complianceFeatureId 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=listComplianceFeatureVersionsSlim path=/complianceFeatures/{complianceFeatureId}/versions method=GET
  * @memberof ComplianceFeature
  */
  listVersionsSlim(complianceFeatureId: UUID): Promise<Array<VersionSlim>>;
  /**
  * List all compliance features
  * @summary List all compliance features
  * @param {SortObject} [sort] 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=listComplianceFeatures path=/complianceFeatures method=GET
  * @memberof ComplianceFeature
  */
  list(results: PagedResults<ComplianceFeatureExtended>, sort?: SortObject): Promise<void>;
  /**
  * Search compliance features
  * @summary Search compliance features
  * @param {SearchComplianceFeatureBody} searchComplianceFeatureBody 
  * @param {SortObject} [sort] 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchComplianceFeatures path=/complianceFeatureSearch method=POST
  * @memberof ComplianceFeature
  */
  search(results: PagedResults<ComplianceFeatureExtended>, searchComplianceFeatureBody: SearchComplianceFeatureBody, sort?: SortObject): Promise<void>;
  /**
  * Returns search options for compliance features by columnName and search
  * @summary Returns search options for compliance features by columnName and search
  * @param {string} columnName 
  * @param {string} search 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchComplianceFeaturesColumnOptions path=/complianceFeatureSearch/searchOptions method=GET
  * @memberof ComplianceFeature
  */
  searchColumnOptions(columnName: string, search: string): Promise<ResultsSearchOptionsWrapper>;
  /**
  * Returns options/filters for compliance features
  * @summary Returns options/filters for compliance features
  * @param {UUID} [standard] 
  * @param {Array<UUID>} [products] 
  * @param {Array<UUID>} [segments] 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchComplianceFeaturesOptions path=/complianceFeatureSearch/options method=GET
  * @memberof ComplianceFeature
  */
  searchComplianceFeaturesOptions(standard?: UUID, products?: Array<UUID>, segments?: Array<UUID>): Promise<ResultsColumnOptionsWrapper>;
}

export class ComplianceFeatureApiMappingImpl implements ComplianceFeatureApi {
  private producer: ComplianceFeatureProducerApi;
  constructor(producer: ComplianceFeatureProducerApi) {
    this.producer = producer;
  }

  /**
   * Get compliance feature by id
   * @summary Get compliance feature by id
   * @param complianceFeatureId 
   * @openapi operation=getComplianceFeature path=/complianceFeatures/{complianceFeatureId} method=GET
   */
  public async get(complianceFeatureId: UUID): Promise<ComplianceFeatureExtended> {
    // verify required parameter 'complianceFeatureId' is not null or undefined
    if (complianceFeatureId === null || complianceFeatureId === undefined) {
      throw new ParameterRequiredError('complianceFeatureId');
    }
    return this.producer.get(complianceFeatureId);
  }
  /**
   * Get a compliance feature version
   * @summary Get a compliance feature version
   * @param complianceFeatureVersionId 
   * @openapi operation=getComplianceFeatureVersion path=/complianceFeatureVersions/{complianceFeatureVersionId} method=GET
   */
  public async getVersion(complianceFeatureVersionId: UUID): Promise<ComplianceFeatureVersionExtended> {
    // verify required parameter 'complianceFeatureVersionId' is not null or undefined
    if (complianceFeatureVersionId === null || complianceFeatureVersionId === undefined) {
      throw new ParameterRequiredError('complianceFeatureVersionId');
    }
    return this.producer.getVersion(complianceFeatureVersionId);
  }
  /**
   * Returns compliance feature types
   * @summary Returns compliance feature types
   * @openapi operation=listComplianceFeatureTypes path=/complianceFeatureTypes method=GET
   */
  public async listComplianceFeatureTypes(): Promise<Array<ComplianceFeatureTypeEnum>> {
    return this.producer.listComplianceFeatureTypes();
  }
  /**
   * List a compliance features versions slim
   * @summary List a compliance features versions slim
   * @param complianceFeatureId 
   * @openapi operation=listComplianceFeatureVersionsSlim path=/complianceFeatures/{complianceFeatureId}/versions method=GET
   */
  public async listVersionsSlim(complianceFeatureId: UUID): Promise<Array<VersionSlim>> {
    // verify required parameter 'complianceFeatureId' is not null or undefined
    if (complianceFeatureId === null || complianceFeatureId === undefined) {
      throw new ParameterRequiredError('complianceFeatureId');
    }
    return this.producer.listVersionsSlim(complianceFeatureId);
  }
  /**
   * List all compliance features
   * @summary List all compliance features
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param sort 
   * @openapi operation=listComplianceFeatures path=/complianceFeatures method=GET
   */
  public async list(pageNumber: number = 1, pageSize: number = 50, sort?: SortObject): Promise<PagedResults<ComplianceFeatureExtended>> {
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<ComplianceFeatureExtended>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    await this.producer.list(bag, sort);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
  /**
   * Search compliance features
   * @summary Search compliance features
   * @param searchComplianceFeatureBody 
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param sort 
   * @openapi operation=searchComplianceFeatures path=/complianceFeatureSearch method=POST
   */
  public async search(searchComplianceFeatureBody: SearchComplianceFeatureBody, pageNumber: number = 1, pageSize: number = 50, sort?: SortObject): Promise<PagedResults<ComplianceFeatureExtended>> {
    // verify required parameter 'searchComplianceFeatureBody' is not null or undefined
    if (searchComplianceFeatureBody === null || searchComplianceFeatureBody === undefined) {
      throw new ParameterRequiredError('searchComplianceFeatureBody');
    }
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<ComplianceFeatureExtended>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    await this.producer.search(bag, searchComplianceFeatureBody, sort);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
  /**
   * Returns search options for compliance features by columnName and search
   * @summary Returns search options for compliance features by columnName and search
   * @param columnName 
   * @param search 
   * @openapi operation=searchComplianceFeaturesColumnOptions path=/complianceFeatureSearch/searchOptions method=GET
   */
  public async searchColumnOptions(columnName: string, search: string): Promise<ResultsSearchOptionsWrapper> {
    // verify required parameter 'columnName' is not null or undefined
    if (columnName === null || columnName === undefined || columnName === '') {
      throw new ParameterRequiredError('columnName');
    }
    // verify required parameter 'search' is not null or undefined
    if (search === null || search === undefined || search === '') {
      throw new ParameterRequiredError('search');
    }
    return this.producer.searchColumnOptions(columnName, search);
  }
  /**
   * Returns options/filters for compliance features
   * @summary Returns options/filters for compliance features
   * @param standard 
   * @param products 
   * @param segments 
   * @openapi operation=searchComplianceFeaturesOptions path=/complianceFeatureSearch/options method=GET
   */
  public async searchComplianceFeaturesOptions(standard?: UUID, products?: Array<UUID>, segments?: Array<UUID>): Promise<ResultsColumnOptionsWrapper> {
    return this.producer.searchComplianceFeaturesOptions(standard, products, segments);
  }
}

/**
 * Wrap producer with mapping implementation
 */
export function wrapComplianceFeatureProducer(producer: ComplianceFeatureProducerApi): ComplianceFeatureApi {
  return new ComplianceFeatureApiMappingImpl(producer);
}

/**
 * ComplianceFeatureApiHttpImpl - Direct HTTP implementation
 *
 * Makes direct HTTP calls to the API using Axios.
 * Used by SDK clients for platform service access.
 */
export class ComplianceFeatureApiHttpImpl implements ComplianceFeatureProducerApi {
  private client: AxiosInstance;
  private headers: Record<string, string>;

  constructor(client: AxiosInstance, headers: Record<string, string> = {}) {
    this.client = client;
    this.headers = headers;
  }

  async get(complianceFeatureId: UUID): Promise<ComplianceFeatureExtended> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/complianceFeatures/{complianceFeatureId}';
  _path = _path.replace('{complianceFeatureId}', encodeURIComponent(String(complianceFeatureId)));
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'ComplianceFeatureExtended')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async getVersion(complianceFeatureVersionId: UUID): Promise<ComplianceFeatureVersionExtended> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/complianceFeatureVersions/{complianceFeatureVersionId}';
  _path = _path.replace('{complianceFeatureVersionId}', encodeURIComponent(String(complianceFeatureVersionId)));
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'ComplianceFeatureVersionExtended')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async listComplianceFeatureTypes(): Promise<Array<ComplianceFeatureTypeEnum>> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/complianceFeatureTypes';
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'Array<ComplianceFeatureTypeEnum>')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async listVersionsSlim(complianceFeatureId: UUID): Promise<Array<VersionSlim>> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/complianceFeatures/{complianceFeatureId}/versions';
  _path = _path.replace('{complianceFeatureId}', encodeURIComponent(String(complianceFeatureId)));
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'Array<VersionSlim>')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async list(results: PagedResults<ComplianceFeatureExtended>, sort?: SortObject): Promise<void> {
  const _body = {
      sort,
  };
  let _path = '/complianceFeatures';
  return this.client.get(
    _path,
    {
      params: {
        ..._body,
        pageNumber: results.pageNumber,
        pageSize: results.pageSize,
      }
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<ComplianceFeatureExtended>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}/complianceFeatures`);
      results.httpMethod = HttpMethod.Get;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'ComplianceFeatureExtended');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async search(results: PagedResults<ComplianceFeatureExtended>, searchComplianceFeatureBody: SearchComplianceFeatureBody, sort?: SortObject): Promise<void> {
  const _body = {
      searchComplianceFeatureBody,sort,
  };
  let _path = '/complianceFeatureSearch';
  return this.client.post(
    _path,
    {
      ..._body,
      pageNumber: results.pageNumber,
      pageSize: results.pageSize,
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<ComplianceFeatureExtended>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}/complianceFeatureSearch`);
      results.httpMethod = HttpMethod.Post;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'ComplianceFeatureExtended');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async searchColumnOptions(columnName: string, search: string): Promise<ResultsSearchOptionsWrapper> {
  const _queryParams = {
      columnName,search,
  };
  const _bodyParams = {
      
  };
  let _path = '/complianceFeatureSearch/searchOptions';
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'ResultsSearchOptionsWrapper')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async searchComplianceFeaturesOptions(standard?: UUID, products?: Array<UUID>, segments?: Array<UUID>): Promise<ResultsColumnOptionsWrapper> {
  const _queryParams = {
      standard,products,segments,
  };
  const _bodyParams = {
      
  };
  let _path = '/complianceFeatureSearch/options';
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'ResultsColumnOptionsWrapper')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
}
