/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AxiosInstance } from 'axios';
import { AppStructure, CmdbData } from '../model/index.js';
import { URL, EnumValue, IllegalArgumentError, PagedResults, CoreError, ParameterRequiredError, UnexpectedError, HttpMethod } from '@zerobias-org/types-core-js';
import { RequestFile, ObjectSerializer } from '../model/index.js';

export namespace NavigationApi {
}

/**
 * NavigationApi - interface
 * @export
 * @interface NavigationApi
 */
export interface NavigationApi {
  /**
   * Retrieves needed values for organization/user handling
   * @summary Retrieves needed values for organization/user handling
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @openapi operation=getCMDBData path=/navigation/cmdbInfos method=GET
   * @memberof NavigationApi
   */
  getCMDBData(): Promise<CmdbData>;

  /**
   * Retrieves navigation items
   * @summary Retrieves navigation items
   * @param {string} [uiVersion] Filter by UI version
   * @param {boolean} [log] Whether to log or not
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.getNavigationItems('uiVersion', true);
   * ```
   * @openapi operation=getNavigationItems path=/navigation/items method=GET
   * @memberof NavigationApi
   */
  getNavigationItems(uiVersion?: string, log?: boolean): Promise<Array<AppStructure>>;

}

/**
 * NavigationProducerApi - interface
 * Producer interface for Navigation
 * @export
 * @interface NavigationProducerApi
 */
export interface NavigationProducerApi {
  /**
  * Retrieves needed values for organization/user handling
  * @summary Retrieves needed values for organization/user handling
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=getCMDBData path=/navigation/cmdbInfos method=GET
  * @memberof Navigation
  */
  getCMDBData(): Promise<CmdbData>;
  /**
  * Retrieves navigation items
  * @summary Retrieves navigation items
  * @param {string} [uiVersion] Filter by UI version
  * @param {boolean} [log] Whether to log or not
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=getNavigationItems path=/navigation/items method=GET
  * @memberof Navigation
  */
  getNavigationItems(uiVersion?: string, log?: boolean): Promise<Array<AppStructure>>;
}

export class NavigationApiMappingImpl implements NavigationApi {
  private producer: NavigationProducerApi;
  constructor(producer: NavigationProducerApi) {
    this.producer = producer;
  }

  /**
   * Retrieves needed values for organization/user handling
   * @summary Retrieves needed values for organization/user handling
   * @openapi operation=getCMDBData path=/navigation/cmdbInfos method=GET
   */
  public async getCMDBData(): Promise<CmdbData> {
    return this.producer.getCMDBData();
  }
  /**
   * Retrieves navigation items
   * @summary Retrieves navigation items
   * @param uiVersion Filter by UI version
   * @param log Whether to log or not
   * @openapi operation=getNavigationItems path=/navigation/items method=GET
   */
  public async getNavigationItems(uiVersion?: string, log?: boolean): Promise<Array<AppStructure>> {
    return this.producer.getNavigationItems(uiVersion, log);
  }
}

/**
 * Wrap producer with mapping implementation
 */
export function wrapNavigationProducer(producer: NavigationProducerApi): NavigationApi {
  return new NavigationApiMappingImpl(producer);
}

/**
 * NavigationApiHttpImpl - Direct HTTP implementation
 *
 * Makes direct HTTP calls to the API using Axios.
 * Used by SDK clients for platform service access.
 */
export class NavigationApiHttpImpl implements NavigationProducerApi {
  private client: AxiosInstance;
  private headers: Record<string, string>;

  constructor(client: AxiosInstance, headers: Record<string, string> = {}) {
    this.client = client;
    this.headers = headers;
  }

  async getCMDBData(): Promise<CmdbData> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/navigation/cmdbInfos';
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'CmdbData')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async getNavigationItems(uiVersion?: string, log?: boolean): Promise<Array<AppStructure>> {
  const _queryParams = {
      uiVersion,log,
  };
  const _bodyParams = {
      
  };
  let _path = '/navigation/items';
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'Array<AppStructure>')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
}
