/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AxiosInstance } from 'axios';
import { CatalogSchema, ResultsColumnOptionsWrapper, SearchSchemaBody, SortObject } from '../model/index.js';
import { URL, EnumValue, IllegalArgumentError, PagedResults, Int32, UUID, CoreError, ParameterRequiredError, UnexpectedError, HttpMethod } from '@zerobias-org/types-core-js';
import { RequestFile, ObjectSerializer } from '../model/index.js';

export namespace SchemaApi {
}

/**
 * SchemaApi - interface
 * @export
 * @interface SchemaApi
 */
export interface SchemaApi {
  /**
   * Returns overview info for auditlogic catalog
   * @summary Returns overview info for auditlogic catalog
   * @param {UUID} artifactOrVersionId 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.get('00000000-0000-0000-0000-000000000000');
   * ```
   * @openapi operation=getSchema path=/schemas/{artifactOrVersionId} method=GET
   * @memberof SchemaApi
   */
  get(artifactOrVersionId: UUID): Promise<CatalogSchema>;

  /**
   * Search all catalog schemas
   * @summary Search all catalog schemas
   * @param {SearchSchemaBody} searchSchemaBody 
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {SortObject} [sort] 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.search(null, 1, 1, null);
   * ```
   * @openapi operation=searchSchemas path=/schemaSearch method=POST
   * @memberof SchemaApi
   */
  search(searchSchemaBody: SearchSchemaBody, pageNumber?: number, pageSize?: number, sort?: SortObject): Promise<PagedResults<CatalogSchema>>;

  /**
   * Returns options/filters for schemas
   * @summary Returns options/filters for schemas
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @openapi operation=searchSchemasOptions path=/schemaSearch/options method=GET
   * @memberof SchemaApi
   */
  searchSchemasOptions(): Promise<ResultsColumnOptionsWrapper>;

}

/**
 * SchemaProducerApi - interface
 * Producer interface for Schema
 * @export
 * @interface SchemaProducerApi
 */
export interface SchemaProducerApi {
  /**
  * Returns overview info for auditlogic catalog
  * @summary Returns overview info for auditlogic catalog
  * @param {UUID} artifactOrVersionId 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=getSchema path=/schemas/{artifactOrVersionId} method=GET
  * @memberof Schema
  */
  get(artifactOrVersionId: UUID): Promise<CatalogSchema>;
  /**
  * Search all catalog schemas
  * @summary Search all catalog schemas
  * @param {SearchSchemaBody} searchSchemaBody 
  * @param {SortObject} [sort] 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchSchemas path=/schemaSearch method=POST
  * @memberof Schema
  */
  search(results: PagedResults<CatalogSchema>, searchSchemaBody: SearchSchemaBody, sort?: SortObject): Promise<void>;
  /**
  * Returns options/filters for schemas
  * @summary Returns options/filters for schemas
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=searchSchemasOptions path=/schemaSearch/options method=GET
  * @memberof Schema
  */
  searchSchemasOptions(): Promise<ResultsColumnOptionsWrapper>;
}

export class SchemaApiMappingImpl implements SchemaApi {
  private producer: SchemaProducerApi;
  constructor(producer: SchemaProducerApi) {
    this.producer = producer;
  }

  /**
   * Returns overview info for auditlogic catalog
   * @summary Returns overview info for auditlogic catalog
   * @param artifactOrVersionId 
   * @openapi operation=getSchema path=/schemas/{artifactOrVersionId} method=GET
   */
  public async get(artifactOrVersionId: UUID): Promise<CatalogSchema> {
    // verify required parameter 'artifactOrVersionId' is not null or undefined
    if (artifactOrVersionId === null || artifactOrVersionId === undefined) {
      throw new ParameterRequiredError('artifactOrVersionId');
    }
    return this.producer.get(artifactOrVersionId);
  }
  /**
   * Search all catalog schemas
   * @summary Search all catalog schemas
   * @param searchSchemaBody 
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param sort 
   * @openapi operation=searchSchemas path=/schemaSearch method=POST
   */
  public async search(searchSchemaBody: SearchSchemaBody, pageNumber: number = 1, pageSize: number = 50, sort?: SortObject): Promise<PagedResults<CatalogSchema>> {
    // verify required parameter 'searchSchemaBody' is not null or undefined
    if (searchSchemaBody === null || searchSchemaBody === undefined) {
      throw new ParameterRequiredError('searchSchemaBody');
    }
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<CatalogSchema>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    await this.producer.search(bag, searchSchemaBody, sort);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
  /**
   * Returns options/filters for schemas
   * @summary Returns options/filters for schemas
   * @openapi operation=searchSchemasOptions path=/schemaSearch/options method=GET
   */
  public async searchSchemasOptions(): Promise<ResultsColumnOptionsWrapper> {
    return this.producer.searchSchemasOptions();
  }
}

/**
 * Wrap producer with mapping implementation
 */
export function wrapSchemaProducer(producer: SchemaProducerApi): SchemaApi {
  return new SchemaApiMappingImpl(producer);
}

/**
 * SchemaApiHttpImpl - Direct HTTP implementation
 *
 * Makes direct HTTP calls to the API using Axios.
 * Used by SDK clients for platform service access.
 */
export class SchemaApiHttpImpl implements SchemaProducerApi {
  private client: AxiosInstance;
  private headers: Record<string, string>;

  constructor(client: AxiosInstance, headers: Record<string, string> = {}) {
    this.client = client;
    this.headers = headers;
  }

  async get(artifactOrVersionId: UUID): Promise<CatalogSchema> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/schemas/{artifactOrVersionId}';
  _path = _path.replace('{artifactOrVersionId}', encodeURIComponent(String(artifactOrVersionId)));
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'CatalogSchema')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async search(results: PagedResults<CatalogSchema>, searchSchemaBody: SearchSchemaBody, sort?: SortObject): Promise<void> {
  const _body = {
      searchSchemaBody,sort,
  };
  let _path = '/schemaSearch';
  return this.client.post(
    _path,
    {
      ..._body,
      pageNumber: results.pageNumber,
      pageSize: results.pageSize,
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<CatalogSchema>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}/schemaSearch`);
      results.httpMethod = HttpMethod.Post;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'CatalogSchema');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async searchSchemasOptions(): Promise<ResultsColumnOptionsWrapper> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/schemaSearch/options';
  return this.client.get(
    _path,
    { params: _queryParams })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'ResultsColumnOptionsWrapper')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
}
