/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const AttackPatternSkillLevel = {
  /**  */
  High: EnumValue.instance('AttackPatternSkillLevel', 'High', 'high'),
  /**  */
  Medium: EnumValue.instance('AttackPatternSkillLevel', 'Medium', 'medium'),
  /**  */
  Low: EnumValue.instance('AttackPatternSkillLevel', 'Low', 'low'),

  from(val: string | number): EnumValue {
    if (AttackPatternSkillLevel[val]) {
      return AttackPatternSkillLevel[val];
    }
    const byValue = AttackPatternSkillLevel.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid AttackPatternSkillLevel`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(AttackPatternSkillLevel)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => AttackPatternSkillLevel[t]);
  }
} as const;

export type AttackPatternSkillLevelDef = typeof AttackPatternSkillLevel[keyof typeof AttackPatternSkillLevel];
