/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const BoundaryAlertOriginType = {
  /** A boundary alert bot resource */
  BoundaryAlertBot: EnumValue.instance('BoundaryAlertOriginType', 'BoundaryAlertBot', 'boundary_alert_bot'),
  /** A trigger */
  Trigger: EnumValue.instance('BoundaryAlertOriginType', 'Trigger', 'trigger'),

  from(val: string | number): EnumValue {
    if (BoundaryAlertOriginType[val]) {
      return BoundaryAlertOriginType[val];
    }
    const byValue = BoundaryAlertOriginType.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid BoundaryAlertOriginType`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(BoundaryAlertOriginType)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => BoundaryAlertOriginType[t]);
  }
} as const;

export type BoundaryAlertOriginTypeDef = typeof BoundaryAlertOriginType[keyof typeof BoundaryAlertOriginType];
