/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CatalogPublishStatusEnumDef } from './CatalogPublishStatusEnum.js';
import { CatalogScopeDef } from './CatalogScope.js';
import { CatalogPublishStatusEnum } from './CatalogPublishStatusEnum.js';
import { CatalogScope } from './CatalogScope.js';
import { Semver, UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Compliance feature version schema
*/
export class ComplianceFeatureVersionAllOf {
  'complianceFeatureId': UUID;
  'versionId': UUID;
  'versionSemver': Semver;
  'versionValue': number;
  'versionFloatValue': number;
  'status': CatalogPublishStatusEnumDef;
  'scope': CatalogScopeDef;
  'code': string;
  'externalId': string;
  'complianceFeatureTypes': Array<string>;
  'createdBy': UUID;
  'classOfferingIds': Array<UUID>;
  'segmentOfferingIds': Array<UUID>;
  'productEditionOfferingIds': Array<UUID>;
  'elementIds': Array<UUID>;
  'roleIds': Array<UUID>;
  'implementationIds': Array<UUID>;
  'standardIds': Array<UUID>;
  'packageCode'?: string;
  'artifactVersionId'?: UUID;
  'updatedBy'?: UUID;
  'logoFileVersionId'?: UUID;
  /**
  * Task created for this compliance feature version
  */
  'taskId'?: UUID | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "complianceFeatureId",
      "baseName": "complianceFeatureId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "versionId",
      "baseName": "versionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "versionSemver",
      "baseName": "versionSemver",
      // false
      // Semver
      // Semver
      "type": "Semver",
      "format": "semver"
    },
    {
      "name": "versionValue",
      "baseName": "versionValue",
      // false
      // number
      // number
      "type": "number",
      "format": "int64"
    },
    {
      "name": "versionFloatValue",
      "baseName": "versionFloatValue",
      // false
      // number
      // number
      "type": "number",
      "format": "float"
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // CatalogPublishStatusEnum
      // CatalogPublishStatusEnumDef
      "type": "CatalogPublishStatusEnum",
      "format": ""
    },
    {
      "name": "scope",
      "baseName": "scope",
      // false
      // CatalogScope
      // CatalogScopeDef
      "type": "CatalogScope",
      "format": ""
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "externalId",
      "baseName": "externalId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "complianceFeatureTypes",
      "baseName": "complianceFeatureTypes",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "createdBy",
      "baseName": "createdBy",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "classOfferingIds",
      "baseName": "classOfferingIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "segmentOfferingIds",
      "baseName": "segmentOfferingIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "productEditionOfferingIds",
      "baseName": "productEditionOfferingIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "elementIds",
      "baseName": "elementIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "roleIds",
      "baseName": "roleIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "implementationIds",
      "baseName": "implementationIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "standardIds",
      "baseName": "standardIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "artifactVersionId",
      "baseName": "artifactVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "updatedBy",
      "baseName": "updatedBy",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "logoFileVersionId",
      "baseName": "logoFileVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "taskId",
      "baseName": "taskId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return ComplianceFeatureVersionAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): ComplianceFeatureVersionAllOf {
    return ObjectSerializer.deserialize(obj, 'ComplianceFeatureVersionAllOf');
  }

  constructor(complianceFeatureId: UUID, versionId: UUID, versionSemver: Semver, versionValue: number, versionFloatValue: number, status: CatalogPublishStatusEnumDef, scope: CatalogScopeDef, code: string, externalId: string, complianceFeatureTypes: Array<string>, createdBy: UUID, classOfferingIds: Array<UUID>, segmentOfferingIds: Array<UUID>, productEditionOfferingIds: Array<UUID>, elementIds: Array<UUID>, roleIds: Array<UUID>, implementationIds: Array<UUID>, standardIds: Array<UUID>, packageCode?: string, artifactVersionId?: UUID, updatedBy?: UUID, logoFileVersionId?: UUID, taskId?: UUID) {
    this.complianceFeatureId = complianceFeatureId;
    this.versionId = versionId;
    this.versionSemver = versionSemver;
    this.versionValue = versionValue;
    this.versionFloatValue = versionFloatValue;
    this.status = status;
    this.scope = scope;
    this.code = code;
    this.externalId = externalId;
    this.complianceFeatureTypes = complianceFeatureTypes;
    this.createdBy = createdBy;
    this.classOfferingIds = classOfferingIds;
    this.segmentOfferingIds = segmentOfferingIds;
    this.productEditionOfferingIds = productEditionOfferingIds;
    this.elementIds = elementIds;
    this.roleIds = roleIds;
    this.implementationIds = implementationIds;
    this.standardIds = standardIds;
    this.packageCode = packageCode;
    this.artifactVersionId = artifactVersionId;
    this.updatedBy = updatedBy;
    this.logoFileVersionId = logoFileVersionId;
    this.taskId = taskId;
  }
}

