/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const CompareComplianceFeaturesGroupByEnum = {
  /**  */
  Feature: EnumValue.instance('CompareComplianceFeaturesGroupByEnum', 'Feature', 'feature'),
  /**  */
  Control: EnumValue.instance('CompareComplianceFeaturesGroupByEnum', 'Control', 'control'),

  from(val: string | number): EnumValue {
    if (CompareComplianceFeaturesGroupByEnum[val]) {
      return CompareComplianceFeaturesGroupByEnum[val];
    }
    const byValue = CompareComplianceFeaturesGroupByEnum.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid CompareComplianceFeaturesGroupByEnum`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(CompareComplianceFeaturesGroupByEnum)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => CompareComplianceFeaturesGroupByEnum[t]);
  }
} as const;

export type CompareComplianceFeaturesGroupByEnumDef = typeof CompareComplianceFeaturesGroupByEnum[keyof typeof CompareComplianceFeaturesGroupByEnum];
