/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Enum for CVSS searching
*/
export const CvssVersionEnum = {
  /**  */
  V2: EnumValue.instance('CvssVersionEnum', 'V2', 'v2'),
  /**  */
  V3: EnumValue.instance('CvssVersionEnum', 'V3', 'v3'),
  /**  */
  V4: EnumValue.instance('CvssVersionEnum', 'V4', 'v4'),

  from(val: string | number): EnumValue {
    if (CvssVersionEnum[val]) {
      return CvssVersionEnum[val];
    }
    const byValue = CvssVersionEnum.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid CvssVersionEnum`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(CvssVersionEnum)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => CvssVersionEnum[t]);
  }
} as const;

export type CvssVersionEnumDef = typeof CvssVersionEnum[keyof typeof CvssVersionEnum];
