/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CvssAttackComplexityDef } from './CvssAttackComplexity.js';
import { CvssV4SystemImpact } from './CvssV4SystemImpact.js';
import { CvssV4AttackRequirementsDef } from './CvssV4AttackRequirements.js';
import { CvssAttackVector } from './CvssAttackVector.js';
import { CvssV4AttackRequirements } from './CvssV4AttackRequirements.js';
import { CvssV4UserInteraction } from './CvssV4UserInteraction.js';
import { CvssAttackVectorDef } from './CvssAttackVector.js';
import { CvssPrivilegesRequiredDef } from './CvssPrivilegesRequired.js';
import { CvssAttackComplexity } from './CvssAttackComplexity.js';
import { CvssPrivilegesRequired } from './CvssPrivilegesRequired.js';
import { CvssV4SystemImpactDef } from './CvssV4SystemImpact.js';
import { CvssV4UserInteractionDef } from './CvssV4UserInteraction.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for a vulnerabilities CVSS v4
*/
export class CvssV4 {
  'vectorString': string;
  'baseScore': number;
  'version': string;
  'baseSeverity'?: string;
  'attackVector'?: CvssAttackVectorDef;
  'attackComplexity'?: CvssAttackComplexityDef;
  'attackRequirements'?: CvssV4AttackRequirementsDef;
  'privilegesRequired'?: CvssPrivilegesRequiredDef;
  'userInteraction'?: CvssV4UserInteractionDef;
  'vulnerableSystemConfidentialityImpact'?: CvssV4SystemImpactDef;
  'subsequentSystemConfidentialityImpact'?: CvssV4SystemImpactDef;
  'vulnerableSystemIntegrityImpact'?: CvssV4SystemImpactDef;
  'subsequentSystemIntegrityImpact'?: CvssV4SystemImpactDef;
  'vulnerableSystemAvailabilityImpact'?: CvssV4SystemImpactDef;
  'subsequentSystemAvailabilityImpact'?: CvssV4SystemImpactDef;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "vectorString",
      "baseName": "vectorString",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "baseScore",
      "baseName": "baseScore",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "version",
      "baseName": "version",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "baseSeverity",
      "baseName": "baseSeverity",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "attackVector",
      "baseName": "attackVector",
      // false
      // CvssAttackVector
      // CvssAttackVectorDef
      "type": "CvssAttackVector",
      "format": ""
    },
    {
      "name": "attackComplexity",
      "baseName": "attackComplexity",
      // false
      // CvssAttackComplexity
      // CvssAttackComplexityDef
      "type": "CvssAttackComplexity",
      "format": ""
    },
    {
      "name": "attackRequirements",
      "baseName": "attackRequirements",
      // false
      // CvssV4AttackRequirements
      // CvssV4AttackRequirementsDef
      "type": "CvssV4AttackRequirements",
      "format": ""
    },
    {
      "name": "privilegesRequired",
      "baseName": "privilegesRequired",
      // false
      // CvssPrivilegesRequired
      // CvssPrivilegesRequiredDef
      "type": "CvssPrivilegesRequired",
      "format": ""
    },
    {
      "name": "userInteraction",
      "baseName": "userInteraction",
      // false
      // CvssV4UserInteraction
      // CvssV4UserInteractionDef
      "type": "CvssV4UserInteraction",
      "format": ""
    },
    {
      "name": "vulnerableSystemConfidentialityImpact",
      "baseName": "vulnerableSystemConfidentialityImpact",
      // false
      // CvssV4SystemImpact
      // CvssV4SystemImpactDef
      "type": "CvssV4SystemImpact",
      "format": ""
    },
    {
      "name": "subsequentSystemConfidentialityImpact",
      "baseName": "subsequentSystemConfidentialityImpact",
      // false
      // CvssV4SystemImpact
      // CvssV4SystemImpactDef
      "type": "CvssV4SystemImpact",
      "format": ""
    },
    {
      "name": "vulnerableSystemIntegrityImpact",
      "baseName": "vulnerableSystemIntegrityImpact",
      // false
      // CvssV4SystemImpact
      // CvssV4SystemImpactDef
      "type": "CvssV4SystemImpact",
      "format": ""
    },
    {
      "name": "subsequentSystemIntegrityImpact",
      "baseName": "subsequentSystemIntegrityImpact",
      // false
      // CvssV4SystemImpact
      // CvssV4SystemImpactDef
      "type": "CvssV4SystemImpact",
      "format": ""
    },
    {
      "name": "vulnerableSystemAvailabilityImpact",
      "baseName": "vulnerableSystemAvailabilityImpact",
      // false
      // CvssV4SystemImpact
      // CvssV4SystemImpactDef
      "type": "CvssV4SystemImpact",
      "format": ""
    },
    {
      "name": "subsequentSystemAvailabilityImpact",
      "baseName": "subsequentSystemAvailabilityImpact",
      // false
      // CvssV4SystemImpact
      // CvssV4SystemImpactDef
      "type": "CvssV4SystemImpact",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return CvssV4.attributeTypeMap;
  }

  static newInstance(obj: any): CvssV4 {
    return ObjectSerializer.deserialize(obj, 'CvssV4');
  }

  constructor(vectorString: string, baseScore: number, version: string, baseSeverity?: string, attackVector?: CvssAttackVectorDef, attackComplexity?: CvssAttackComplexityDef, attackRequirements?: CvssV4AttackRequirementsDef, privilegesRequired?: CvssPrivilegesRequiredDef, userInteraction?: CvssV4UserInteractionDef, vulnerableSystemConfidentialityImpact?: CvssV4SystemImpactDef, subsequentSystemConfidentialityImpact?: CvssV4SystemImpactDef, vulnerableSystemIntegrityImpact?: CvssV4SystemImpactDef, subsequentSystemIntegrityImpact?: CvssV4SystemImpactDef, vulnerableSystemAvailabilityImpact?: CvssV4SystemImpactDef, subsequentSystemAvailabilityImpact?: CvssV4SystemImpactDef) {
    this.vectorString = vectorString;
    this.baseScore = baseScore;
    this.version = version;
    this.baseSeverity = baseSeverity;
    this.attackVector = attackVector;
    this.attackComplexity = attackComplexity;
    this.attackRequirements = attackRequirements;
    this.privilegesRequired = privilegesRequired;
    this.userInteraction = userInteraction;
    this.vulnerableSystemConfidentialityImpact = vulnerableSystemConfidentialityImpact;
    this.subsequentSystemConfidentialityImpact = subsequentSystemConfidentialityImpact;
    this.vulnerableSystemIntegrityImpact = vulnerableSystemIntegrityImpact;
    this.subsequentSystemIntegrityImpact = subsequentSystemIntegrityImpact;
    this.vulnerableSystemAvailabilityImpact = vulnerableSystemAvailabilityImpact;
    this.subsequentSystemAvailabilityImpact = subsequentSystemAvailabilityImpact;
  }
}

