/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { JsonTypeEnumDef } from './JsonTypeEnum.js';
import { JsonTypeEnum } from './JsonTypeEnum.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Describes a JSON or system type of data
*/
export class DataTypeAllOf {
  'dataTypeType': JsonTypeEnumDef;
  'pattern'?: string | null;
  'coreType'?: boolean | null;
  'packageCode'?: string | null;
  'enumInfoId'?: UUID | null;
  'examples'?: Array<string> | null;
  'artifactVersionId'?: UUID | null;
  'schemaId'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "dataTypeType",
      "baseName": "dataTypeType",
      // false
      // JsonTypeEnum
      // JsonTypeEnumDef
      "type": "JsonTypeEnum",
      "format": ""
    },
    {
      "name": "pattern",
      "baseName": "pattern",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "coreType",
      "baseName": "coreType",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "enumInfoId",
      "baseName": "enumInfoId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "examples",
      "baseName": "examples",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "artifactVersionId",
      "baseName": "artifactVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "schemaId",
      "baseName": "schemaId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return DataTypeAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): DataTypeAllOf {
    return ObjectSerializer.deserialize(obj, 'DataTypeAllOf');
  }

  constructor(dataTypeType: JsonTypeEnumDef, pattern?: string, coreType?: boolean, packageCode?: string, enumInfoId?: UUID, examples?: Array<string>, artifactVersionId?: UUID, schemaId?: UUID) {
    this.dataTypeType = dataTypeType;
    this.pattern = pattern;
    this.coreType = coreType;
    this.packageCode = packageCode;
    this.enumInfoId = enumInfoId;
    this.examples = examples;
    this.artifactVersionId = artifactVersionId;
    this.schemaId = schemaId;
  }
}

