/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CatalogSourceDef } from './CatalogSource.js';
import { CatalogSource } from './CatalogSource.js';
import { Resource } from './Resource.js';
import { ElementAllOf } from './ElementAllOf.js';
import { Nmtoken, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class Element {
  /**
  * Unique identifier
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  'code': string;
  'standardName': string;
  'standardExternalId': string;
  'standardId': UUID;
  'elementTypeId': UUID;
  'source': CatalogSourceDef;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  /**
  * A resource id which acts as a boundary/container for this resource.
  */
  'boundaryId'?: UUID;
  'externalId'?: string | null;
  'background'?: string;
  'objectId'?: UUID;
  'packageCode'?: string | null;
  'tagIds'?: Array<UUID>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "standardName",
      "baseName": "standardName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "standardExternalId",
      "baseName": "standardExternalId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "standardId",
      "baseName": "standardId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "elementTypeId",
      "baseName": "elementTypeId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "source",
      "baseName": "source",
      // false
      // CatalogSource
      // CatalogSourceDef
      "type": "CatalogSource",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "externalId",
      "baseName": "externalId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "background",
      "baseName": "background",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "objectId",
      "baseName": "objectId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "tagIds",
      "baseName": "tagIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return Element.attributeTypeMap;
  }

  static newInstance(obj: any): Element {
    return ObjectSerializer.deserialize(obj, 'Element');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, code: string, standardName: string, standardExternalId: string, standardId: UUID, elementTypeId: UUID, source: CatalogSourceDef, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, boundaryId?: UUID, externalId?: string, background?: string, objectId?: UUID, packageCode?: string, tagIds?: Array<UUID>) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.code = code;
    this.standardName = standardName;
    this.standardExternalId = standardExternalId;
    this.standardId = standardId;
    this.elementTypeId = elementTypeId;
    this.source = source;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.boundaryId = boundaryId;
    this.externalId = externalId;
    this.background = background;
    this.objectId = objectId;
    this.packageCode = packageCode;
    this.tagIds = tagIds;
  }
}

