/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { FindingSubject } from './FindingSubject.js';
import { TestResultEnumDef } from './TestResultEnum.js';
import { FindingTest } from './FindingTest.js';
import { TestResultEnum } from './TestResultEnum.js';
import { FindingExtendedVulnerability } from './FindingExtendedVulnerability.js';
import { FindingTestCase } from './FindingTestCase.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Finding extended schema
*/
export class FindingExtendedAllOf {
  'discoveredDate': Date;
  'result': TestResultEnumDef;
  'testCaseId': UUID;
  'testCase': FindingTestCase;
  'tests': Array<FindingTest>;
  'subjects': Array<FindingSubject>;
  'resolvedDate'?: Date | null;
  'vulnerabilities'?: Array<FindingExtendedVulnerability>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "discoveredDate",
      "baseName": "discoveredDate",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "result",
      "baseName": "result",
      // false
      // TestResultEnum
      // TestResultEnumDef
      "type": "TestResultEnum",
      "format": ""
    },
    {
      "name": "testCaseId",
      "baseName": "testCaseId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "testCase",
      "baseName": "testCase",
      // false
      // FindingTestCase
      // FindingTestCase
      "type": "FindingTestCase",
      "format": ""
    },
    {
      "name": "tests",
      "baseName": "tests",
      // false
      // Array&lt;FindingTest&gt;
      // Array&lt;FindingTest&gt;
      "type": "Array<FindingTest>",
      "format": ""
    },
    {
      "name": "subjects",
      "baseName": "subjects",
      // false
      // Array&lt;FindingSubject&gt;
      // Array&lt;FindingSubject&gt;
      "type": "Array<FindingSubject>",
      "format": ""
    },
    {
      "name": "resolvedDate",
      "baseName": "resolvedDate",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "vulnerabilities",
      "baseName": "vulnerabilities",
      // false
      // Array&lt;FindingExtendedVulnerability&gt;
      // Array&lt;FindingExtendedVulnerability&gt;
      "type": "Array<FindingExtendedVulnerability>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return FindingExtendedAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): FindingExtendedAllOf {
    return ObjectSerializer.deserialize(obj, 'FindingExtendedAllOf');
  }

  constructor(discoveredDate: Date, result: TestResultEnumDef, testCaseId: UUID, testCase: FindingTestCase, tests: Array<FindingTest>, subjects: Array<FindingSubject>, resolvedDate?: Date, vulnerabilities?: Array<FindingExtendedVulnerability>) {
    this.discoveredDate = discoveredDate;
    this.result = result;
    this.testCaseId = testCaseId;
    this.testCase = testCase;
    this.tests = tests;
    this.subjects = subjects;
    this.resolvedDate = resolvedDate;
    this.vulnerabilities = vulnerabilities;
  }
}

