/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ObjectSerializer, RequestFile } from './index.js';

export class KbArticleExtendedAllOf {
  'appTemplateCode': string;
  'artifactName': string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "appTemplateCode",
      "baseName": "appTemplateCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "artifactName",
      "baseName": "artifactName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return KbArticleExtendedAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): KbArticleExtendedAllOf {
    return ObjectSerializer.deserialize(obj, 'KbArticleExtendedAllOf');
  }

  constructor(appTemplateCode: string, artifactName: string, ) {
    this.appTemplateCode = appTemplateCode;
    this.artifactName = artifactName;
  }
}

