/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const ProductServiceFilter = {
  /**  */
  Product: EnumValue.instance('ProductServiceFilter', 'Product', 'product'),
  /**  */
  Service: EnumValue.instance('ProductServiceFilter', 'Service', 'service'),
  /**  */
  Both: EnumValue.instance('ProductServiceFilter', 'Both', 'both'),

  from(val: string | number): EnumValue {
    if (ProductServiceFilter[val]) {
      return ProductServiceFilter[val];
    }
    const byValue = ProductServiceFilter.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid ProductServiceFilter`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(ProductServiceFilter)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => ProductServiceFilter[t]);
  }
} as const;

export type ProductServiceFilterDef = typeof ProductServiceFilter[keyof typeof ProductServiceFilter];
