/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class ProductComplianceFeatureEdition {
  'id': UUID;
  'latestVersionId': UUID;
  'name': string;
  'code': string;
  'description'?: string;
  'imageUrl'?: URL;
  'productComponentId'?: UUID;
  'productComponentVersionId'?: UUID;
  'productComponentName'?: string;
  'productComponentDescription'?: string;
  'productComponentImageUrl'?: URL;
  'productComponentCode'?: string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "latestVersionId",
      "baseName": "latestVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "productComponentId",
      "baseName": "productComponentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "productComponentVersionId",
      "baseName": "productComponentVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "productComponentName",
      "baseName": "productComponentName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "productComponentDescription",
      "baseName": "productComponentDescription",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "productComponentImageUrl",
      "baseName": "productComponentImageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "productComponentCode",
      "baseName": "productComponentCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return ProductComplianceFeatureEdition.attributeTypeMap;
  }

  static newInstance(obj: any): ProductComplianceFeatureEdition {
    return ObjectSerializer.deserialize(obj, 'ProductComplianceFeatureEdition');
  }

  constructor(id: UUID, latestVersionId: UUID, name: string, code: string, description?: string, imageUrl?: URL, productComponentId?: UUID, productComponentVersionId?: UUID, productComponentName?: string, productComponentDescription?: string, productComponentImageUrl?: URL, productComponentCode?: string) {
    this.id = id;
    this.latestVersionId = latestVersionId;
    this.name = name;
    this.code = code;
    this.description = description;
    this.imageUrl = imageUrl;
    this.productComponentId = productComponentId;
    this.productComponentVersionId = productComponentVersionId;
    this.productComponentName = productComponentName;
    this.productComponentDescription = productComponentDescription;
    this.productComponentImageUrl = productComponentImageUrl;
    this.productComponentCode = productComponentCode;
  }
}

