/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { PublishQueryStatusEnumDef } from './PublishQueryStatusEnum.js';
import { PublishQueryStatusEnum } from './PublishQueryStatusEnum.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Request body for search graphql querys
*/
export class SearchGraphqlQueryBody {
  'name'?: string;
  'description'?: string;
  'statuses'?: Array<PublishQueryStatusEnumDef>;
  'products'?: Array<UUID>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "statuses",
      "baseName": "statuses",
      // false
      // Array&lt;PublishQueryStatusEnum&gt;
      // Array&lt;PublishQueryStatusEnumDef&gt;
      "type": "Array<PublishQueryStatusEnum>",
      "format": ""
    },
    {
      "name": "products",
      "baseName": "products",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return SearchGraphqlQueryBody.attributeTypeMap;
  }

  static newInstance(obj: any): SearchGraphqlQueryBody {
    return ObjectSerializer.deserialize(obj, 'SearchGraphqlQueryBody');
  }

  constructor(name?: string, description?: string, statuses?: Array<PublishQueryStatusEnumDef>, products?: Array<UUID>) {
    this.name = name;
    this.description = description;
    this.statuses = statuses;
    this.products = products;
  }
}

