/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { VspStatusEnum } from './VspStatusEnum.js';
import { VspStatusEnumDef } from './VspStatusEnum.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Request body for searching compliance services
*/
export class SearchComplianceServiceBody {
  'search'?: string;
  'name'?: string;
  'code'?: string;
  'description'?: string;
  'externalId'?: string;
  'packageCode'?: string;
  'statuses'?: Array<VspStatusEnumDef>;
  'segmentVersions'?: Array<UUID>;
  'elements'?: Array<UUID>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "search",
      "baseName": "search",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "externalId",
      "baseName": "externalId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "statuses",
      "baseName": "statuses",
      // false
      // Array&lt;VspStatusEnum&gt;
      // Array&lt;VspStatusEnumDef&gt;
      "type": "Array<VspStatusEnum>",
      "format": ""
    },
    {
      "name": "segmentVersions",
      "baseName": "segmentVersions",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "elements",
      "baseName": "elements",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return SearchComplianceServiceBody.attributeTypeMap;
  }

  static newInstance(obj: any): SearchComplianceServiceBody {
    return ObjectSerializer.deserialize(obj, 'SearchComplianceServiceBody');
  }

  constructor(search?: string, name?: string, code?: string, description?: string, externalId?: string, packageCode?: string, statuses?: Array<VspStatusEnumDef>, segmentVersions?: Array<UUID>, elements?: Array<UUID>) {
    this.search = search;
    this.name = name;
    this.code = code;
    this.description = description;
    this.externalId = externalId;
    this.packageCode = packageCode;
    this.statuses = statuses;
    this.segmentVersions = segmentVersions;
    this.elements = elements;
  }
}

