/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { NavigationLabelTypeEnum } from './NavigationLabelTypeEnum.js';
import { NavigationItemStatusEnumDef } from './NavigationItemStatusEnum.js';
import { NavigationItemStatusEnum } from './NavigationItemStatusEnum.js';
import { NavigationLabelTypeEnumDef } from './NavigationLabelTypeEnum.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Structrure of an section in navigation items
*/
export class SectionStructure {
  'id': UUID;
  'ownerId': UUID;
  'resourceId': UUID;
  'resourceType': NavigationLabelTypeEnumDef;
  'label': string;
  'name': string;
  'uiVersion': string;
  'sectionOrder': number;
  'icon': string;
  'description': string;
  'status': NavigationItemStatusEnumDef;
  'boundaryId'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "resourceId",
      "baseName": "resourceId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "resourceType",
      "baseName": "resourceType",
      // false
      // NavigationLabelTypeEnum
      // NavigationLabelTypeEnumDef
      "type": "NavigationLabelTypeEnum",
      "format": ""
    },
    {
      "name": "label",
      "baseName": "label",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "uiVersion",
      "baseName": "uiVersion",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "sectionOrder",
      "baseName": "sectionOrder",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "icon",
      "baseName": "icon",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // NavigationItemStatusEnum
      // NavigationItemStatusEnumDef
      "type": "NavigationItemStatusEnum",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return SectionStructure.attributeTypeMap;
  }

  static newInstance(obj: any): SectionStructure {
    return ObjectSerializer.deserialize(obj, 'SectionStructure');
  }

  constructor(id: UUID, ownerId: UUID, resourceId: UUID, resourceType: NavigationLabelTypeEnumDef, label: string, name: string, uiVersion: string, sectionOrder: number, icon: string, description: string, status: NavigationItemStatusEnumDef, boundaryId?: UUID) {
    this.id = id;
    this.ownerId = ownerId;
    this.resourceId = resourceId;
    this.resourceType = resourceType;
    this.label = label;
    this.name = name;
    this.uiVersion = uiVersion;
    this.sectionOrder = sectionOrder;
    this.icon = icon;
    this.description = description;
    this.status = status;
    this.boundaryId = boundaryId;
  }
}

