/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { HostingTypeEnum } from './HostingTypeEnum.js';
import { FactoryTypeEnum } from './FactoryTypeEnum.js';
import { HostingTypeEnumDef } from './HostingTypeEnum.js';
import { FactoryTypeEnumDef } from './FactoryTypeEnum.js';
import { UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Request body for suggesting a new product
*/
export class SuggestNewProduct {
  'name': string;
  'code': string;
  'description': string;
  'url': URL;
  'segmentVersions': Array<UUID>;
  'vendorId': UUID;
  'factoryTypes': Array<FactoryTypeEnumDef>;
  'imageUrl'?: URL;
  'suiteId'?: UUID | null;
  'logoFileVersionId'?: UUID | null;
  'hostingTypes'?: Array<HostingTypeEnumDef> | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "segmentVersions",
      "baseName": "segmentVersions",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "vendorId",
      "baseName": "vendorId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "factoryTypes",
      "baseName": "factoryTypes",
      // false
      // Array&lt;FactoryTypeEnum&gt;
      // Array&lt;FactoryTypeEnumDef&gt;
      "type": "Array<FactoryTypeEnum>",
      "format": ""
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "suiteId",
      "baseName": "suiteId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "logoFileVersionId",
      "baseName": "logoFileVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "hostingTypes",
      "baseName": "hostingTypes",
      // false
      // Array&lt;HostingTypeEnum&gt;
      // Array&lt;HostingTypeEnumDef&gt;
      "type": "Array<HostingTypeEnum>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return SuggestNewProduct.attributeTypeMap;
  }

  static newInstance(obj: any): SuggestNewProduct {
    return ObjectSerializer.deserialize(obj, 'SuggestNewProduct');
  }

  constructor(name: string, code: string, description: string, url: URL, segmentVersions: Array<UUID>, vendorId: UUID, factoryTypes: Array<FactoryTypeEnumDef>, imageUrl?: URL, suiteId?: UUID, logoFileVersionId?: UUID, hostingTypes?: Array<HostingTypeEnumDef>) {
    this.name = name;
    this.code = code;
    this.description = description;
    this.url = url;
    this.segmentVersions = segmentVersions;
    this.vendorId = vendorId;
    this.factoryTypes = factoryTypes;
    this.imageUrl = imageUrl;
    this.suiteId = suiteId;
    this.logoFileVersionId = logoFileVersionId;
    this.hostingTypes = hostingTypes;
  }
}

