/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { TaskCustomFieldFilter } from './TaskCustomFieldFilter.js';
import { IdNameCodeDescriptionImageUrlObject } from './IdNameCodeDescriptionImageUrlObject.js';
import { IdNameDescriptionImageUrlObject } from './IdNameDescriptionImageUrlObject.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class TaskFilters {
  'activities': Array<IdNameDescriptionImageUrlObject>;
  'assigned': Array<IdNameCodeDescriptionImageUrlObject>;
  'accountable': Array<IdNameCodeDescriptionImageUrlObject>;
  'approvers': Array<IdNameCodeDescriptionImageUrlObject>;
  'notified': Array<IdNameCodeDescriptionImageUrlObject>;
  'parties': Array<IdNameCodeDescriptionImageUrlObject>;
  'roles': Array<IdNameDescriptionImageUrlObject>;
  'boundaries': Array<IdNameDescriptionImageUrlObject>;
  'customFields': Array<TaskCustomFieldFilter>;
  'phases': Array<string>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "activities",
      "baseName": "activities",
      // false
      // Array&lt;IdNameDescriptionImageUrlObject&gt;
      // Array&lt;IdNameDescriptionImageUrlObject&gt;
      "type": "Array<IdNameDescriptionImageUrlObject>",
      "format": ""
    },
    {
      "name": "assigned",
      "baseName": "assigned",
      // false
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      "type": "Array<IdNameCodeDescriptionImageUrlObject>",
      "format": ""
    },
    {
      "name": "accountable",
      "baseName": "accountable",
      // false
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      "type": "Array<IdNameCodeDescriptionImageUrlObject>",
      "format": ""
    },
    {
      "name": "approvers",
      "baseName": "approvers",
      // false
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      "type": "Array<IdNameCodeDescriptionImageUrlObject>",
      "format": ""
    },
    {
      "name": "notified",
      "baseName": "notified",
      // false
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      "type": "Array<IdNameCodeDescriptionImageUrlObject>",
      "format": ""
    },
    {
      "name": "parties",
      "baseName": "parties",
      // false
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      // Array&lt;IdNameCodeDescriptionImageUrlObject&gt;
      "type": "Array<IdNameCodeDescriptionImageUrlObject>",
      "format": ""
    },
    {
      "name": "roles",
      "baseName": "roles",
      // false
      // Array&lt;IdNameDescriptionImageUrlObject&gt;
      // Array&lt;IdNameDescriptionImageUrlObject&gt;
      "type": "Array<IdNameDescriptionImageUrlObject>",
      "format": ""
    },
    {
      "name": "boundaries",
      "baseName": "boundaries",
      // false
      // Array&lt;IdNameDescriptionImageUrlObject&gt;
      // Array&lt;IdNameDescriptionImageUrlObject&gt;
      "type": "Array<IdNameDescriptionImageUrlObject>",
      "format": ""
    },
    {
      "name": "customFields",
      "baseName": "customFields",
      // false
      // Array&lt;TaskCustomFieldFilter&gt;
      // Array&lt;TaskCustomFieldFilter&gt;
      "type": "Array<TaskCustomFieldFilter>",
      "format": ""
    },
    {
      "name": "phases",
      "baseName": "phases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return TaskFilters.attributeTypeMap;
  }

  static newInstance(obj: any): TaskFilters {
    return ObjectSerializer.deserialize(obj, 'TaskFilters');
  }

  constructor(activities: Array<IdNameDescriptionImageUrlObject>, assigned: Array<IdNameCodeDescriptionImageUrlObject>, accountable: Array<IdNameCodeDescriptionImageUrlObject>, approvers: Array<IdNameCodeDescriptionImageUrlObject>, notified: Array<IdNameCodeDescriptionImageUrlObject>, parties: Array<IdNameCodeDescriptionImageUrlObject>, roles: Array<IdNameDescriptionImageUrlObject>, boundaries: Array<IdNameDescriptionImageUrlObject>, customFields: Array<TaskCustomFieldFilter>, phases: Array<string>, ) {
    this.activities = activities;
    this.assigned = assigned;
    this.accountable = accountable;
    this.approvers = approvers;
    this.notified = notified;
    this.parties = parties;
    this.roles = roles;
    this.boundaries = boundaries;
    this.customFields = customFields;
    this.phases = phases;
  }
}

