/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Statuses for store vsps
*/
export const VspStatusEnum = {
  /**  */
  Draft: EnumValue.instance('VspStatusEnum', 'Draft', 'draft'),
  /**  */
  Active: EnumValue.instance('VspStatusEnum', 'Active', 'active'),
  /**  */
  Rejected: EnumValue.instance('VspStatusEnum', 'Rejected', 'rejected'),
  /**  */
  Deleted: EnumValue.instance('VspStatusEnum', 'Deleted', 'deleted'),
  /**  */
  Verified: EnumValue.instance('VspStatusEnum', 'Verified', 'verified'),
  /**  */
  Suggested: EnumValue.instance('VspStatusEnum', 'Suggested', 'suggested'),
  /**  */
  Publishing: EnumValue.instance('VspStatusEnum', 'Publishing', 'publishing'),

  from(val: string | number): EnumValue {
    if (VspStatusEnum[val]) {
      return VspStatusEnum[val];
    }
    const byValue = VspStatusEnum.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid VspStatusEnum`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(VspStatusEnum)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => VspStatusEnum[t]);
  }
} as const;

export type VspStatusEnumDef = typeof VspStatusEnum[keyof typeof VspStatusEnum];
