/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AlertSubscriptionExtendedParty } from './AlertSubscriptionExtendedParty.js';
import { IdNameDescriptionObject } from './IdNameDescriptionObject.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class AlertSubscriptionExtendedAllOf {
  'role'?: IdNameDescriptionObject;
  'boundaryRole'?: IdNameDescriptionObject;
  'boundaryParty'?: AlertSubscriptionExtendedParty;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "role",
      "baseName": "role",
      // false
      // IdNameDescriptionObject
      // IdNameDescriptionObject
      "type": "IdNameDescriptionObject",
      "format": ""
    },
    {
      "name": "boundaryRole",
      "baseName": "boundaryRole",
      // false
      // IdNameDescriptionObject
      // IdNameDescriptionObject
      "type": "IdNameDescriptionObject",
      "format": ""
    },
    {
      "name": "boundaryParty",
      "baseName": "boundaryParty",
      // false
      // AlertSubscriptionExtendedParty
      // AlertSubscriptionExtendedParty
      "type": "AlertSubscriptionExtendedParty",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return AlertSubscriptionExtendedAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): AlertSubscriptionExtendedAllOf {
    return ObjectSerializer.deserialize(obj, 'AlertSubscriptionExtendedAllOf');
  }

  constructor(role?: IdNameDescriptionObject, boundaryRole?: IdNameDescriptionObject, boundaryParty?: AlertSubscriptionExtendedParty) {
    this.role = role;
    this.boundaryRole = boundaryRole;
    this.boundaryParty = boundaryParty;
  }
}

