/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AlertSummaryBySeverity } from './AlertSummaryBySeverity.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class AlertSummary {
  'total'?: number;
  'bySeverity'?: Array<AlertSummaryBySeverity>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "total",
      "baseName": "total",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "bySeverity",
      "baseName": "bySeverity",
      // false
      // Array&lt;AlertSummaryBySeverity&gt;
      // Array&lt;AlertSummaryBySeverity&gt;
      "type": "Array<AlertSummaryBySeverity>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return AlertSummary.attributeTypeMap;
  }

  static newInstance(obj: any): AlertSummary {
    return ObjectSerializer.deserialize(obj, 'AlertSummary');
  }

  constructor(total?: number, bySeverity?: Array<AlertSummaryBySeverity>) {
    this.total = total;
    this.bySeverity = bySeverity;
  }
}

