/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AlertLinkExtendedAllOf } from './AlertLinkExtendedAllOf.js';
import { AlertLink } from './AlertLink.js';
import { Resource } from './Resource.js';
import { Alert } from './Alert.js';
import { Nmtoken, UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* An expanded view of an alert resource link with both Resource and Alert side expanded
*/
export class AlertLinkExtended {
  /**
  * Unique identifier for this link
  */
  'id': UUID;
  /**
  * The type of link. `impacts` and `caused_by` are provided by hydra
  */
  'type': Nmtoken;
  /**
  * The ID of the alert
  */
  'alertId': UUID;
  /**
  * The ID of the resource
  */
  'resourceId': UUID;
  'alert': Alert;
  'resource': Resource;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "alertId",
      "baseName": "alertId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "resourceId",
      "baseName": "resourceId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "alert",
      "baseName": "alert",
      // false
      // Alert
      // Alert
      "type": "Alert",
      "format": ""
    },
    {
      "name": "resource",
      "baseName": "resource",
      // false
      // Resource
      // Resource
      "type": "Resource",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return AlertLinkExtended.attributeTypeMap;
  }

  static newInstance(obj: any): AlertLinkExtended {
    return ObjectSerializer.deserialize(obj, 'AlertLinkExtended');
  }

  constructor(id: UUID, type: Nmtoken, alertId: UUID, resourceId: UUID, alert: Alert, resource: Resource, ) {
    this.id = id;
    this.type = type;
    this.alertId = alertId;
    this.resourceId = resourceId;
    this.alert = alert;
    this.resource = resource;
  }
}

