/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { DateFormat } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* App specific org monthly usage report
*/
export class AppOrgMonthlyUsageReportAllOf {
  /**
  * Date of the monthly usage metric collection
  */
  'month': DateFormat;
  /**
  * Name of the organization report
  */
  'organizationName': string;
  /**
  * Types of the organization
  */
  'organizationTypes': string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "month",
      "baseName": "month",
      // false
      // DateFormat
      // DateFormat
      "type": "DateFormat",
      "format": "date"
    },
    {
      "name": "organizationName",
      "baseName": "organizationName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "organizationTypes",
      "baseName": "organizationTypes",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return AppOrgMonthlyUsageReportAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): AppOrgMonthlyUsageReportAllOf {
    return ObjectSerializer.deserialize(obj, 'AppOrgMonthlyUsageReportAllOf');
  }

  constructor(month: DateFormat, organizationName: string, organizationTypes: string, ) {
    this.month = month;
    this.organizationName = organizationName;
    this.organizationTypes = organizationTypes;
  }
}

