/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AppOrgMonthlyUsageReportAllOf } from './AppOrgMonthlyUsageReportAllOf.js';
import { AppOrgUsageMetricBoundariesProductCollectingData } from './AppOrgUsageMetricBoundariesProductCollectingData.js';
import { AppOrgUsageMetric } from './AppOrgUsageMetric.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class AppOrgMonthlyUsageReport {
  /**
  * Connected products count for the organization
  */
  'connectedProductCount': number;
  /**
  * Objects count for the organization
  */
  'objectCount': number;
  /**
  * Object versions count for the organization
  */
  'objectVersionCount': number;
  /**
  * Active boundaries count for the organization
  */
  'activeBoundaryCount': number;
  'boundariesProductCollectingData': Array<AppOrgUsageMetricBoundariesProductCollectingData>;
  /**
  * Date of the monthly usage metric collection
  */
  'month': Date;
  /**
  * Name of the organization report
  */
  'organizationName': string;
  /**
  * Types of the organization
  */
  'organizationTypes': string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "connectedProductCount",
      "baseName": "connectedProductCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "objectCount",
      "baseName": "objectCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "objectVersionCount",
      "baseName": "objectVersionCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "activeBoundaryCount",
      "baseName": "activeBoundaryCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "boundariesProductCollectingData",
      "baseName": "boundariesProductCollectingData",
      // false
      // Array&lt;AppOrgUsageMetricBoundariesProductCollectingData&gt;
      // Array&lt;AppOrgUsageMetricBoundariesProductCollectingData&gt;
      "type": "Array<AppOrgUsageMetricBoundariesProductCollectingData>",
      "format": ""
    },
    {
      "name": "month",
      "baseName": "month",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date"
    },
    {
      "name": "organizationName",
      "baseName": "organizationName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "organizationTypes",
      "baseName": "organizationTypes",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return AppOrgMonthlyUsageReport.attributeTypeMap;
  }

  static newInstance(obj: any): AppOrgMonthlyUsageReport {
    return ObjectSerializer.deserialize(obj, 'AppOrgMonthlyUsageReport');
  }

  constructor(connectedProductCount: number, objectCount: number, objectVersionCount: number, activeBoundaryCount: number, boundariesProductCollectingData: Array<AppOrgUsageMetricBoundariesProductCollectingData>, month: Date, organizationName: string, organizationTypes: string, ) {
    this.connectedProductCount = connectedProductCount;
    this.objectCount = objectCount;
    this.objectVersionCount = objectVersionCount;
    this.activeBoundaryCount = activeBoundaryCount;
    this.boundariesProductCollectingData = boundariesProductCollectingData;
    this.month = month;
    this.organizationName = organizationName;
    this.organizationTypes = organizationTypes;
  }
}

