/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ArtifactStatusEnum } from './ArtifactStatusEnum.js';
import { ArtifactTypeEnum } from './ArtifactTypeEnum.js';
import { Resource } from './Resource.js';
import { ArtifactVersionAllOf } from './ArtifactVersionAllOf.js';
import { ArtifactStatusEnumDef } from './ArtifactStatusEnum.js';
import { ArtifactTypeEnumDef } from './ArtifactTypeEnum.js';
import { ArtifactVersionAllOfPackages } from './ArtifactVersionAllOfPackages.js';
import { Nmtoken, Semver, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class ArtifactVersion {
  /**
  * Unique identifier
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  'status': ArtifactStatusEnumDef;
  'artifactType': ArtifactTypeEnumDef;
  'isLatestVersion': boolean;
  'preRelease': boolean;
  'artifactName': string;
  'artifactId': UUID;
  'semver': Semver;
  'value': number;
  'floatValue': number;
  'packages': Array<ArtifactVersionAllOfPackages>;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  /**
  * An external URL to this resource in the outside world
  */
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  /**
  * A resource id which acts as a boundary/container for this resource.
  */
  'boundaryId'?: UUID;
  'readMe'?: string | null;
  'changeLog'?: string | null;
  'versionId'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // ArtifactStatusEnum
      // ArtifactStatusEnumDef
      "type": "ArtifactStatusEnum",
      "format": ""
    },
    {
      "name": "artifactType",
      "baseName": "artifactType",
      // false
      // ArtifactTypeEnum
      // ArtifactTypeEnumDef
      "type": "ArtifactTypeEnum",
      "format": ""
    },
    {
      "name": "isLatestVersion",
      "baseName": "isLatestVersion",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "preRelease",
      "baseName": "preRelease",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "artifactName",
      "baseName": "artifactName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "artifactId",
      "baseName": "artifactId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "semver",
      "baseName": "semver",
      // false
      // Semver
      // Semver
      "type": "Semver",
      "format": "semver"
    },
    {
      "name": "value",
      "baseName": "value",
      // false
      // number
      // number
      "type": "number",
      "format": "int64"
    },
    {
      "name": "floatValue",
      "baseName": "floatValue",
      // false
      // number
      // number
      "type": "number",
      "format": "float"
    },
    {
      "name": "packages",
      "baseName": "packages",
      // false
      // Array&lt;ArtifactVersionAllOfPackages&gt;
      // Array&lt;ArtifactVersionAllOfPackages&gt;
      "type": "Array<ArtifactVersionAllOfPackages>",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "readMe",
      "baseName": "readMe",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "changeLog",
      "baseName": "changeLog",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "versionId",
      "baseName": "versionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return ArtifactVersion.attributeTypeMap;
  }

  static newInstance(obj: any): ArtifactVersion {
    return ObjectSerializer.deserialize(obj, 'ArtifactVersion');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, status: ArtifactStatusEnumDef, artifactType: ArtifactTypeEnumDef, isLatestVersion: boolean, preRelease: boolean, artifactName: string, artifactId: UUID, semver: Semver, value: number, floatValue: number, packages: Array<ArtifactVersionAllOfPackages>, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, boundaryId?: UUID, readMe?: string, changeLog?: string, versionId?: UUID) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.status = status;
    this.artifactType = artifactType;
    this.isLatestVersion = isLatestVersion;
    this.preRelease = preRelease;
    this.artifactName = artifactName;
    this.artifactId = artifactId;
    this.semver = semver;
    this.value = value;
    this.floatValue = floatValue;
    this.packages = packages;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.boundaryId = boundaryId;
    this.readMe = readMe;
    this.changeLog = changeLog;
    this.versionId = versionId;
  }
}

