/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ArtifactStatusEnum } from './ArtifactStatusEnum.js';
import { ArtifactTypeEnum } from './ArtifactTypeEnum.js';
import { ArtifactStatusEnumDef } from './ArtifactStatusEnum.js';
import { ArtifactTypeEnumDef } from './ArtifactTypeEnum.js';
import { ArtifactVersionAllOfPackages } from './ArtifactVersionAllOfPackages.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Artifact data within the catalog schema
*/
export class ArtifactAllOf {
  'artifactType': ArtifactTypeEnumDef;
  'latestVersionId': UUID;
  'latestVersionSemver': string;
  'latestVersionValue': number;
  'latestVersionStatus': ArtifactStatusEnumDef;
  'latestVersionFloatValue': number;
  'isRetired': boolean;
  'preRelease': boolean;
  'versionIds': Array<UUID>;
  'versionSemvers': Array<string>;
  'versionValues': Array<number>;
  'versionFloatValues': Array<number>;
  'packages': Array<ArtifactVersionAllOfPackages>;
  'latestReleasedVersionSemver'?: string;
  'latestReleasedVersionValue'?: number;
  'latestReleasedVersionStatus'?: ArtifactStatusEnumDef;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "artifactType",
      "baseName": "artifactType",
      // false
      // ArtifactTypeEnum
      // ArtifactTypeEnumDef
      "type": "ArtifactTypeEnum",
      "format": ""
    },
    {
      "name": "latestVersionId",
      "baseName": "latestVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "latestVersionSemver",
      "baseName": "latestVersionSemver",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "latestVersionValue",
      "baseName": "latestVersionValue",
      // false
      // number
      // number
      "type": "number",
      "format": "int64"
    },
    {
      "name": "latestVersionStatus",
      "baseName": "latestVersionStatus",
      // false
      // ArtifactStatusEnum
      // ArtifactStatusEnumDef
      "type": "ArtifactStatusEnum",
      "format": ""
    },
    {
      "name": "latestVersionFloatValue",
      "baseName": "latestVersionFloatValue",
      // false
      // number
      // number
      "type": "number",
      "format": "float"
    },
    {
      "name": "isRetired",
      "baseName": "isRetired",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "preRelease",
      "baseName": "preRelease",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "versionIds",
      "baseName": "versionIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "versionSemvers",
      "baseName": "versionSemvers",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "versionValues",
      "baseName": "versionValues",
      // false
      // Array&lt;number&gt;
      // Array&lt;number&gt;
      "type": "Array<number>",
      "format": "int64"
    },
    {
      "name": "versionFloatValues",
      "baseName": "versionFloatValues",
      // false
      // Array&lt;number&gt;
      // Array&lt;number&gt;
      "type": "Array<number>",
      "format": "float"
    },
    {
      "name": "packages",
      "baseName": "packages",
      // false
      // Array&lt;ArtifactVersionAllOfPackages&gt;
      // Array&lt;ArtifactVersionAllOfPackages&gt;
      "type": "Array<ArtifactVersionAllOfPackages>",
      "format": ""
    },
    {
      "name": "latestReleasedVersionSemver",
      "baseName": "latestReleasedVersionSemver",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "latestReleasedVersionValue",
      "baseName": "latestReleasedVersionValue",
      // false
      // number
      // number
      "type": "number",
      "format": "int64"
    },
    {
      "name": "latestReleasedVersionStatus",
      "baseName": "latestReleasedVersionStatus",
      // false
      // ArtifactStatusEnum
      // ArtifactStatusEnumDef
      "type": "ArtifactStatusEnum",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return ArtifactAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): ArtifactAllOf {
    return ObjectSerializer.deserialize(obj, 'ArtifactAllOf');
  }

  constructor(artifactType: ArtifactTypeEnumDef, latestVersionId: UUID, latestVersionSemver: string, latestVersionValue: number, latestVersionStatus: ArtifactStatusEnumDef, latestVersionFloatValue: number, isRetired: boolean, preRelease: boolean, versionIds: Array<UUID>, versionSemvers: Array<string>, versionValues: Array<number>, versionFloatValues: Array<number>, packages: Array<ArtifactVersionAllOfPackages>, latestReleasedVersionSemver?: string, latestReleasedVersionValue?: number, latestReleasedVersionStatus?: ArtifactStatusEnumDef) {
    this.artifactType = artifactType;
    this.latestVersionId = latestVersionId;
    this.latestVersionSemver = latestVersionSemver;
    this.latestVersionValue = latestVersionValue;
    this.latestVersionStatus = latestVersionStatus;
    this.latestVersionFloatValue = latestVersionFloatValue;
    this.isRetired = isRetired;
    this.preRelease = preRelease;
    this.versionIds = versionIds;
    this.versionSemvers = versionSemvers;
    this.versionValues = versionValues;
    this.versionFloatValues = versionFloatValues;
    this.packages = packages;
    this.latestReleasedVersionSemver = latestReleasedVersionSemver;
    this.latestReleasedVersionValue = latestReleasedVersionValue;
    this.latestReleasedVersionStatus = latestReleasedVersionStatus;
  }
}

