/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const AssessmentResultRatingEnum = {
  /**  */
  Minor: EnumValue.instance('AssessmentResultRatingEnum', 'Minor', 'minor'),
  /**  */
  Intermediate: EnumValue.instance('AssessmentResultRatingEnum', 'Intermediate', 'intermediate'),
  /**  */
  Major: EnumValue.instance('AssessmentResultRatingEnum', 'Major', 'major'),

  from(val: string | number): EnumValue {
    if (AssessmentResultRatingEnum[val]) {
      return AssessmentResultRatingEnum[val];
    }
    const byValue = AssessmentResultRatingEnum.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid AssessmentResultRatingEnum`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(AssessmentResultRatingEnum)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => AssessmentResultRatingEnum[t]);
  }
} as const;

export type AssessmentResultRatingEnumDef = typeof AssessmentResultRatingEnum[keyof typeof AssessmentResultRatingEnum];
