/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Extended schema for audit
*/
export class AuditExtended {
  'auditorName': string;
  'boundaryName': string;
  'auditeePersonName': string;
  'frameworkVersionName'?: string;
  'evidenceRequestListName'?: string;
  /**
  * Count of assessment results with type equal finding
  */
  'findingCount'?: number;
  /**
  * Count of assessment results with type different of finding
  */
  'otherResultCount'?: number;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "auditorName",
      "baseName": "auditorName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "boundaryName",
      "baseName": "boundaryName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "auditeePersonName",
      "baseName": "auditeePersonName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "frameworkVersionName",
      "baseName": "frameworkVersionName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "evidenceRequestListName",
      "baseName": "evidenceRequestListName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "findingCount",
      "baseName": "findingCount",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "otherResultCount",
      "baseName": "otherResultCount",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return AuditExtended.attributeTypeMap;
  }

  static newInstance(obj: any): AuditExtended {
    return ObjectSerializer.deserialize(obj, 'AuditExtended');
  }

  constructor(auditorName: string, boundaryName: string, auditeePersonName: string, frameworkVersionName?: string, evidenceRequestListName?: string, findingCount?: number, otherResultCount?: number) {
    this.auditorName = auditorName;
    this.boundaryName = boundaryName;
    this.auditeePersonName = auditeePersonName;
    this.frameworkVersionName = frameworkVersionName;
    this.evidenceRequestListName = evidenceRequestListName;
    this.findingCount = findingCount;
    this.otherResultCount = otherResultCount;
  }
}

