/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Type of Audit
*/
export const AuditTypeEnum = {
  /**  */
  Internal: EnumValue.instance('AuditTypeEnum', 'Internal', 'internal'),
  /**  */
  External: EnumValue.instance('AuditTypeEnum', 'External', 'external'),
  /**  */
  Business: EnumValue.instance('AuditTypeEnum', 'Business', 'business'),

  from(val: string | number): EnumValue {
    if (AuditTypeEnum[val]) {
      return AuditTypeEnum[val];
    }
    const byValue = AuditTypeEnum.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid AuditTypeEnum`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(AuditTypeEnum)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => AuditTypeEnum[t]);
  }
} as const;

export type AuditTypeEnumDef = typeof AuditTypeEnum[keyof typeof AuditTypeEnum];
