/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Baseline schema
*/
export class BaselineAllOf {
  'code': string;
  'standardId': UUID;
  'externalId'?: string | null;
  'packageCode'?: string | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "standardId",
      "baseName": "standardId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "externalId",
      "baseName": "externalId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return BaselineAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): BaselineAllOf {
    return ObjectSerializer.deserialize(obj, 'BaselineAllOf');
  }

  constructor(code: string, standardId: UUID, externalId?: string, packageCode?: string) {
    this.code = code;
    this.standardId = standardId;
    this.externalId = externalId;
    this.packageCode = packageCode;
  }
}

