/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ObjectSerializer, RequestFile } from './index.js';

export class BatchChainOfCustodySchemaBatchTags {
  'name': string;
  'description': string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return BatchChainOfCustodySchemaBatchTags.attributeTypeMap;
  }

  static newInstance(obj: any): BatchChainOfCustodySchemaBatchTags {
    return ObjectSerializer.deserialize(obj, 'BatchChainOfCustodySchemaBatchTags');
  }

  constructor(name: string, description: string, ) {
    this.name = name;
    this.description = description;
  }
}

