/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for boundaryKeywordSearch filter
*/
export class BoundaryKeywordSearchFilter {
  'id': UUID;
  'name': string;
  'type': string;
  'ownerId': UUID;
  'kind': BoundaryKeywordSearchFilter.KindEnumDef;
  'description'?: string | null;
  'imageUrl'?: URL | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "kind",
      "baseName": "kind",
      // true
      // BoundaryKeywordSearchFilter.KindEnum
      // BoundaryKeywordSearchFilter.KindEnumDef
      "type": "BoundaryKeywordSearchFilter.KindEnum",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    }  ];

  static getAttributeTypeMap() {
    return BoundaryKeywordSearchFilter.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryKeywordSearchFilter {
    return ObjectSerializer.deserialize(obj, 'BoundaryKeywordSearchFilter');
  }

  constructor(id: UUID, name: string, type: string, ownerId: UUID, kind: BoundaryKeywordSearchFilter.KindEnumDef, description?: string, imageUrl?: URL) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.kind = kind;
    this.description = description;
    this.imageUrl = imageUrl;
  }
}

export namespace BoundaryKeywordSearchFilter {
  export const KindEnum = {
    /**  */
    Resource: EnumValue.instance('BoundaryKeywordSearchFilter.KindEnum', 'Resource', 'resource'),
    /**  */
    Tag: EnumValue.instance('BoundaryKeywordSearchFilter.KindEnum', 'Tag', 'tag'),

    from(val: string | number): EnumValue {
      if (KindEnum[val]) {
        return KindEnum[val];
      }
      const byValue = KindEnum.values.find((v) => v.value === val);
      if (byValue) {
        return byValue;
      }
      throw new IllegalArgumentError(`${val} is not a valid KindEnum`);
    },

    get values(): EnumValue[] {
      return Object
        .keys(KindEnum)
        .filter((k) => k !== 'values' && k !== 'from')
        .map((t) => KindEnum[t]);
    }
  } as const;

  export type KindEnumDef = typeof KindEnum[keyof typeof KindEnum];
}
