/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { BoundaryProductOverviewPipelineSummary } from './BoundaryProductOverviewPipelineSummary.js';
import { BoundaryProductOverviewScfControl } from './BoundaryProductOverviewScfControl.js';
import { HostingTypeEnum } from './HostingTypeEnum.js';
import { FactoryTypeEnum } from './FactoryTypeEnum.js';
import { NameDescriptionObject } from './NameDescriptionObject.js';
import { IdNameCodeDescriptionImageUrlVersionObject } from './IdNameCodeDescriptionImageUrlVersionObject.js';
import { HostingTypeEnumDef } from './HostingTypeEnum.js';
import { FactoryTypeEnumDef } from './FactoryTypeEnum.js';
import { UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Describes a boundary suggested product overview
*/
export class BoundarySuggestedProductOverview {
  'id': UUID;
  'productId': UUID;
  'productName': string;
  'pipelineSummary': BoundaryProductOverviewPipelineSummary;
  'productCreated': Date;
  'scfControls': Array<BoundaryProductOverviewScfControl>;
  'productDescription'?: string | null;
  'productImageUrl'?: URL | null;
  'productUrl'?: URL | null;
  'segmentIds'?: Array<UUID>;
  'segments'?: Array<IdNameCodeDescriptionImageUrlVersionObject>;
  'factoryTypes'?: Array<FactoryTypeEnumDef>;
  'factoryTypeObjects'?: Array<NameDescriptionObject>;
  'hostingTypes'?: Array<HostingTypeEnumDef>;
  'hostingTypeObjects'?: Array<NameDescriptionObject>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "productId",
      "baseName": "productId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "productName",
      "baseName": "productName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "pipelineSummary",
      "baseName": "pipelineSummary",
      // false
      // BoundaryProductOverviewPipelineSummary
      // BoundaryProductOverviewPipelineSummary
      "type": "BoundaryProductOverviewPipelineSummary",
      "format": ""
    },
    {
      "name": "productCreated",
      "baseName": "productCreated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "scfControls",
      "baseName": "scfControls",
      // false
      // Array&lt;BoundaryProductOverviewScfControl&gt;
      // Array&lt;BoundaryProductOverviewScfControl&gt;
      "type": "Array<BoundaryProductOverviewScfControl>",
      "format": ""
    },
    {
      "name": "productDescription",
      "baseName": "productDescription",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "productImageUrl",
      "baseName": "productImageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "productUrl",
      "baseName": "productUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "segmentIds",
      "baseName": "segmentIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "segments",
      "baseName": "segments",
      // false
      // Array&lt;IdNameCodeDescriptionImageUrlVersionObject&gt;
      // Array&lt;IdNameCodeDescriptionImageUrlVersionObject&gt;
      "type": "Array<IdNameCodeDescriptionImageUrlVersionObject>",
      "format": ""
    },
    {
      "name": "factoryTypes",
      "baseName": "factoryTypes",
      // false
      // Array&lt;FactoryTypeEnum&gt;
      // Array&lt;FactoryTypeEnumDef&gt;
      "type": "Array<FactoryTypeEnum>",
      "format": ""
    },
    {
      "name": "factoryTypeObjects",
      "baseName": "factoryTypeObjects",
      // false
      // Array&lt;NameDescriptionObject&gt;
      // Array&lt;NameDescriptionObject&gt;
      "type": "Array<NameDescriptionObject>",
      "format": ""
    },
    {
      "name": "hostingTypes",
      "baseName": "hostingTypes",
      // false
      // Array&lt;HostingTypeEnum&gt;
      // Array&lt;HostingTypeEnumDef&gt;
      "type": "Array<HostingTypeEnum>",
      "format": ""
    },
    {
      "name": "hostingTypeObjects",
      "baseName": "hostingTypeObjects",
      // false
      // Array&lt;NameDescriptionObject&gt;
      // Array&lt;NameDescriptionObject&gt;
      "type": "Array<NameDescriptionObject>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return BoundarySuggestedProductOverview.attributeTypeMap;
  }

  static newInstance(obj: any): BoundarySuggestedProductOverview {
    return ObjectSerializer.deserialize(obj, 'BoundarySuggestedProductOverview');
  }

  constructor(id: UUID, productId: UUID, productName: string, pipelineSummary: BoundaryProductOverviewPipelineSummary, productCreated: Date, scfControls: Array<BoundaryProductOverviewScfControl>, productDescription?: string, productImageUrl?: URL, productUrl?: URL, segmentIds?: Array<UUID>, segments?: Array<IdNameCodeDescriptionImageUrlVersionObject>, factoryTypes?: Array<FactoryTypeEnumDef>, factoryTypeObjects?: Array<NameDescriptionObject>, hostingTypes?: Array<HostingTypeEnumDef>, hostingTypeObjects?: Array<NameDescriptionObject>) {
    this.id = id;
    this.productId = productId;
    this.productName = productName;
    this.pipelineSummary = pipelineSummary;
    this.productCreated = productCreated;
    this.scfControls = scfControls;
    this.productDescription = productDescription;
    this.productImageUrl = productImageUrl;
    this.productUrl = productUrl;
    this.segmentIds = segmentIds;
    this.segments = segments;
    this.factoryTypes = factoryTypes;
    this.factoryTypeObjects = factoryTypeObjects;
    this.hostingTypes = hostingTypes;
    this.hostingTypeObjects = hostingTypeObjects;
  }
}

