/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { BoundaryTypeEnum } from './BoundaryTypeEnum.js';
import { HostingTypeEnum } from './HostingTypeEnum.js';
import { BoundaryStatusEnumDef } from './BoundaryStatusEnum.js';
import { BoundaryStatusEnum } from './BoundaryStatusEnum.js';
import { FactoryTypeEnum } from './FactoryTypeEnum.js';
import { BoundaryTypeEnumDef } from './BoundaryTypeEnum.js';
import { HostingTypeEnumDef } from './HostingTypeEnum.js';
import { FactoryTypeEnumDef } from './FactoryTypeEnum.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* A boundary
*/
export class BoundaryAllOf {
  'status': BoundaryStatusEnumDef;
  'boundaryType': BoundaryTypeEnumDef;
  'tagId': UUID;
  'createdBy': UUID;
  'factoryTypes': Array<FactoryTypeEnumDef>;
  'hostingTypes': Array<HostingTypeEnumDef>;
  'managedTypes': Array<string>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "status",
      "baseName": "status",
      // false
      // BoundaryStatusEnum
      // BoundaryStatusEnumDef
      "type": "BoundaryStatusEnum",
      "format": ""
    },
    {
      "name": "boundaryType",
      "baseName": "boundaryType",
      // false
      // BoundaryTypeEnum
      // BoundaryTypeEnumDef
      "type": "BoundaryTypeEnum",
      "format": ""
    },
    {
      "name": "tagId",
      "baseName": "tagId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "createdBy",
      "baseName": "createdBy",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "factoryTypes",
      "baseName": "factoryTypes",
      // false
      // Array&lt;FactoryTypeEnum&gt;
      // Array&lt;FactoryTypeEnumDef&gt;
      "type": "Array<FactoryTypeEnum>",
      "format": ""
    },
    {
      "name": "hostingTypes",
      "baseName": "hostingTypes",
      // false
      // Array&lt;HostingTypeEnum&gt;
      // Array&lt;HostingTypeEnumDef&gt;
      "type": "Array<HostingTypeEnum>",
      "format": ""
    },
    {
      "name": "managedTypes",
      "baseName": "managedTypes",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return BoundaryAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryAllOf {
    return ObjectSerializer.deserialize(obj, 'BoundaryAllOf');
  }

  constructor(status: BoundaryStatusEnumDef, boundaryType: BoundaryTypeEnumDef, tagId: UUID, createdBy: UUID, factoryTypes: Array<FactoryTypeEnumDef>, hostingTypes: Array<HostingTypeEnumDef>, managedTypes: Array<string>, ) {
    this.status = status;
    this.boundaryType = boundaryType;
    this.tagId = tagId;
    this.createdBy = createdBy;
    this.factoryTypes = factoryTypes;
    this.hostingTypes = hostingTypes;
    this.managedTypes = managedTypes;
  }
}

