/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for boundary keyword search body
*/
export class BoundaryKeywordSearchBody {
  'keyword': string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "keyword",
      "baseName": "keyword",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return BoundaryKeywordSearchBody.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryKeywordSearchBody {
    return ObjectSerializer.deserialize(obj, 'BoundaryKeywordSearchBody');
  }

  constructor(keyword: string, ) {
    this.keyword = keyword;
  }
}

