/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Summary of a domain maturity counts and team/policy info
*/
export class BoundaryDomainSummaryDomain {
  'internalDomainId': UUID;
  'code': string;
  'name': string;
  'policyObjectCount': number;
  'totalCount': number;
  'notPerformedCount': number;
  'performedInternallyCount': number;
  'plannedAndTrackedCount': number;
  'wellDefinedCount': number;
  'quantitativelyControlledCount': number;
  'continuouslyImprovingCount': number;
  'designPrinciple'?: string | null;
  'intent'?: string | null;
  'boundaryTeamId'?: UUID | null;
  'teamId'?: UUID | null;
  'teamName'?: string | null;
  'policyEvidenceDefinitionId'?: UUID | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "internalDomainId",
      "baseName": "internalDomainId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "policyObjectCount",
      "baseName": "policyObjectCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "totalCount",
      "baseName": "totalCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "notPerformedCount",
      "baseName": "notPerformedCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "performedInternallyCount",
      "baseName": "performedInternallyCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "plannedAndTrackedCount",
      "baseName": "plannedAndTrackedCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "wellDefinedCount",
      "baseName": "wellDefinedCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "quantitativelyControlledCount",
      "baseName": "quantitativelyControlledCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "continuouslyImprovingCount",
      "baseName": "continuouslyImprovingCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "designPrinciple",
      "baseName": "designPrinciple",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "intent",
      "baseName": "intent",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "boundaryTeamId",
      "baseName": "boundaryTeamId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "teamId",
      "baseName": "teamId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "teamName",
      "baseName": "teamName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "policyEvidenceDefinitionId",
      "baseName": "policyEvidenceDefinitionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return BoundaryDomainSummaryDomain.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryDomainSummaryDomain {
    return ObjectSerializer.deserialize(obj, 'BoundaryDomainSummaryDomain');
  }

  constructor(internalDomainId: UUID, code: string, name: string, policyObjectCount: number, totalCount: number, notPerformedCount: number, performedInternallyCount: number, plannedAndTrackedCount: number, wellDefinedCount: number, quantitativelyControlledCount: number, continuouslyImprovingCount: number, designPrinciple?: string, intent?: string, boundaryTeamId?: UUID, teamId?: UUID, teamName?: string, policyEvidenceDefinitionId?: UUID) {
    this.internalDomainId = internalDomainId;
    this.code = code;
    this.name = name;
    this.policyObjectCount = policyObjectCount;
    this.totalCount = totalCount;
    this.notPerformedCount = notPerformedCount;
    this.performedInternallyCount = performedInternallyCount;
    this.plannedAndTrackedCount = plannedAndTrackedCount;
    this.wellDefinedCount = wellDefinedCount;
    this.quantitativelyControlledCount = quantitativelyControlledCount;
    this.continuouslyImprovingCount = continuouslyImprovingCount;
    this.designPrinciple = designPrinciple;
    this.intent = intent;
    this.boundaryTeamId = boundaryTeamId;
    this.teamId = teamId;
    this.teamName = teamName;
    this.policyEvidenceDefinitionId = policyEvidenceDefinitionId;
  }
}

