/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CatalogPublishStatusEnumDef } from './CatalogPublishStatusEnum.js';
import { BoundaryFrameworkControlProductPipeline } from './BoundaryFrameworkControlProductPipeline.js';
import { CatalogPublishStatusEnum } from './CatalogPublishStatusEnum.js';
import { UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Product details for a boundary framework control
*/
export class BoundaryFrameworkControlProduct {
  'id': UUID;
  'name': string;
  'description': string | null;
  'code': string;
  'packageCode': string;
  'status': CatalogPublishStatusEnumDef;
  'producing': boolean;
  'implementing': boolean;
  'pipelines': Array<BoundaryFrameworkControlProductPipeline>;
  'imageUrl'?: URL | null;
  'url'?: URL | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // CatalogPublishStatusEnum
      // CatalogPublishStatusEnumDef
      "type": "CatalogPublishStatusEnum",
      "format": ""
    },
    {
      "name": "producing",
      "baseName": "producing",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "implementing",
      "baseName": "implementing",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "pipelines",
      "baseName": "pipelines",
      // false
      // Array&lt;BoundaryFrameworkControlProductPipeline&gt;
      // Array&lt;BoundaryFrameworkControlProductPipeline&gt;
      "type": "Array<BoundaryFrameworkControlProductPipeline>",
      "format": ""
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    }  ];

  static getAttributeTypeMap() {
    return BoundaryFrameworkControlProduct.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryFrameworkControlProduct {
    return ObjectSerializer.deserialize(obj, 'BoundaryFrameworkControlProduct');
  }

  constructor(id: UUID, name: string, description: string, code: string, packageCode: string, status: CatalogPublishStatusEnumDef, producing: boolean, implementing: boolean, pipelines: Array<BoundaryFrameworkControlProductPipeline>, imageUrl?: URL, url?: URL) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.code = code;
    this.packageCode = packageCode;
    this.status = status;
    this.producing = producing;
    this.implementing = implementing;
    this.pipelines = pipelines;
    this.imageUrl = imageUrl;
    this.url = url;
  }
}

