/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { IdNameImageUrlObject } from './IdNameImageUrlObject.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Info about a boundary teams scf control evidence definition implemenation row
*/
export class BoundaryTeamScfControlEvidenceDefinitionImplementationRow {
  'id': UUID;
  'producingProduct': IdNameImageUrlObject;
  'coveredProduct'?: IdNameImageUrlObject;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "producingProduct",
      "baseName": "producingProduct",
      // false
      // IdNameImageUrlObject
      // IdNameImageUrlObject
      "type": "IdNameImageUrlObject",
      "format": ""
    },
    {
      "name": "coveredProduct",
      "baseName": "coveredProduct",
      // false
      // IdNameImageUrlObject
      // IdNameImageUrlObject
      "type": "IdNameImageUrlObject",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return BoundaryTeamScfControlEvidenceDefinitionImplementationRow.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryTeamScfControlEvidenceDefinitionImplementationRow {
    return ObjectSerializer.deserialize(obj, 'BoundaryTeamScfControlEvidenceDefinitionImplementationRow');
  }

  constructor(id: UUID, producingProduct: IdNameImageUrlObject, coveredProduct?: IdNameImageUrlObject) {
    this.id = id;
    this.producingProduct = producingProduct;
    this.coveredProduct = coveredProduct;
  }
}

