/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { BoundaryAlertOrigin } from './BoundaryAlertOrigin.js';
import { Resource } from './Resource.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Model usually returned by API listers, may contain minor extended information
*/
export class BoundaryAlertViewAllOf {
  /**
  * A flat list of Resources that are causing this alert.
  */
  'causedBy': Array<Resource>;
  'origin': BoundaryAlertOrigin;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "causedBy",
      "baseName": "causedBy",
      // false
      // Array&lt;Resource&gt;
      // Array&lt;Resource&gt;
      "type": "Array<Resource>",
      "format": ""
    },
    {
      "name": "origin",
      "baseName": "origin",
      // false
      // BoundaryAlertOrigin
      // BoundaryAlertOrigin
      "type": "BoundaryAlertOrigin",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return BoundaryAlertViewAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryAlertViewAllOf {
    return ObjectSerializer.deserialize(obj, 'BoundaryAlertViewAllOf');
  }

  constructor(causedBy: Array<Resource>, origin: BoundaryAlertOrigin, ) {
    this.causedBy = causedBy;
    this.origin = origin;
  }
}

