/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Enum on the status of a scf control within a boundary team
*/
export const BoundaryTeamScfControlStatus = {
  /**  */
  NotAnswered: EnumValue.instance('BoundaryTeamScfControlStatus', 'NotAnswered', 'not_answered'),
  /**  */
  Performed: EnumValue.instance('BoundaryTeamScfControlStatus', 'Performed', 'performed'),
  /**  */
  NotPerformed: EnumValue.instance('BoundaryTeamScfControlStatus', 'NotPerformed', 'not_performed'),

  from(val: string | number): EnumValue {
    if (BoundaryTeamScfControlStatus[val]) {
      return BoundaryTeamScfControlStatus[val];
    }
    const byValue = BoundaryTeamScfControlStatus.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid BoundaryTeamScfControlStatus`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(BoundaryTeamScfControlStatus)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => BoundaryTeamScfControlStatus[t]);
  }
} as const;

export type BoundaryTeamScfControlStatusDef = typeof BoundaryTeamScfControlStatus[keyof typeof BoundaryTeamScfControlStatus];
