/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { SeverityDef } from './Severity.js';
import { Alert } from './Alert.js';
import { BoundaryAlertAllOf } from './BoundaryAlertAllOf.js';
import { Severity } from './Severity.js';
import { BoundaryAlertSubject } from './BoundaryAlertSubject.js';
import { Nmtoken, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class BoundaryAlert {
  /**
  * Unique identifier
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  'boundaryId': UUID;
  /**
  * A reference to the trigger this alert was generated from
  */
  'triggerId': UUID;
  /**
  * Resource ids that are impacted by this alert. Only returns top level when used outside of /impacts
  */
  'impacts': Array<UUID>;
  /**
  * A flat list of Resource ids that are causing this alert.
  */
  'causedBy': Array<UUID>;
  'severity': SeverityDef;
  /**
  * The alert type
  */
  'alertType': Nmtoken;
  /**
  * The alert body
  */
  'body': { [key: string]: any; };
  /**
  * The service this alert originiated from.
  */
  'service': string;
  'groupId': string;
  'elementId': string;
  'subjects': Array<BoundaryAlertSubject>;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  /**
  * An external URL to this resource in the outside world
  */
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  /**
  * The alert title
  */
  'title'?: string;
  /**
  * Instructions on how to remediate this alert
  */
  'remediation'?: string | null;
  'alertId'?: UUID;
  'extendsAlert'?: Alert;
  'graphqlQueryId'?: UUID;
  'graphqlQueryVersionId'?: UUID;
  'boundaryAlertBotId'?: UUID | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "triggerId",
      "baseName": "triggerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "impacts",
      "baseName": "impacts",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "causedBy",
      "baseName": "causedBy",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "severity",
      "baseName": "severity",
      // false
      // Severity
      // SeverityDef
      "type": "Severity",
      "format": ""
    },
    {
      "name": "alertType",
      "baseName": "alertType",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "body",
      "baseName": "body",
      // false
      // { [key: string]: any; }
      // { [key: string]: any; }
      "type": "{ [key: string]: any; }",
      "format": ""
    },
    {
      "name": "service",
      "baseName": "service",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "groupId",
      "baseName": "groupId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "elementId",
      "baseName": "elementId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "subjects",
      "baseName": "subjects",
      // false
      // Array&lt;BoundaryAlertSubject&gt;
      // Array&lt;BoundaryAlertSubject&gt;
      "type": "Array<BoundaryAlertSubject>",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "title",
      "baseName": "title",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "remediation",
      "baseName": "remediation",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "alertId",
      "baseName": "alertId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "extendsAlert",
      "baseName": "extendsAlert",
      // false
      // Alert
      // Alert
      "type": "Alert",
      "format": ""
    },
    {
      "name": "graphqlQueryId",
      "baseName": "graphqlQueryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "graphqlQueryVersionId",
      "baseName": "graphqlQueryVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "boundaryAlertBotId",
      "baseName": "boundaryAlertBotId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return BoundaryAlert.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryAlert {
    return ObjectSerializer.deserialize(obj, 'BoundaryAlert');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, boundaryId: UUID, triggerId: UUID, impacts: Array<UUID>, causedBy: Array<UUID>, severity: SeverityDef, alertType: Nmtoken, body: { [key: string]: any; }, service: string, groupId: string, elementId: string, subjects: Array<BoundaryAlertSubject>, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, title?: string, remediation?: string, alertId?: UUID, extendsAlert?: Alert, graphqlQueryId?: UUID, graphqlQueryVersionId?: UUID, boundaryAlertBotId?: UUID) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.boundaryId = boundaryId;
    this.triggerId = triggerId;
    this.impacts = impacts;
    this.causedBy = causedBy;
    this.severity = severity;
    this.alertType = alertType;
    this.body = body;
    this.service = service;
    this.groupId = groupId;
    this.elementId = elementId;
    this.subjects = subjects;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.title = title;
    this.remediation = remediation;
    this.alertId = alertId;
    this.extendsAlert = extendsAlert;
    this.graphqlQueryId = graphqlQueryId;
    this.graphqlQueryVersionId = graphqlQueryVersionId;
    this.boundaryAlertBotId = boundaryAlertBotId;
  }
}

