/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { BoundaryDomainSummaryDomain } from './BoundaryDomainSummaryDomain.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Summary of a boundary domains and rollup
*/
export class BoundaryDomainSummary {
  'totalCount': number;
  'notPerformedCount': number;
  'performedInternallyCount': number;
  'plannedAndTrackedCount': number;
  'wellDefinedCount': number;
  'quantitativelyControlledCount': number;
  'continuouslyImprovingCount': number;
  'domains': Array<BoundaryDomainSummaryDomain>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "totalCount",
      "baseName": "totalCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "notPerformedCount",
      "baseName": "notPerformedCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "performedInternallyCount",
      "baseName": "performedInternallyCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "plannedAndTrackedCount",
      "baseName": "plannedAndTrackedCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "wellDefinedCount",
      "baseName": "wellDefinedCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "quantitativelyControlledCount",
      "baseName": "quantitativelyControlledCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "continuouslyImprovingCount",
      "baseName": "continuouslyImprovingCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "domains",
      "baseName": "domains",
      // false
      // Array&lt;BoundaryDomainSummaryDomain&gt;
      // Array&lt;BoundaryDomainSummaryDomain&gt;
      "type": "Array<BoundaryDomainSummaryDomain>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return BoundaryDomainSummary.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryDomainSummary {
    return ObjectSerializer.deserialize(obj, 'BoundaryDomainSummary');
  }

  constructor(totalCount: number, notPerformedCount: number, performedInternallyCount: number, plannedAndTrackedCount: number, wellDefinedCount: number, quantitativelyControlledCount: number, continuouslyImprovingCount: number, domains: Array<BoundaryDomainSummaryDomain>, ) {
    this.totalCount = totalCount;
    this.notPerformedCount = notPerformedCount;
    this.performedInternallyCount = performedInternallyCount;
    this.plannedAndTrackedCount = plannedAndTrackedCount;
    this.wellDefinedCount = wellDefinedCount;
    this.quantitativelyControlledCount = quantitativelyControlledCount;
    this.continuouslyImprovingCount = continuouslyImprovingCount;
    this.domains = domains;
  }
}

