/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { PartyTypeEnumDef } from './PartyTypeEnum.js';
import { PartyTypeEnum } from './PartyTypeEnum.js';
import { EnumValue, IllegalArgumentError, UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Boundary Component Extended Party Schema
*/
export class BoundaryComponentExtendedParty {
  'id': UUID;
  'name': string;
  'ownerId': UUID;
  'partyType': PartyTypeEnumDef;
  'description'?: string | null;
  'principalId'?: UUID;
  'teamId'?: UUID;
  'externalId'?: UUID;
  'linkType'?: BoundaryComponentExtendedParty.LinkTypeEnumDef;
  'linkId'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "partyType",
      "baseName": "partyType",
      // false
      // PartyTypeEnum
      // PartyTypeEnumDef
      "type": "PartyTypeEnum",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "principalId",
      "baseName": "principalId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "teamId",
      "baseName": "teamId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "externalId",
      "baseName": "externalId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "linkType",
      "baseName": "linkType",
      // true
      // BoundaryComponentExtendedParty.LinkTypeEnum
      // BoundaryComponentExtendedParty.LinkTypeEnumDef
      "type": "BoundaryComponentExtendedParty.LinkTypeEnum",
      "format": ""
    },
    {
      "name": "linkId",
      "baseName": "linkId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return BoundaryComponentExtendedParty.attributeTypeMap;
  }

  static newInstance(obj: any): BoundaryComponentExtendedParty {
    return ObjectSerializer.deserialize(obj, 'BoundaryComponentExtendedParty');
  }

  constructor(id: UUID, name: string, ownerId: UUID, partyType: PartyTypeEnumDef, description?: string, principalId?: UUID, teamId?: UUID, externalId?: UUID, linkType?: BoundaryComponentExtendedParty.LinkTypeEnumDef, linkId?: UUID) {
    this.id = id;
    this.name = name;
    this.ownerId = ownerId;
    this.partyType = partyType;
    this.description = description;
    this.principalId = principalId;
    this.teamId = teamId;
    this.externalId = externalId;
    this.linkType = linkType;
    this.linkId = linkId;
  }
}

export namespace BoundaryComponentExtendedParty {
  export const LinkTypeEnum = {
    /**  */
    Role: EnumValue.instance('BoundaryComponentExtendedParty.LinkTypeEnum', 'Role', 'role'),
    /**  */
    ImplementationStatement: EnumValue.instance('BoundaryComponentExtendedParty.LinkTypeEnum', 'ImplementationStatement', 'implementation_statement'),
    /**  */
    Direct: EnumValue.instance('BoundaryComponentExtendedParty.LinkTypeEnum', 'Direct', 'direct'),

    from(val: string | number): EnumValue {
      if (LinkTypeEnum[val]) {
        return LinkTypeEnum[val];
      }
      const byValue = LinkTypeEnum.values.find((v) => v.value === val);
      if (byValue) {
        return byValue;
      }
      throw new IllegalArgumentError(`${val} is not a valid LinkTypeEnum`);
    },

    get values(): EnumValue[] {
      return Object
        .keys(LinkTypeEnum)
        .filter((k) => k !== 'values' && k !== 'from')
        .map((t) => LinkTypeEnum[t]);
    }
  } as const;

  export type LinkTypeEnumDef = typeof LinkTypeEnum[keyof typeof LinkTypeEnum];
}
