/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const BoundaryProductPipelineSortColumns = {
  /**  */
  Name: EnumValue.instance('BoundaryProductPipelineSortColumns', 'Name', 'name'),
  /**  */
  Frequency: EnumValue.instance('BoundaryProductPipelineSortColumns', 'Frequency', 'frequency'),
  /**  */
  Format: EnumValue.instance('BoundaryProductPipelineSortColumns', 'Format', 'format'),
  /**  */
  LastPipelineJobRunTime: EnumValue.instance('BoundaryProductPipelineSortColumns', 'LastPipelineJobRunTime', 'lastPipelineJobRunTime'),
  /**  */
  LastPipelineJobRunStatus: EnumValue.instance('BoundaryProductPipelineSortColumns', 'LastPipelineJobRunStatus', 'lastPipelineJobRunStatus'),

  from(val: string | number): EnumValue {
    if (BoundaryProductPipelineSortColumns[val]) {
      return BoundaryProductPipelineSortColumns[val];
    }
    const byValue = BoundaryProductPipelineSortColumns.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid BoundaryProductPipelineSortColumns`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(BoundaryProductPipelineSortColumns)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => BoundaryProductPipelineSortColumns[t]);
  }
} as const;

export type BoundaryProductPipelineSortColumnsDef = typeof BoundaryProductPipelineSortColumns[keyof typeof BoundaryProductPipelineSortColumns];
