/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class ClassGraphLinks {
  'id': UUID;
  'fromId': UUID;
  'toId': UUID;
  'fromIcon': string | null;
  'toIcon': string;
  'fromPropertyName'?: string;
  'toPropertyName'?: string;
  't3Name'?: string;
  't3Id'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "fromId",
      "baseName": "fromId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "toId",
      "baseName": "toId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "fromIcon",
      "baseName": "fromIcon",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "toIcon",
      "baseName": "toIcon",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "fromPropertyName",
      "baseName": "fromPropertyName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "toPropertyName",
      "baseName": "toPropertyName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "t3Name",
      "baseName": "t3Name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "t3Id",
      "baseName": "t3Id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return ClassGraphLinks.attributeTypeMap;
  }

  static newInstance(obj: any): ClassGraphLinks {
    return ObjectSerializer.deserialize(obj, 'ClassGraphLinks');
  }

  constructor(id: UUID, fromId: UUID, toId: UUID, fromIcon: string, toIcon: string, fromPropertyName?: string, toPropertyName?: string, t3Name?: string, t3Id?: UUID) {
    this.id = id;
    this.fromId = fromId;
    this.toId = toId;
    this.fromIcon = fromIcon;
    this.toIcon = toIcon;
    this.fromPropertyName = fromPropertyName;
    this.toPropertyName = toPropertyName;
    this.t3Name = t3Name;
    this.t3Id = t3Id;
  }
}

