/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { PipelineBatchModeEnumDef } from './PipelineBatchModeEnum.js';
import { PipelineBatchModeEnum } from './PipelineBatchModeEnum.js';
import { Semver, UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Collector bot schema
*/
export class CollectorBotAllOf {
  'version': Semver;
  'batchModes': Array<PipelineBatchModeEnumDef>;
  'changeLog'?: string | null;
  'readMe'?: string | null;
  'remediation'?: string | null;
  'userGuide'?: string | null;
  'versionId'?: UUID;
  'versionValue'?: number;
  'versionFloatValue'?: number;
  'preRelease'?: boolean;
  'packageCode'?: string | null;
  'parameters'?: { [key: string]: any; };
  'modulesInfo'?: Array<{ [key: string]: any; }>;
  'products'?: Array<UUID>;
  'classes'?: Array<UUID>;
  'artifactVersionId'?: UUID | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "version",
      "baseName": "version",
      // false
      // Semver
      // Semver
      "type": "Semver",
      "format": "semver"
    },
    {
      "name": "batchModes",
      "baseName": "batchModes",
      // false
      // Array&lt;PipelineBatchModeEnum&gt;
      // Array&lt;PipelineBatchModeEnumDef&gt;
      "type": "Array<PipelineBatchModeEnum>",
      "format": ""
    },
    {
      "name": "changeLog",
      "baseName": "changeLog",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "readMe",
      "baseName": "readMe",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "remediation",
      "baseName": "remediation",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "userGuide",
      "baseName": "userGuide",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "versionId",
      "baseName": "versionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "versionValue",
      "baseName": "versionValue",
      // false
      // number
      // number
      "type": "number",
      "format": "int64"
    },
    {
      "name": "versionFloatValue",
      "baseName": "versionFloatValue",
      // false
      // number
      // number
      "type": "number",
      "format": "float"
    },
    {
      "name": "preRelease",
      "baseName": "preRelease",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parameters",
      "baseName": "parameters",
      // false
      // { [key: string]: any; }
      // { [key: string]: any; }
      "type": "{ [key: string]: any; }",
      "format": ""
    },
    {
      "name": "modulesInfo",
      "baseName": "modulesInfo",
      // false
      // Array&lt;{ [key: string]: any; }&gt;
      // Array&lt;{ [key: string]: any; }&gt;
      "type": "Array<{ [key: string]: any; }>",
      "format": ""
    },
    {
      "name": "products",
      "baseName": "products",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "classes",
      "baseName": "classes",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "artifactVersionId",
      "baseName": "artifactVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return CollectorBotAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): CollectorBotAllOf {
    return ObjectSerializer.deserialize(obj, 'CollectorBotAllOf');
  }

  constructor(version: Semver, batchModes: Array<PipelineBatchModeEnumDef>, changeLog?: string, readMe?: string, remediation?: string, userGuide?: string, versionId?: UUID, versionValue?: number, versionFloatValue?: number, preRelease?: boolean, packageCode?: string, parameters?: { [key: string]: any; }, modulesInfo?: Array<{ [key: string]: any; }>, products?: Array<UUID>, classes?: Array<UUID>, artifactVersionId?: UUID) {
    this.version = version;
    this.batchModes = batchModes;
    this.changeLog = changeLog;
    this.readMe = readMe;
    this.remediation = remediation;
    this.userGuide = userGuide;
    this.versionId = versionId;
    this.versionValue = versionValue;
    this.versionFloatValue = versionFloatValue;
    this.preRelease = preRelease;
    this.packageCode = packageCode;
    this.parameters = parameters;
    this.modulesInfo = modulesInfo;
    this.products = products;
    this.classes = classes;
    this.artifactVersionId = artifactVersionId;
  }
}

