/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CatalogPublishStatusEnumDef } from './CatalogPublishStatusEnum.js';
import { IdNameCodeDescriptionImageUrlObject } from './IdNameCodeDescriptionImageUrlObject.js';
import { CrosswalkVersionExtendedAllOf } from './CrosswalkVersionExtendedAllOf.js';
import { CrosswalkStandard } from './CrosswalkStandard.js';
import { CatalogPublishStatusEnum } from './CatalogPublishStatusEnum.js';
import { CrosswalkVersion } from './CrosswalkVersion.js';
import { Nmtoken, Semver, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class CrosswalkVersionExtended {
  /**
  * Unique identifier
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  'status': CatalogPublishStatusEnumDef;
  'versionId': UUID;
  'versionValue': number;
  'versionSemver': Semver;
  'crosswalkId': UUID;
  'sourceStandardId': UUID;
  'targetStandardId': UUID;
  'sourceStandard': CrosswalkStandard;
  'targetStandard': CrosswalkStandard;
  'crosswalkCode': string;
  'crosswalkExternalId': string;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  /**
  * An external URL to this resource in the outside world
  */
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  /**
  * A resource id which acts as a boundary/container for this resource.
  */
  'boundaryId'?: UUID;
  'packageCode'?: string;
  'logoFileVersionId'?: UUID;
  /**
  * Task created for this crosswalk version
  */
  'taskId'?: UUID | null;
  'vendor'?: IdNameCodeDescriptionImageUrlObject;
  'suite'?: IdNameCodeDescriptionImageUrlObject;
  'product'?: IdNameCodeDescriptionImageUrlObject;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // CatalogPublishStatusEnum
      // CatalogPublishStatusEnumDef
      "type": "CatalogPublishStatusEnum",
      "format": ""
    },
    {
      "name": "versionId",
      "baseName": "versionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "versionValue",
      "baseName": "versionValue",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "versionSemver",
      "baseName": "versionSemver",
      // false
      // Semver
      // Semver
      "type": "Semver",
      "format": "semver"
    },
    {
      "name": "crosswalkId",
      "baseName": "crosswalkId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "sourceStandardId",
      "baseName": "sourceStandardId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "targetStandardId",
      "baseName": "targetStandardId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "sourceStandard",
      "baseName": "sourceStandard",
      // false
      // CrosswalkStandard
      // CrosswalkStandard
      "type": "CrosswalkStandard",
      "format": ""
    },
    {
      "name": "targetStandard",
      "baseName": "targetStandard",
      // false
      // CrosswalkStandard
      // CrosswalkStandard
      "type": "CrosswalkStandard",
      "format": ""
    },
    {
      "name": "crosswalkCode",
      "baseName": "crosswalkCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "crosswalkExternalId",
      "baseName": "crosswalkExternalId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "logoFileVersionId",
      "baseName": "logoFileVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "taskId",
      "baseName": "taskId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "vendor",
      "baseName": "vendor",
      // false
      // IdNameCodeDescriptionImageUrlObject
      // IdNameCodeDescriptionImageUrlObject
      "type": "IdNameCodeDescriptionImageUrlObject",
      "format": ""
    },
    {
      "name": "suite",
      "baseName": "suite",
      // false
      // IdNameCodeDescriptionImageUrlObject
      // IdNameCodeDescriptionImageUrlObject
      "type": "IdNameCodeDescriptionImageUrlObject",
      "format": ""
    },
    {
      "name": "product",
      "baseName": "product",
      // false
      // IdNameCodeDescriptionImageUrlObject
      // IdNameCodeDescriptionImageUrlObject
      "type": "IdNameCodeDescriptionImageUrlObject",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return CrosswalkVersionExtended.attributeTypeMap;
  }

  static newInstance(obj: any): CrosswalkVersionExtended {
    return ObjectSerializer.deserialize(obj, 'CrosswalkVersionExtended');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, status: CatalogPublishStatusEnumDef, versionId: UUID, versionValue: number, versionSemver: Semver, crosswalkId: UUID, sourceStandardId: UUID, targetStandardId: UUID, sourceStandard: CrosswalkStandard, targetStandard: CrosswalkStandard, crosswalkCode: string, crosswalkExternalId: string, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, boundaryId?: UUID, packageCode?: string, logoFileVersionId?: UUID, taskId?: UUID, vendor?: IdNameCodeDescriptionImageUrlObject, suite?: IdNameCodeDescriptionImageUrlObject, product?: IdNameCodeDescriptionImageUrlObject) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.status = status;
    this.versionId = versionId;
    this.versionValue = versionValue;
    this.versionSemver = versionSemver;
    this.crosswalkId = crosswalkId;
    this.sourceStandardId = sourceStandardId;
    this.targetStandardId = targetStandardId;
    this.sourceStandard = sourceStandard;
    this.targetStandard = targetStandard;
    this.crosswalkCode = crosswalkCode;
    this.crosswalkExternalId = crosswalkExternalId;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.boundaryId = boundaryId;
    this.packageCode = packageCode;
    this.logoFileVersionId = logoFileVersionId;
    this.taskId = taskId;
    this.vendor = vendor;
    this.suite = suite;
    this.product = product;
  }
}

