/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CrosswalkElementRelationshipTypeDef } from './CrosswalkElementRelationshipType.js';
import { CrosswalkElementRelationshipType } from './CrosswalkElementRelationshipType.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class CrosswalkElement {
  'id': UUID;
  'crosswalkId': UUID;
  'sourceStandardId': UUID;
  'sourceStandardElementId': UUID;
  'targetStandardId': UUID;
  'targetStandardElementId': UUID;
  'relationshipType': CrosswalkElementRelationshipTypeDef;
  'strengthOfRelationship'?: number;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "crosswalkId",
      "baseName": "crosswalkId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "sourceStandardId",
      "baseName": "sourceStandardId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "sourceStandardElementId",
      "baseName": "sourceStandardElementId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "targetStandardId",
      "baseName": "targetStandardId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "targetStandardElementId",
      "baseName": "targetStandardElementId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "relationshipType",
      "baseName": "relationshipType",
      // false
      // CrosswalkElementRelationshipType
      // CrosswalkElementRelationshipTypeDef
      "type": "CrosswalkElementRelationshipType",
      "format": ""
    },
    {
      "name": "strengthOfRelationship",
      "baseName": "strengthOfRelationship",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    }  ];

  static getAttributeTypeMap() {
    return CrosswalkElement.attributeTypeMap;
  }

  static newInstance(obj: any): CrosswalkElement {
    return ObjectSerializer.deserialize(obj, 'CrosswalkElement');
  }

  constructor(id: UUID, crosswalkId: UUID, sourceStandardId: UUID, sourceStandardElementId: UUID, targetStandardId: UUID, targetStandardElementId: UUID, relationshipType: CrosswalkElementRelationshipTypeDef, strengthOfRelationship?: number) {
    this.id = id;
    this.crosswalkId = crosswalkId;
    this.sourceStandardId = sourceStandardId;
    this.sourceStandardElementId = sourceStandardElementId;
    this.targetStandardId = targetStandardId;
    this.targetStandardElementId = targetStandardElementId;
    this.relationshipType = relationshipType;
    this.strengthOfRelationship = strengthOfRelationship;
  }
}

