/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for deleting targets from a boundary product
*/
export class DeleteBoundaryProductTarget {
  'productTargetIds': Array<UUID>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "productTargetIds",
      "baseName": "productTargetIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return DeleteBoundaryProductTarget.attributeTypeMap;
  }

  static newInstance(obj: any): DeleteBoundaryProductTarget {
    return ObjectSerializer.deserialize(obj, 'DeleteBoundaryProductTarget');
  }

  constructor(productTargetIds: Array<UUID>, ) {
    this.productTargetIds = productTargetIds;
  }
}

