/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ExternalControl } from './ExternalControl.js';
import { ExternalControlOverrideEnum } from './ExternalControlOverrideEnum.js';
import { ExternalControlExtendedAllOf } from './ExternalControlExtendedAllOf.js';
import { ExternalControlOverrideEnumDef } from './ExternalControlOverrideEnum.js';
import { Nmtoken, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class ExternalControlExtended {
  /**
  * Unique identifier
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  /**
  * A resource id which acts as a boundary/container for this resource.
  */
  'boundaryId': UUID;
  /**
  * ID of the framework element control referenced
  */
  'controlId': UUID;
  /**
  * Baseline ids that map to this external control
  */
  'sourceIds': Array<UUID>;
  'controlCode': string;
  /**
  * ID of the framework
  */
  'frameworkId': UUID;
  /**
  * Code of the framework
  */
  'frameworkCode': string;
  /**
  * Name of the framework
  */
  'frameworkName': string;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  /**
  * An external URL to this resource in the outside world
  */
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  'override'?: ExternalControlOverrideEnumDef;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "controlId",
      "baseName": "controlId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "sourceIds",
      "baseName": "sourceIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "controlCode",
      "baseName": "controlCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "frameworkId",
      "baseName": "frameworkId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "frameworkCode",
      "baseName": "frameworkCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "frameworkName",
      "baseName": "frameworkName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "override",
      "baseName": "override",
      // false
      // ExternalControlOverrideEnum
      // ExternalControlOverrideEnumDef
      "type": "ExternalControlOverrideEnum",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return ExternalControlExtended.attributeTypeMap;
  }

  static newInstance(obj: any): ExternalControlExtended {
    return ObjectSerializer.deserialize(obj, 'ExternalControlExtended');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, boundaryId: UUID, controlId: UUID, sourceIds: Array<UUID>, controlCode: string, frameworkId: UUID, frameworkCode: string, frameworkName: string, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, override?: ExternalControlOverrideEnumDef) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.boundaryId = boundaryId;
    this.controlId = controlId;
    this.sourceIds = sourceIds;
    this.controlCode = controlCode;
    this.frameworkId = frameworkId;
    this.frameworkCode = frameworkCode;
    this.frameworkName = frameworkName;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.override = override;
  }
}

