/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EvidenceRequestWithExtendedInfoAllOfEvidenceDefinitions } from './EvidenceRequestWithExtendedInfoAllOfEvidenceDefinitions.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for extended info for evidence request
*/
export class ExtendEvidenceRequest {
  'evidenceDefinitions': Array<EvidenceRequestWithExtendedInfoAllOfEvidenceDefinitions>;
  'subElementCode'?: string | null;
  'frameworkElementCode'?: string;
  'frameworkElementName'?: string;
  'frameworkElementType'?: string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "evidenceDefinitions",
      "baseName": "evidenceDefinitions",
      // false
      // Array&lt;EvidenceRequestWithExtendedInfoAllOfEvidenceDefinitions&gt;
      // Array&lt;EvidenceRequestWithExtendedInfoAllOfEvidenceDefinitions&gt;
      "type": "Array<EvidenceRequestWithExtendedInfoAllOfEvidenceDefinitions>",
      "format": ""
    },
    {
      "name": "subElementCode",
      "baseName": "subElementCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "frameworkElementCode",
      "baseName": "frameworkElementCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "frameworkElementName",
      "baseName": "frameworkElementName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "frameworkElementType",
      "baseName": "frameworkElementType",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return ExtendEvidenceRequest.attributeTypeMap;
  }

  static newInstance(obj: any): ExtendEvidenceRequest {
    return ObjectSerializer.deserialize(obj, 'ExtendEvidenceRequest');
  }

  constructor(evidenceDefinitions: Array<EvidenceRequestWithExtendedInfoAllOfEvidenceDefinitions>, subElementCode?: string, frameworkElementCode?: string, frameworkElementName?: string, frameworkElementType?: string) {
    this.evidenceDefinitions = evidenceDefinitions;
    this.subElementCode = subElementCode;
    this.frameworkElementCode = frameworkElementCode;
    this.frameworkElementName = frameworkElementName;
    this.frameworkElementType = frameworkElementType;
  }
}

