/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { Suite } from './Suite.js';
import { Product } from './Product.js';
import { PropertyClassName } from './PropertyClassName.js';
import { Vendor } from './Vendor.js';
import { Property } from './Property.js';
import { PropertyDataTypeTypeAndLinkClassInfo } from './PropertyDataTypeTypeAndLinkClassInfo.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class ExtendedClass {
  'product': Product;
  'vendor': Vendor;
  'properties': Array<Property & PropertyClassName & PropertyDataTypeTypeAndLinkClassInfo>;
  'suite'?: Suite;
  'vspId'?: UUID;
  'vspType'?: string;
  'vspParentId'?: UUID;
  'vspParentParentId'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "product",
      "baseName": "product",
      // false
      // Product
      // Product
      "type": "Product",
      "format": ""
    },
    {
      "name": "vendor",
      "baseName": "vendor",
      // false
      // Vendor
      // Vendor
      "type": "Vendor",
      "format": ""
    },
    {
      "name": "properties",
      "baseName": "properties",
      // false
      // Array&lt;Property &amp; PropertyClassName &amp; PropertyDataTypeTypeAndLinkClassInfo&gt;
      // Array&lt;Property &amp; PropertyClassName &amp; PropertyDataTypeTypeAndLinkClassInfo&gt;
      "type": "Array<Property & PropertyClassName & PropertyDataTypeTypeAndLinkClassInfo>",
      "format": ""
    },
    {
      "name": "suite",
      "baseName": "suite",
      // false
      // Suite
      // Suite
      "type": "Suite",
      "format": ""
    },
    {
      "name": "vspId",
      "baseName": "vspId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "vspType",
      "baseName": "vspType",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "vspParentId",
      "baseName": "vspParentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "vspParentParentId",
      "baseName": "vspParentParentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return ExtendedClass.attributeTypeMap;
  }

  static newInstance(obj: any): ExtendedClass {
    return ObjectSerializer.deserialize(obj, 'ExtendedClass');
  }

  constructor(product: Product, vendor: Vendor, properties: Array<Property & PropertyClassName & PropertyDataTypeTypeAndLinkClassInfo>, suite?: Suite, vspId?: UUID, vspType?: string, vspParentId?: UUID, vspParentParentId?: UUID) {
    this.product = product;
    this.vendor = vendor;
    this.properties = properties;
    this.suite = suite;
    this.vspId = vspId;
    this.vspType = vspType;
    this.vspParentId = vspParentId;
    this.vspParentParentId = vspParentParentId;
  }
}

