/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* System GraphQL Query Classes Definition
*/
export class GraphqlQueryClasses {
  'id': UUID;
  'graphqlQueryVersionId': UUID | null;
  'classId': UUID | null;
  'npmRegistryId'?: UUID | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "graphqlQueryVersionId",
      "baseName": "graphqlQueryVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "classId",
      "baseName": "classId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "npmRegistryId",
      "baseName": "npmRegistryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return GraphqlQueryClasses.attributeTypeMap;
  }

  static newInstance(obj: any): GraphqlQueryClasses {
    return ObjectSerializer.deserialize(obj, 'GraphqlQueryClasses');
  }

  constructor(id: UUID, graphqlQueryVersionId: UUID, classId: UUID, npmRegistryId?: UUID) {
    this.id = id;
    this.graphqlQueryVersionId = graphqlQueryVersionId;
    this.classId = classId;
    this.npmRegistryId = npmRegistryId;
  }
}

