/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { InternalDomainExtendedAllOf } from './InternalDomainExtendedAllOf.js';
import { InternalDomainExtendedPipeline } from './InternalDomainExtendedPipeline.js';
import { InternalDomain } from './InternalDomain.js';
import { Nmtoken, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class InternalDomainExtended {
  /**
  * Unique identifier
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  /**
  * A resource id which acts as a boundary/container for this resource.
  */
  'boundaryId': UUID;
  /**
  * ID of the scf domain referenced
  */
  'scfDomainCode': string;
  /**
  * Array of the external baseline ids that map to this internal domain
  */
  'sourceIds': Array<UUID>;
  'domainPolicyObjectCount': number;
  'domainPolicyPipelines': Array<InternalDomainExtendedPipeline>;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  /**
  * An external URL to this resource in the outside world
  */
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  /**
  * The team associated with this domain
  */
  'team'?: UUID | null;
  'teamName'?: string | null;
  'intent'?: string | null;
  'designPrinciple'?: string | null;
  'domainPolicyId'?: UUID | null;
  'domainPolicyName'?: string | null;
  'domainPolicyEvidenceBotId'?: UUID | null;
  'domainPolicyQueryVersionId'?: UUID | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "scfDomainCode",
      "baseName": "scfDomainCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "sourceIds",
      "baseName": "sourceIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "domainPolicyObjectCount",
      "baseName": "domainPolicyObjectCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "domainPolicyPipelines",
      "baseName": "domainPolicyPipelines",
      // false
      // Array&lt;InternalDomainExtendedPipeline&gt;
      // Array&lt;InternalDomainExtendedPipeline&gt;
      "type": "Array<InternalDomainExtendedPipeline>",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "team",
      "baseName": "team",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "teamName",
      "baseName": "teamName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "intent",
      "baseName": "intent",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "designPrinciple",
      "baseName": "designPrinciple",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "domainPolicyId",
      "baseName": "domainPolicyId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "domainPolicyName",
      "baseName": "domainPolicyName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "domainPolicyEvidenceBotId",
      "baseName": "domainPolicyEvidenceBotId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "domainPolicyQueryVersionId",
      "baseName": "domainPolicyQueryVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return InternalDomainExtended.attributeTypeMap;
  }

  static newInstance(obj: any): InternalDomainExtended {
    return ObjectSerializer.deserialize(obj, 'InternalDomainExtended');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, boundaryId: UUID, scfDomainCode: string, sourceIds: Array<UUID>, domainPolicyObjectCount: number, domainPolicyPipelines: Array<InternalDomainExtendedPipeline>, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, team?: UUID, teamName?: string, intent?: string, designPrinciple?: string, domainPolicyId?: UUID, domainPolicyName?: string, domainPolicyEvidenceBotId?: UUID, domainPolicyQueryVersionId?: UUID) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.boundaryId = boundaryId;
    this.scfDomainCode = scfDomainCode;
    this.sourceIds = sourceIds;
    this.domainPolicyObjectCount = domainPolicyObjectCount;
    this.domainPolicyPipelines = domainPolicyPipelines;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.team = team;
    this.teamName = teamName;
    this.intent = intent;
    this.designPrinciple = designPrinciple;
    this.domainPolicyId = domainPolicyId;
    this.domainPolicyName = domainPolicyName;
    this.domainPolicyEvidenceBotId = domainPolicyEvidenceBotId;
    this.domainPolicyQueryVersionId = domainPolicyQueryVersionId;
  }
}

