/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CapabilityMaturityModelDef } from './CapabilityMaturityModel.js';
import { CapabilityMaturityModel } from './CapabilityMaturityModel.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Describes a internal control
*/
export class InternalControlAllOf {
  /**
  * ID of the scf control referenced
  */
  'scfControlId': UUID;
  /**
  * Array of the external baseline ids that map to this internal control
  */
  'sourceIds': Array<UUID>;
  /**
  * Whether the scf control is being performed in this boundary
  */
  'performed'?: boolean | null;
  'performedMaturity'?: CapabilityMaturityModelDef;
  'desiredMaturity'?: CapabilityMaturityModelDef;
  'standard'?: string | null;
  'guideline'?: string | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "scfControlId",
      "baseName": "scfControlId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "sourceIds",
      "baseName": "sourceIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "performed",
      "baseName": "performed",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "performedMaturity",
      "baseName": "performedMaturity",
      // false
      // CapabilityMaturityModel
      // CapabilityMaturityModelDef
      "type": "CapabilityMaturityModel",
      "format": ""
    },
    {
      "name": "desiredMaturity",
      "baseName": "desiredMaturity",
      // false
      // CapabilityMaturityModel
      // CapabilityMaturityModelDef
      "type": "CapabilityMaturityModel",
      "format": ""
    },
    {
      "name": "standard",
      "baseName": "standard",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "guideline",
      "baseName": "guideline",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return InternalControlAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): InternalControlAllOf {
    return ObjectSerializer.deserialize(obj, 'InternalControlAllOf');
  }

  constructor(scfControlId: UUID, sourceIds: Array<UUID>, performed?: boolean, performedMaturity?: CapabilityMaturityModelDef, desiredMaturity?: CapabilityMaturityModelDef, standard?: string, guideline?: string) {
    this.scfControlId = scfControlId;
    this.sourceIds = sourceIds;
    this.performed = performed;
    this.performedMaturity = performedMaturity;
    this.desiredMaturity = desiredMaturity;
    this.standard = standard;
    this.guideline = guideline;
  }
}

