/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { BatchLogLevelEnumDef } from './BatchLogLevelEnum.js';
import { BatchLogLevelEnum } from './BatchLogLevelEnum.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Log Item for a Batch
*/
export class LocalBatchLog {
  'logLevel': BatchLogLevelEnumDef;
  /**
  * The message to log
  */
  'message': string;
  'data': object;
  'timestamp': Date;
  'batchId': UUID;
  'className': string;
  'moduleName': string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "logLevel",
      "baseName": "logLevel",
      // false
      // BatchLogLevelEnum
      // BatchLogLevelEnumDef
      "type": "BatchLogLevelEnum",
      "format": ""
    },
    {
      "name": "message",
      "baseName": "message",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "data",
      "baseName": "data",
      // false
      // object
      // object
      "type": "object",
      "format": ""
    },
    {
      "name": "timestamp",
      "baseName": "timestamp",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "batchId",
      "baseName": "batchId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "className",
      "baseName": "className",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "moduleName",
      "baseName": "moduleName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return LocalBatchLog.attributeTypeMap;
  }

  static newInstance(obj: any): LocalBatchLog {
    return ObjectSerializer.deserialize(obj, 'LocalBatchLog');
  }

  constructor(logLevel: BatchLogLevelEnumDef, message: string, data: object, timestamp: Date, batchId: UUID, className: string, moduleName: string, ) {
    this.logLevel = logLevel;
    this.message = message;
    this.data = data;
    this.timestamp = timestamp;
    this.batchId = batchId;
    this.className = className;
    this.moduleName = moduleName;
  }
}

