/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { Schedule } from './Schedule.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* An Alert Trigger Selector Template, When providing an event it must be a changeEvent.  `event` must not be provided if cron is provided
*/
export class NewBoundaryAlertBotExtendedOn {
  /**
  * the event type this selector applies to. Does not need to be specified for `cron` selectors. Must be specified for changeEvent selectors
  */
  'event'?: string | null;
  /**
  * a set of operations on the selected event that this selector listens to. Provide `*` when listening to all change operations.
  */
  'op'?: Array<string> | string | null;
  'schedule'?: Schedule;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "event",
      "baseName": "event",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "op",
      "baseName": "op",
      // false
      // Array&lt;string&gt; | string
      // Array&lt;string&gt; | string
      "type": "Array<string> | string",
      "format": ""
    },
    {
      "name": "schedule",
      "baseName": "schedule",
      // false
      // Schedule
      // Schedule
      "type": "Schedule",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return NewBoundaryAlertBotExtendedOn.attributeTypeMap;
  }

  static newInstance(obj: any): NewBoundaryAlertBotExtendedOn {
    return ObjectSerializer.deserialize(obj, 'NewBoundaryAlertBotExtendedOn');
  }

  constructor(event?: string, op?: Array<string> | string, schedule?: Schedule) {
    this.event = event;
    this.op = op;
    this.schedule = schedule;
  }
}

