/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { SchemasTag } from './SchemasTag.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for a new evidence request list
*/
export class NewEvidenceRequestList {
  /**
  * The name of the evidence request list
  */
  'name': string;
  /**
  * The ID of the framework version assigned to the request list
  */
  'frameworkVersionId': UUID;
  /**
  * The description of the evidence request list
  */
  'description'?: string | null;
  'tags'?: Array<SchemasTag>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "frameworkVersionId",
      "baseName": "frameworkVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "tags",
      "baseName": "tags",
      // false
      // Array&lt;SchemasTag&gt;
      // Array&lt;SchemasTag&gt;
      "type": "Array<SchemasTag>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return NewEvidenceRequestList.attributeTypeMap;
  }

  static newInstance(obj: any): NewEvidenceRequestList {
    return ObjectSerializer.deserialize(obj, 'NewEvidenceRequestList');
  }

  constructor(name: string, frameworkVersionId: UUID, description?: string, tags?: Array<SchemasTag>) {
    this.name = name;
    this.frameworkVersionId = frameworkVersionId;
    this.description = description;
    this.tags = tags;
  }
}

