/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Type of connector
*/
export const PipelineConnectorTypeEnum = {
  /**  */
  ProductSpecific: EnumValue.instance('PipelineConnectorTypeEnum', 'ProductSpecific', 'product_specific'),
  /**  */
  File: EnumValue.instance('PipelineConnectorTypeEnum', 'File', 'file'),
  /**  */
  Spreadsheet: EnumValue.instance('PipelineConnectorTypeEnum', 'Spreadsheet', 'spreadsheet'),
  /**  */
  Dynamic: EnumValue.instance('PipelineConnectorTypeEnum', 'Dynamic', 'dynamic'),

  from(val: string | number): EnumValue {
    if (PipelineConnectorTypeEnum[val]) {
      return PipelineConnectorTypeEnum[val];
    }
    const byValue = PipelineConnectorTypeEnum.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid PipelineConnectorTypeEnum`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(PipelineConnectorTypeEnum)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => PipelineConnectorTypeEnum[t]);
  }
} as const;

export type PipelineConnectorTypeEnumDef = typeof PipelineConnectorTypeEnum[keyof typeof PipelineConnectorTypeEnum];
