/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { PipelineExtendedComponent } from './PipelineExtendedComponent.js';
import { PipelineExtendedGetUploadedEvidence } from './PipelineExtendedGetUploadedEvidence.js';
import { PipelineExtendedGetAuditgraph } from './PipelineExtendedGetAuditgraph.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Describes a pipeline extended get
*/
export class PipelineExtendedGetAllOf {
  'auditgraph': Array<PipelineExtendedGetAuditgraph>;
  'uploadedEvidence': Array<PipelineExtendedGetUploadedEvidence>;
  'supportedComponents': Array<PipelineExtendedComponent>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "auditgraph",
      "baseName": "auditgraph",
      // false
      // Array&lt;PipelineExtendedGetAuditgraph&gt;
      // Array&lt;PipelineExtendedGetAuditgraph&gt;
      "type": "Array<PipelineExtendedGetAuditgraph>",
      "format": ""
    },
    {
      "name": "uploadedEvidence",
      "baseName": "uploadedEvidence",
      // false
      // Array&lt;PipelineExtendedGetUploadedEvidence&gt;
      // Array&lt;PipelineExtendedGetUploadedEvidence&gt;
      "type": "Array<PipelineExtendedGetUploadedEvidence>",
      "format": ""
    },
    {
      "name": "supportedComponents",
      "baseName": "supportedComponents",
      // false
      // Array&lt;PipelineExtendedComponent&gt;
      // Array&lt;PipelineExtendedComponent&gt;
      "type": "Array<PipelineExtendedComponent>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return PipelineExtendedGetAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): PipelineExtendedGetAllOf {
    return ObjectSerializer.deserialize(obj, 'PipelineExtendedGetAllOf');
  }

  constructor(auditgraph: Array<PipelineExtendedGetAuditgraph>, uploadedEvidence: Array<PipelineExtendedGetUploadedEvidence>, supportedComponents: Array<PipelineExtendedComponent>, ) {
    this.auditgraph = auditgraph;
    this.uploadedEvidence = uploadedEvidence;
    this.supportedComponents = supportedComponents;
  }
}

