/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { PipelineJobTarget } from './PipelineJobTarget.js';
import { PipelineJobStatusEnumDef } from './PipelineJobStatusEnum.js';
import { PipelineJobStatusEnum } from './PipelineJobStatusEnum.js';
import { Duration, UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Describes a pipeline job
*/
export class PipelineJob {
  'id': UUID;
  'ownerId': UUID;
  'pipelineId': UUID;
  'runDate': Date;
  'status': PipelineJobStatusEnumDef;
  'previewMode': boolean;
  'instanceNumber'?: number | null;
  'executionStartTime'?: Date | null;
  'duration'?: Duration | null;
  'jobError'?: object | null;
  'executionDetails'?: { [key: string]: any; } | null;
  'previewCount'?: number | null;
  /**
  * The token set at completion of this job, if any.
  */
  'token'?: string;
  'target'?: PipelineJobTarget;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "pipelineId",
      "baseName": "pipelineId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "runDate",
      "baseName": "runDate",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // PipelineJobStatusEnum
      // PipelineJobStatusEnumDef
      "type": "PipelineJobStatusEnum",
      "format": ""
    },
    {
      "name": "previewMode",
      "baseName": "previewMode",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "instanceNumber",
      "baseName": "instanceNumber",
      // false
      // number
      // number
      "type": "number",
      "format": "int64"
    },
    {
      "name": "executionStartTime",
      "baseName": "executionStartTime",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "duration",
      "baseName": "duration",
      // false
      // Duration
      // Duration
      "type": "Duration",
      "format": "duration"
    },
    {
      "name": "jobError",
      "baseName": "jobError",
      // false
      // object
      // object
      "type": "object",
      "format": ""
    },
    {
      "name": "executionDetails",
      "baseName": "executionDetails",
      // false
      // { [key: string]: any; }
      // { [key: string]: any; }
      "type": "{ [key: string]: any; }",
      "format": ""
    },
    {
      "name": "previewCount",
      "baseName": "previewCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "token",
      "baseName": "token",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "target",
      "baseName": "target",
      // false
      // PipelineJobTarget
      // PipelineJobTarget
      "type": "PipelineJobTarget",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return PipelineJob.attributeTypeMap;
  }

  static newInstance(obj: any): PipelineJob {
    return ObjectSerializer.deserialize(obj, 'PipelineJob');
  }

  constructor(id: UUID, ownerId: UUID, pipelineId: UUID, runDate: Date, status: PipelineJobStatusEnumDef, previewMode: boolean, instanceNumber?: number, executionStartTime?: Date, duration?: Duration, jobError?: object, executionDetails?: { [key: string]: any; }, previewCount?: number, token?: string, target?: PipelineJobTarget) {
    this.id = id;
    this.ownerId = ownerId;
    this.pipelineId = pipelineId;
    this.runDate = runDate;
    this.status = status;
    this.previewMode = previewMode;
    this.instanceNumber = instanceNumber;
    this.executionStartTime = executionStartTime;
    this.duration = duration;
    this.jobError = jobError;
    this.executionDetails = executionDetails;
    this.previewCount = previewCount;
    this.token = token;
    this.target = target;
  }
}

