/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class PipelineExtendedGetAuditgraph {
  'classId': UUID;
  'className': string;
  'objectCount': number;
  'classImageUrl'?: URL | null;
  'dynamicClassId'?: UUID | null;
  'dynamicClassName'?: string | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "classId",
      "baseName": "classId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "className",
      "baseName": "className",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "objectCount",
      "baseName": "objectCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "classImageUrl",
      "baseName": "classImageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "dynamicClassId",
      "baseName": "dynamicClassId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "dynamicClassName",
      "baseName": "dynamicClassName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return PipelineExtendedGetAuditgraph.attributeTypeMap;
  }

  static newInstance(obj: any): PipelineExtendedGetAuditgraph {
    return ObjectSerializer.deserialize(obj, 'PipelineExtendedGetAuditgraph');
  }

  constructor(classId: UUID, className: string, objectCount: number, classImageUrl?: URL, dynamicClassId?: UUID, dynamicClassName?: string) {
    this.classId = classId;
    this.className = className;
    this.objectCount = objectCount;
    this.classImageUrl = classImageUrl;
    this.dynamicClassId = dynamicClassId;
    this.dynamicClassName = dynamicClassName;
  }
}

