/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const PrincipalStatus = {
  /**  */
  Provisioned: EnumValue.instance('PrincipalStatus', 'Provisioned', 'provisioned'),
  /**  */
  Active: EnumValue.instance('PrincipalStatus', 'Active', 'active'),
  /**  */
  Inactive: EnumValue.instance('PrincipalStatus', 'Inactive', 'inactive'),

  from(val: string | number): EnumValue {
    if (PrincipalStatus[val]) {
      return PrincipalStatus[val];
    }
    const byValue = PrincipalStatus.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid PrincipalStatus`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(PrincipalStatus)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => PrincipalStatus[t]);
  }
} as const;

export type PrincipalStatusDef = typeof PrincipalStatus[keyof typeof PrincipalStatus];
