/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ResourceSelectorConditionType } from './ResourceSelectorConditionType.js';
import { ResourceSelectorConditionTypeDef } from './ResourceSelectorConditionType.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* A condition that may be evaluated when requesting access to a resource Conditions may be of one of three types:














































































































































































































































































































































  * json: Evaluates json payload properties based on a path and operator
  * tag: Matches if the resource is tagged by the given tagId
  * function: matches if the given function evaluates to true
*/
export class ResourceSelectorCondition {
  /**
  * The id of the condition
  */
  'id': UUID;
  /**
  * The name of the condition
  */
  'name': string;
  /**
  * The id of the selector this condition applies to
  */
  'resourceSelectorId': UUID;
  'type': ResourceSelectorConditionTypeDef;

  static readonly discriminator: string | undefined = "type";

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "resourceSelectorId",
      "baseName": "resourceSelectorId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // ResourceSelectorConditionType
      // ResourceSelectorConditionTypeDef
      "type": "ResourceSelectorConditionType",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return ResourceSelectorCondition.attributeTypeMap;
  }

  static newInstance(obj: any): ResourceSelectorCondition {
    return ObjectSerializer.deserialize(obj, 'ResourceSelectorCondition');
  }

  constructor(id: UUID, name: string, resourceSelectorId: UUID, type: ResourceSelectorConditionTypeDef, ) {
    this.id = id;
    this.name = name;
    this.resourceSelectorId = resourceSelectorId;
    this.type = type;
  }
}

