/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Enum for a Role Type
*/
export const RoleType = {
  /**  */
  Org: EnumValue.instance('RoleType', 'Org', 'org'),
  /**  */
  Boundary: EnumValue.instance('RoleType', 'Boundary', 'boundary'),
  /**  */
  Compliance: EnumValue.instance('RoleType', 'Compliance', 'compliance'),

  from(val: string | number): EnumValue {
    if (RoleType[val]) {
      return RoleType[val];
    }
    const byValue = RoleType.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid RoleType`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(RoleType)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => RoleType[t]);
  }
} as const;

export type RoleTypeDef = typeof RoleType[keyof typeof RoleType];
