/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Enumeration for different types of Principals
*/
export const SchemasPrincipalType = {
  /**  */
  Org: EnumValue.instance('SchemasPrincipalType', 'Org', 'ORG'),
  /**  */
  Group: EnumValue.instance('SchemasPrincipalType', 'Group', 'GROUP'),
  /**  */
  User: EnumValue.instance('SchemasPrincipalType', 'User', 'USER'),
  /**  */
  ApiKey: EnumValue.instance('SchemasPrincipalType', 'ApiKey', 'API_KEY'),
  /**  */
  ServiceAccount: EnumValue.instance('SchemasPrincipalType', 'ServiceAccount', 'SERVICE_ACCOUNT'),

  from(val: string | number): EnumValue {
    if (SchemasPrincipalType[val]) {
      return SchemasPrincipalType[val];
    }
    const byValue = SchemasPrincipalType.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid SchemasPrincipalType`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(SchemasPrincipalType)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => SchemasPrincipalType[t]);
  }
} as const;

export type SchemasPrincipalTypeDef = typeof SchemasPrincipalType[keyof typeof SchemasPrincipalType];
