/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { Semver, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class SegmentProductStub {
  'id': UUID;
  'latestVersionId': UUID;
  'name': string;
  'code': string;
  'version': Semver;
  'description'?: string | null;
  'imageUrl'?: URL | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "latestVersionId",
      "baseName": "latestVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "version",
      "baseName": "version",
      // false
      // Semver
      // Semver
      "type": "Semver",
      "format": "semver"
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    }  ];

  static getAttributeTypeMap() {
    return SegmentProductStub.attributeTypeMap;
  }

  static newInstance(obj: any): SegmentProductStub {
    return ObjectSerializer.deserialize(obj, 'SegmentProductStub');
  }

  constructor(id: UUID, latestVersionId: UUID, name: string, code: string, version: Semver, description?: string, imageUrl?: URL) {
    this.id = id;
    this.latestVersionId = latestVersionId;
    this.name = name;
    this.code = code;
    this.version = version;
    this.description = description;
    this.imageUrl = imageUrl;
  }
}

