/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { SegmentExtendedGetAllOf } from './SegmentExtendedGetAllOf.js';
import { ParentSegmentVersion } from './ParentSegmentVersion.js';
import { SegmentVersion } from './SegmentVersion.js';
import { SegmentExtended } from './SegmentExtended.js';
import { SegmentProductStub } from './SegmentProductStub.js';
import { SegmentType } from './SegmentType.js';
import { CatalogPublishStatusEnumDef } from './CatalogPublishStatusEnum.js';
import { CatalogPublishStatusEnum } from './CatalogPublishStatusEnum.js';
import { SegmentComplianceFeature } from './SegmentComplianceFeature.js';
import { Nmtoken, Semver, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class SegmentExtendedGet {
  /**
  * Unique identifier
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  'status': CatalogPublishStatusEnumDef;
  'latestVersionId': UUID;
  'latestVersion': SegmentVersion;
  'code': string;
  'externalId': string;
  'segmentTypeId': UUID;
  'versionId': UUID;
  'versionSemver': Semver;
  'versionValue': number;
  'versionFloatValue': string;
  'isService': boolean;
  'segmentType': SegmentType;
  'parents': Array<ParentSegmentVersion>;
  'children': Array<ParentSegmentVersion>;
  'products': Array<SegmentProductStub>;
  'complianceFeatures': Array<SegmentComplianceFeature>;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  /**
  * An external URL to this resource in the outside world
  */
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  /**
  * A resource id which acts as a boundary/container for this resource.
  */
  'boundaryId'?: UUID;
  'packageCode'?: string;
  'artifactId'?: UUID;
  'publishedArtifactName'?: string;
  'latestReleasedVersionId'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // CatalogPublishStatusEnum
      // CatalogPublishStatusEnumDef
      "type": "CatalogPublishStatusEnum",
      "format": ""
    },
    {
      "name": "latestVersionId",
      "baseName": "latestVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "latestVersion",
      "baseName": "latestVersion",
      // false
      // SegmentVersion
      // SegmentVersion
      "type": "SegmentVersion",
      "format": ""
    },
    {
      "name": "code",
      "baseName": "code",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "externalId",
      "baseName": "externalId",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "segmentTypeId",
      "baseName": "segmentTypeId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "versionId",
      "baseName": "versionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "versionSemver",
      "baseName": "versionSemver",
      // false
      // Semver
      // Semver
      "type": "Semver",
      "format": "semver"
    },
    {
      "name": "versionValue",
      "baseName": "versionValue",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "versionFloatValue",
      "baseName": "versionFloatValue",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "isService",
      "baseName": "isService",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "segmentType",
      "baseName": "segmentType",
      // false
      // SegmentType
      // SegmentType
      "type": "SegmentType",
      "format": ""
    },
    {
      "name": "parents",
      "baseName": "parents",
      // false
      // Array&lt;ParentSegmentVersion&gt;
      // Array&lt;ParentSegmentVersion&gt;
      "type": "Array<ParentSegmentVersion>",
      "format": ""
    },
    {
      "name": "children",
      "baseName": "children",
      // false
      // Array&lt;ParentSegmentVersion&gt;
      // Array&lt;ParentSegmentVersion&gt;
      "type": "Array<ParentSegmentVersion>",
      "format": ""
    },
    {
      "name": "products",
      "baseName": "products",
      // false
      // Array&lt;SegmentProductStub&gt;
      // Array&lt;SegmentProductStub&gt;
      "type": "Array<SegmentProductStub>",
      "format": ""
    },
    {
      "name": "complianceFeatures",
      "baseName": "complianceFeatures",
      // false
      // Array&lt;SegmentComplianceFeature&gt;
      // Array&lt;SegmentComplianceFeature&gt;
      "type": "Array<SegmentComplianceFeature>",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "artifactId",
      "baseName": "artifactId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "publishedArtifactName",
      "baseName": "publishedArtifactName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "latestReleasedVersionId",
      "baseName": "latestReleasedVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return SegmentExtendedGet.attributeTypeMap;
  }

  static newInstance(obj: any): SegmentExtendedGet {
    return ObjectSerializer.deserialize(obj, 'SegmentExtendedGet');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, status: CatalogPublishStatusEnumDef, latestVersionId: UUID, latestVersion: SegmentVersion, code: string, externalId: string, segmentTypeId: UUID, versionId: UUID, versionSemver: Semver, versionValue: number, versionFloatValue: string, isService: boolean, segmentType: SegmentType, parents: Array<ParentSegmentVersion>, children: Array<ParentSegmentVersion>, products: Array<SegmentProductStub>, complianceFeatures: Array<SegmentComplianceFeature>, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, boundaryId?: UUID, packageCode?: string, artifactId?: UUID, publishedArtifactName?: string, latestReleasedVersionId?: UUID) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.status = status;
    this.latestVersionId = latestVersionId;
    this.latestVersion = latestVersion;
    this.code = code;
    this.externalId = externalId;
    this.segmentTypeId = segmentTypeId;
    this.versionId = versionId;
    this.versionSemver = versionSemver;
    this.versionValue = versionValue;
    this.versionFloatValue = versionFloatValue;
    this.isService = isService;
    this.segmentType = segmentType;
    this.parents = parents;
    this.children = children;
    this.products = products;
    this.complianceFeatures = complianceFeatures;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.boundaryId = boundaryId;
    this.packageCode = packageCode;
    this.artifactId = artifactId;
    this.publishedArtifactName = publishedArtifactName;
    this.latestReleasedVersionId = latestReleasedVersionId;
  }
}

