/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const StandardStatus = {
  /**  */
  Deleted: EnumValue.instance('StandardStatus', 'Deleted', 'deleted'),
  /**  */
  Expired: EnumValue.instance('StandardStatus', 'Expired', 'expired'),
  /**  */
  Featured: EnumValue.instance('StandardStatus', 'Featured', 'featured'),
  /**  */
  Approved: EnumValue.instance('StandardStatus', 'Approved', 'approved'),
  /**  */
  Disapproved: EnumValue.instance('StandardStatus', 'Disapproved', 'disapproved'),
  /**  */
  Pending: EnumValue.instance('StandardStatus', 'Pending', 'pending'),
  /**  */
  SavedDraft: EnumValue.instance('StandardStatus', 'SavedDraft', 'saved_draft'),

  from(val: string | number): EnumValue {
    if (StandardStatus[val]) {
      return StandardStatus[val];
    }
    const byValue = StandardStatus.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid StandardStatus`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(StandardStatus)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => StandardStatus[t]);
  }
} as const;

export type StandardStatusDef = typeof StandardStatus[keyof typeof StandardStatus];
