/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ElementType } from './ElementType.js';
import { SchemasTag } from './SchemasTag.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Standard extended schema
*/
export class StandardExtendedAllOf {
  'elementTypes': Array<ElementType>;
  'rootMappingType': ElementType;
  'mappingTypes': Array<ElementType>;
  'tags'?: Array<SchemasTag>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "elementTypes",
      "baseName": "elementTypes",
      // false
      // Array&lt;ElementType&gt;
      // Array&lt;ElementType&gt;
      "type": "Array<ElementType>",
      "format": ""
    },
    {
      "name": "rootMappingType",
      "baseName": "rootMappingType",
      // false
      // ElementType
      // ElementType
      "type": "ElementType",
      "format": ""
    },
    {
      "name": "mappingTypes",
      "baseName": "mappingTypes",
      // false
      // Array&lt;ElementType&gt;
      // Array&lt;ElementType&gt;
      "type": "Array<ElementType>",
      "format": ""
    },
    {
      "name": "tags",
      "baseName": "tags",
      // false
      // Array&lt;SchemasTag&gt;
      // Array&lt;SchemasTag&gt;
      "type": "Array<SchemasTag>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return StandardExtendedAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): StandardExtendedAllOf {
    return ObjectSerializer.deserialize(obj, 'StandardExtendedAllOf');
  }

  constructor(elementTypes: Array<ElementType>, rootMappingType: ElementType, mappingTypes: Array<ElementType>, tags?: Array<SchemasTag>) {
    this.elementTypes = elementTypes;
    this.rootMappingType = rootMappingType;
    this.mappingTypes = mappingTypes;
    this.tags = tags;
  }
}

