/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for a suggested vendor
*/
export class SuggestedVendor {
  'id': UUID;
  'name': string;
  'ownerId': UUID;
  'created': Date;
  'description'?: string | null;
  'imageUrl'?: URL | null;
  'url'?: URL | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    }  ];

  static getAttributeTypeMap() {
    return SuggestedVendor.attributeTypeMap;
  }

  static newInstance(obj: any): SuggestedVendor {
    return ObjectSerializer.deserialize(obj, 'SuggestedVendor');
  }

  constructor(id: UUID, name: string, ownerId: UUID, created: Date, description?: string, imageUrl?: URL, url?: URL) {
    this.id = id;
    this.name = name;
    this.ownerId = ownerId;
    this.created = created;
    this.description = description;
    this.imageUrl = imageUrl;
    this.url = url;
  }
}

