/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { TagScopeEnumDef } from './TagScopeEnum.js';
import { IdNameDescriptionImageUrlObject } from './IdNameDescriptionImageUrlObject.js';
import { TagScopeEnum } from './TagScopeEnum.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class TagExtendedAllOf {
  'owner'?: IdNameDescriptionImageUrlObject;
  'scope'?: TagScopeEnumDef;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "owner",
      "baseName": "owner",
      // false
      // IdNameDescriptionImageUrlObject
      // IdNameDescriptionImageUrlObject
      "type": "IdNameDescriptionImageUrlObject",
      "format": ""
    },
    {
      "name": "scope",
      "baseName": "scope",
      // false
      // TagScopeEnum
      // TagScopeEnumDef
      "type": "TagScopeEnum",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return TagExtendedAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): TagExtendedAllOf {
    return ObjectSerializer.deserialize(obj, 'TagExtendedAllOf');
  }

  constructor(owner?: IdNameDescriptionImageUrlObject, scope?: TagScopeEnumDef) {
    this.owner = owner;
    this.scope = scope;
  }
}

