/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { Email, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Details of the person that created the comment.
*/
export class TaskCommentPerson {
  /**
  * The name of the person that created this comment
  */
  'name': string;
  /**
  * The emails of the person that created this comment
  */
  'emails': Array<Email>;
  'imageUrl'?: URL;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "emails",
      "baseName": "emails",
      // false
      // Array&lt;Email&gt;
      // Array&lt;Email&gt;
      "type": "Array<Email>",
      "format": "email"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    }  ];

  static getAttributeTypeMap() {
    return TaskCommentPerson.attributeTypeMap;
  }

  static newInstance(obj: any): TaskCommentPerson {
    return ObjectSerializer.deserialize(obj, 'TaskCommentPerson');
  }

  constructor(name: string, emails: Array<Email>, imageUrl?: URL) {
    this.name = name;
    this.emails = emails;
    this.imageUrl = imageUrl;
  }
}

