/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { Test } from './Test.js';
import { TestCase } from './TestCase.js';
import { TestExtendedAllOf } from './TestExtendedAllOf.js';
import { TestResultEnumDef } from './TestResultEnum.js';
import { TestFindingSourceDef } from './TestFindingSource.js';
import { TestFindingSource } from './TestFindingSource.js';
import { TestResultEnum } from './TestResultEnum.js';
import { Component } from './Component.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class TestExtended {
  'id': UUID;
  'ownerId': UUID;
  'testCaseId': UUID;
  'testDate': Date;
  'result': TestResultEnumDef;
  'source': TestFindingSourceDef;
  'testCase': TestCase;
  'subjects': Array<Component>;
  'localId'?: UUID | null;
  'objectId'?: UUID | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "testCaseId",
      "baseName": "testCaseId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "testDate",
      "baseName": "testDate",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "result",
      "baseName": "result",
      // false
      // TestResultEnum
      // TestResultEnumDef
      "type": "TestResultEnum",
      "format": ""
    },
    {
      "name": "source",
      "baseName": "source",
      // false
      // TestFindingSource
      // TestFindingSourceDef
      "type": "TestFindingSource",
      "format": ""
    },
    {
      "name": "testCase",
      "baseName": "testCase",
      // false
      // TestCase
      // TestCase
      "type": "TestCase",
      "format": ""
    },
    {
      "name": "subjects",
      "baseName": "subjects",
      // false
      // Array&lt;Component&gt;
      // Array&lt;Component&gt;
      "type": "Array<Component>",
      "format": ""
    },
    {
      "name": "localId",
      "baseName": "localId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "objectId",
      "baseName": "objectId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return TestExtended.attributeTypeMap;
  }

  static newInstance(obj: any): TestExtended {
    return ObjectSerializer.deserialize(obj, 'TestExtended');
  }

  constructor(id: UUID, ownerId: UUID, testCaseId: UUID, testDate: Date, result: TestResultEnumDef, source: TestFindingSourceDef, testCase: TestCase, subjects: Array<Component>, localId?: UUID, objectId?: UUID) {
    this.id = id;
    this.ownerId = ownerId;
    this.testCaseId = testCaseId;
    this.testDate = testDate;
    this.result = result;
    this.source = source;
    this.testCase = testCase;
    this.subjects = subjects;
    this.localId = localId;
    this.objectId = objectId;
  }
}

