/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { PipelineMonthOfYearEnum } from './PipelineMonthOfYearEnum.js';
import { PipelineExecutionModeEnumDef } from './PipelineExecutionModeEnum.js';
import { PipelineAdminStatusEnumDef } from './PipelineAdminStatusEnum.js';
import { PipelineDayOfWeekEnum } from './PipelineDayOfWeekEnum.js';
import { PipelineDayOfWeekEnumDef } from './PipelineDayOfWeekEnum.js';
import { PipelineScopeModeEnumDef } from './PipelineScopeModeEnum.js';
import { TimeZone } from './TimeZone.js';
import { PipelineFrequencyEnumDef } from './PipelineFrequencyEnum.js';
import { PipelineAdminStatusEnum } from './PipelineAdminStatusEnum.js';
import { TimeZoneDef } from './TimeZone.js';
import { PipelineExecutionModeEnum } from './PipelineExecutionModeEnum.js';
import { PipelineFrequencyEnum } from './PipelineFrequencyEnum.js';
import { PipelineSelectedScopes } from './PipelineSelectedScopes.js';
import { PipelineMonthOfYearEnumDef } from './PipelineMonthOfYearEnum.js';
import { PipelineScopeModeEnum } from './PipelineScopeModeEnum.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Describes a pipeline
*/
export class UpdatePipeline {
  'adminStatus'?: PipelineAdminStatusEnumDef;
  /**
  * Name of the pipeline
  */
  'name'?: string;
  /**
  * Description of the pipeline
  */
  'description'?: string | null;
  'frequency'?: PipelineFrequencyEnumDef;
  'executionTime'?: string | null;
  'executionMode'?: PipelineExecutionModeEnumDef;
  'dayOfWeek'?: PipelineDayOfWeekEnumDef;
  'dayOfMonth'?: number | null;
  'monthOfYear'?: PipelineMonthOfYearEnumDef;
  'timezone'?: TimeZoneDef;
  'targets'?: { [key: string]: UUID; };
  'collectorBotId'?: UUID | null;
  'params'?: object | null;
  'promotePreview'?: boolean | null;
  'scopeMode'?: PipelineScopeModeEnumDef;
  'selectedScopes'?: PipelineSelectedScopes | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "adminStatus",
      "baseName": "adminStatus",
      // false
      // PipelineAdminStatusEnum
      // PipelineAdminStatusEnumDef
      "type": "PipelineAdminStatusEnum",
      "format": ""
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "frequency",
      "baseName": "frequency",
      // false
      // PipelineFrequencyEnum
      // PipelineFrequencyEnumDef
      "type": "PipelineFrequencyEnum",
      "format": ""
    },
    {
      "name": "executionTime",
      "baseName": "executionTime",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "executionMode",
      "baseName": "executionMode",
      // false
      // PipelineExecutionModeEnum
      // PipelineExecutionModeEnumDef
      "type": "PipelineExecutionModeEnum",
      "format": ""
    },
    {
      "name": "dayOfWeek",
      "baseName": "dayOfWeek",
      // false
      // PipelineDayOfWeekEnum
      // PipelineDayOfWeekEnumDef
      "type": "PipelineDayOfWeekEnum",
      "format": ""
    },
    {
      "name": "dayOfMonth",
      "baseName": "dayOfMonth",
      // false
      // number
      // number
      "type": "number",
      "format": "int64"
    },
    {
      "name": "monthOfYear",
      "baseName": "monthOfYear",
      // false
      // PipelineMonthOfYearEnum
      // PipelineMonthOfYearEnumDef
      "type": "PipelineMonthOfYearEnum",
      "format": ""
    },
    {
      "name": "timezone",
      "baseName": "timezone",
      // false
      // TimeZone
      // TimeZoneDef
      "type": "TimeZone",
      "format": ""
    },
    {
      "name": "targets",
      "baseName": "targets",
      // false
      // { [key: string]: UUID; }
      // { [key: string]: UUID; }
      "type": "{ [key: string]: UUID; }",
      "format": "uuid"
    },
    {
      "name": "collectorBotId",
      "baseName": "collectorBotId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "params",
      "baseName": "params",
      // false
      // object
      // object
      "type": "object",
      "format": ""
    },
    {
      "name": "promotePreview",
      "baseName": "promotePreview",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "scopeMode",
      "baseName": "scopeMode",
      // false
      // PipelineScopeModeEnum
      // PipelineScopeModeEnumDef
      "type": "PipelineScopeModeEnum",
      "format": ""
    },
    {
      "name": "selectedScopes",
      "baseName": "selectedScopes",
      // false
      // PipelineSelectedScopes
      // PipelineSelectedScopes
      "type": "PipelineSelectedScopes",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return UpdatePipeline.attributeTypeMap;
  }

  static newInstance(obj: any): UpdatePipeline {
    return ObjectSerializer.deserialize(obj, 'UpdatePipeline');
  }

  constructor(adminStatus?: PipelineAdminStatusEnumDef, name?: string, description?: string, frequency?: PipelineFrequencyEnumDef, executionTime?: string, executionMode?: PipelineExecutionModeEnumDef, dayOfWeek?: PipelineDayOfWeekEnumDef, dayOfMonth?: number, monthOfYear?: PipelineMonthOfYearEnumDef, timezone?: TimeZoneDef, targets?: { [key: string]: UUID; }, collectorBotId?: UUID, params?: object, promotePreview?: boolean, scopeMode?: PipelineScopeModeEnumDef, selectedScopes?: PipelineSelectedScopes) {
    this.adminStatus = adminStatus;
    this.name = name;
    this.description = description;
    this.frequency = frequency;
    this.executionTime = executionTime;
    this.executionMode = executionMode;
    this.dayOfWeek = dayOfWeek;
    this.dayOfMonth = dayOfMonth;
    this.monthOfYear = monthOfYear;
    this.timezone = timezone;
    this.targets = targets;
    this.collectorBotId = collectorBotId;
    this.params = params;
    this.promotePreview = promotePreview;
    this.scopeMode = scopeMode;
    this.selectedScopes = selectedScopes;
  }
}

