/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { GraphqlQueryVersionPagination } from './GraphqlQueryVersionPagination.js';
import { PublishQueryStatusEnumDef } from './PublishQueryStatusEnum.js';
import { GraphqlQueryVersionSystemParameters } from './GraphqlQueryVersionSystemParameters.js';
import { UpdateGraphqlQueryFields } from './UpdateGraphqlQueryFields.js';
import { PublishQueryStatusEnum } from './PublishQueryStatusEnum.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for updating a graphql query
*/
export class UpdateGraphqlQuery {
  'boundaryId'?: UUID;
  'name'?: string;
  'description'?: string;
  'template'?: string;
  'status'?: PublishQueryStatusEnumDef;
  'elements'?: Array<UUID> | null;
  'evidenceDefinitionIds'?: Array<UUID> | null;
  'systemFields'?: GraphqlQueryVersionSystemParameters;
  'fields'?: Array<UpdateGraphqlQueryFields>;
  'tags'?: Array<UUID>;
  'pagination'?: GraphqlQueryVersionPagination | null;
  'viewProperties'?: { [key: string]: Array<{ [key: string]: any; }>; };

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "template",
      "baseName": "template",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // PublishQueryStatusEnum
      // PublishQueryStatusEnumDef
      "type": "PublishQueryStatusEnum",
      "format": ""
    },
    {
      "name": "elements",
      "baseName": "elements",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "evidenceDefinitionIds",
      "baseName": "evidenceDefinitionIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "systemFields",
      "baseName": "systemFields",
      // false
      // GraphqlQueryVersionSystemParameters
      // GraphqlQueryVersionSystemParameters
      "type": "GraphqlQueryVersionSystemParameters",
      "format": ""
    },
    {
      "name": "fields",
      "baseName": "fields",
      // false
      // Array&lt;UpdateGraphqlQueryFields&gt;
      // Array&lt;UpdateGraphqlQueryFields&gt;
      "type": "Array<UpdateGraphqlQueryFields>",
      "format": ""
    },
    {
      "name": "tags",
      "baseName": "tags",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "pagination",
      "baseName": "pagination",
      // false
      // GraphqlQueryVersionPagination
      // GraphqlQueryVersionPagination
      "type": "GraphqlQueryVersionPagination",
      "format": ""
    },
    {
      "name": "viewProperties",
      "baseName": "viewProperties",
      // false
      // { [key: string]: Array&lt;{ [key: string]: any; }&gt;; }
      // { [key: string]: Array&lt;{ [key: string]: any; }&gt;; }
      "type": "{ [key: string]: Array<{ [key: string]: any; }>; }",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return UpdateGraphqlQuery.attributeTypeMap;
  }

  static newInstance(obj: any): UpdateGraphqlQuery {
    return ObjectSerializer.deserialize(obj, 'UpdateGraphqlQuery');
  }

  constructor(boundaryId?: UUID, name?: string, description?: string, template?: string, status?: PublishQueryStatusEnumDef, elements?: Array<UUID>, evidenceDefinitionIds?: Array<UUID>, systemFields?: GraphqlQueryVersionSystemParameters, fields?: Array<UpdateGraphqlQueryFields>, tags?: Array<UUID>, pagination?: GraphqlQueryVersionPagination, viewProperties?: { [key: string]: Array<{ [key: string]: any; }>; }) {
    this.boundaryId = boundaryId;
    this.name = name;
    this.description = description;
    this.template = template;
    this.status = status;
    this.elements = elements;
    this.evidenceDefinitionIds = evidenceDefinitionIds;
    this.systemFields = systemFields;
    this.fields = fields;
    this.tags = tags;
    this.pagination = pagination;
    this.viewProperties = viewProperties;
  }
}

