/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Update a Boundary Query Alert Configuration.
*/
export class UpdateBoundaryAlertBot {
  /**
  * The name of the boundary query alert configuration. Leave unset or set to null to not update this field
  */
  'name'?: string | null;
  /**
  * Whether to enabled or disable this configuration. this will enable/disable any cron/trigger behind the hood. Leave unset or set to null to not update this field
  */
  'enabled'?: boolean | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "enabled",
      "baseName": "enabled",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return UpdateBoundaryAlertBot.attributeTypeMap;
  }

  static newInstance(obj: any): UpdateBoundaryAlertBot {
    return ObjectSerializer.deserialize(obj, 'UpdateBoundaryAlertBot');
  }

  constructor(name?: string, enabled?: boolean) {
    this.name = name;
    this.enabled = enabled;
  }
}

