/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AssessmentResultTypeEnum } from './AssessmentResultTypeEnum.js';
import { AssessmentResultTypeEnumDef } from './AssessmentResultTypeEnum.js';
import { AssessmentResultRatingEnum } from './AssessmentResultRatingEnum.js';
import { AssessmentResultRatingEnumDef } from './AssessmentResultRatingEnum.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Update Assessment Result
*/
export class UpdateAssessmentResult {
  'type': AssessmentResultTypeEnumDef;
  'details': string;
  'rating'?: AssessmentResultRatingEnumDef;
  'justification'?: string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "type",
      "baseName": "type",
      // false
      // AssessmentResultTypeEnum
      // AssessmentResultTypeEnumDef
      "type": "AssessmentResultTypeEnum",
      "format": ""
    },
    {
      "name": "details",
      "baseName": "details",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "rating",
      "baseName": "rating",
      // false
      // AssessmentResultRatingEnum
      // AssessmentResultRatingEnumDef
      "type": "AssessmentResultRatingEnum",
      "format": ""
    },
    {
      "name": "justification",
      "baseName": "justification",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return UpdateAssessmentResult.attributeTypeMap;
  }

  static newInstance(obj: any): UpdateAssessmentResult {
    return ObjectSerializer.deserialize(obj, 'UpdateAssessmentResult');
  }

  constructor(type: AssessmentResultTypeEnumDef, details: string, rating?: AssessmentResultRatingEnumDef, justification?: string) {
    this.type = type;
    this.details = details;
    this.rating = rating;
    this.justification = justification;
  }
}

