/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CloudControlMatrixEnumDef } from './CloudControlMatrixEnum.js';
import { CloudControlMatrixEnum } from './CloudControlMatrixEnum.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Request body for updating a boundary team scf control
*/
export class UpdateBoundaryTeamScfControl {
  'performedMaturity': CloudControlMatrixEnumDef;
  'desiredMaturity': CloudControlMatrixEnumDef;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "performedMaturity",
      "baseName": "performedMaturity",
      // false
      // CloudControlMatrixEnum
      // CloudControlMatrixEnumDef
      "type": "CloudControlMatrixEnum",
      "format": ""
    },
    {
      "name": "desiredMaturity",
      "baseName": "desiredMaturity",
      // false
      // CloudControlMatrixEnum
      // CloudControlMatrixEnumDef
      "type": "CloudControlMatrixEnum",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return UpdateBoundaryTeamScfControl.attributeTypeMap;
  }

  static newInstance(obj: any): UpdateBoundaryTeamScfControl {
    return ObjectSerializer.deserialize(obj, 'UpdateBoundaryTeamScfControl');
  }

  constructor(performedMaturity: CloudControlMatrixEnumDef, desiredMaturity: CloudControlMatrixEnumDef, ) {
    this.performedMaturity = performedMaturity;
    this.desiredMaturity = desiredMaturity;
  }
}

