/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError, UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for updating the assignee of an evidence assessment
*/
export class UpdateAuditEvidenceAssessmentAssignee {
  /**
  * Array of evidence assessment ids to update the assignee
  */
  'evidenceAssessmentIds': Array<UUID>;
  'action': UpdateAuditEvidenceAssessmentAssignee.ActionEnumDef;
  'assignee'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "evidenceAssessmentIds",
      "baseName": "evidenceAssessmentIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "action",
      "baseName": "action",
      // true
      // UpdateAuditEvidenceAssessmentAssignee.ActionEnum
      // UpdateAuditEvidenceAssessmentAssignee.ActionEnumDef
      "type": "UpdateAuditEvidenceAssessmentAssignee.ActionEnum",
      "format": ""
    },
    {
      "name": "assignee",
      "baseName": "assignee",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return UpdateAuditEvidenceAssessmentAssignee.attributeTypeMap;
  }

  static newInstance(obj: any): UpdateAuditEvidenceAssessmentAssignee {
    return ObjectSerializer.deserialize(obj, 'UpdateAuditEvidenceAssessmentAssignee');
  }

  constructor(evidenceAssessmentIds: Array<UUID>, action: UpdateAuditEvidenceAssessmentAssignee.ActionEnumDef, assignee?: UUID) {
    this.evidenceAssessmentIds = evidenceAssessmentIds;
    this.action = action;
    this.assignee = assignee;
  }
}

export namespace UpdateAuditEvidenceAssessmentAssignee {
  export const ActionEnum = {
    /**  */
    Assign: EnumValue.instance('UpdateAuditEvidenceAssessmentAssignee.ActionEnum', 'Assign', 'assign'),
    /**  */
    Unassign: EnumValue.instance('UpdateAuditEvidenceAssessmentAssignee.ActionEnum', 'Unassign', 'unassign'),

    from(val: string | number): EnumValue {
      if (ActionEnum[val]) {
        return ActionEnum[val];
      }
      const byValue = ActionEnum.values.find((v) => v.value === val);
      if (byValue) {
        return byValue;
      }
      throw new IllegalArgumentError(`${val} is not a valid ActionEnum`);
    },

    get values(): EnumValue[] {
      return Object
        .keys(ActionEnum)
        .filter((k) => k !== 'values' && k !== 'from')
        .map((t) => ActionEnum[t]);
    }
  } as const;

  export type ActionEnumDef = typeof ActionEnum[keyof typeof ActionEnum];
}
