/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ObjectSerializer, RequestFile } from './index.js';

export class VersionByObjectDataRequiredProperties {
  'id': string;
  'name': string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return VersionByObjectDataRequiredProperties.attributeTypeMap;
  }

  static newInstance(obj: any): VersionByObjectDataRequiredProperties {
    return ObjectSerializer.deserialize(obj, 'VersionByObjectDataRequiredProperties');
  }

  constructor(id: string, name: string, ) {
    this.id = id;
    this.name = name;
  }
}

