/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { SeverityDef } from './Severity.js';
import { Severity } from './Severity.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class AlertSummaryBySeverity {
  'severity'?: SeverityDef;
  /**
  * count of distinct alerts raised against parents of this resource
  */
  'total'?: number;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "severity",
      "baseName": "severity",
      // false
      // Severity
      // SeverityDef
      "type": "Severity",
      "format": ""
    },
    {
      "name": "total",
      "baseName": "total",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return AlertSummaryBySeverity.attributeTypeMap;
  }

  static newInstance(obj: any): AlertSummaryBySeverity {
    return ObjectSerializer.deserialize(obj, 'AlertSummaryBySeverity');
  }

  constructor(severity?: SeverityDef, total?: number) {
    this.severity = severity;
    this.total = total;
  }
}

