/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* All possible statuses for orders (regardless of type).
*/
export const AllOrderStatus = {
  /** The order has been received and is in the backlog */
  Backlog: EnumValue.instance('AllOrderStatus', 'Backlog', 'backlog'),
  /** The order is blocked */
  Blocked: EnumValue.instance('AllOrderStatus', 'Blocked', 'blocked'),
  /** The order is complete */
  Complete: EnumValue.instance('AllOrderStatus', 'Complete', 'complete'),
  /** The order has been rejected */
  Rejected: EnumValue.instance('AllOrderStatus', 'Rejected', 'rejected'),
  /** The order has been cancelled */
  Cancelled: EnumValue.instance('AllOrderStatus', 'Cancelled', 'cancelled'),
  /** The order is pending full Business Analysis */
  AnalysisBacklog: EnumValue.instance('AllOrderStatus', 'AnalysisBacklog', 'analysis_backlog'),
  /** The order has entered analysis */
  Analysis: EnumValue.instance('AllOrderStatus', 'Analysis', 'analysis'),
  /** The order has been analyzed and business requirements are known */
  AnalysisComplete: EnumValue.instance('AllOrderStatus', 'AnalysisComplete', 'analysis_complete'),
  /** The order is pending Lab Requirements Analysis */
  LabBacklog: EnumValue.instance('AllOrderStatus', 'LabBacklog', 'lab_backlog'),
  /** The order has entered lab analysis */
  LabAnalysis: EnumValue.instance('AllOrderStatus', 'LabAnalysis', 'lab_analysis'),
  /** A lab for this order is being provisioned */
  LabImplementation: EnumValue.instance('AllOrderStatus', 'LabImplementation', 'lab_implementation'),
  /** The order is pending development */
  DevBacklog: EnumValue.instance('AllOrderStatus', 'DevBacklog', 'dev_backlog'),
  /** Cataloging and Prototyping work has started for this order */
  Cataloging: EnumValue.instance('AllOrderStatus', 'Cataloging', 'cataloging'),
  /** The order is in progress */
  InProgress: EnumValue.instance('AllOrderStatus', 'InProgress', 'in_progress'),

  from(val: string | number): EnumValue {
    if (AllOrderStatus[val]) {
      return AllOrderStatus[val];
    }
    const byValue = AllOrderStatus.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid AllOrderStatus`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(AllOrderStatus)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => AllOrderStatus[t]);
  }
} as const;

export type AllOrderStatusDef = typeof AllOrderStatus[keyof typeof AllOrderStatus];
