/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ModerationStatusDef } from './ModerationStatus.js';
import { ModerationStatus } from './ModerationStatus.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* The product that is being cataloged
*/
export class CatalogingOrderChangeEventAllOfProduct {
  /**
  * The ordered product id.
  */
  'id'?: UUID;
  /**
  * The ordered product name.
  */
  'name'?: string;
  /**
  * The ordered product package name.
  */
  'packageName'?: string;
  'status'?: ModerationStatusDef;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "packageName",
      "baseName": "packageName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // ModerationStatus
      // ModerationStatusDef
      "type": "ModerationStatus",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return CatalogingOrderChangeEventAllOfProduct.attributeTypeMap;
  }

  static newInstance(obj: any): CatalogingOrderChangeEventAllOfProduct {
    return ObjectSerializer.deserialize(obj, 'CatalogingOrderChangeEventAllOfProduct');
  }

  constructor(id?: UUID, name?: string, packageName?: string, status?: ModerationStatusDef) {
    this.id = id;
    this.name = name;
    this.packageName = packageName;
    this.status = status;
  }
}

