/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ObjectSerializer, RequestFile } from './index.js';

export class CatalogSummaryReportOperations {
  /**
  * the total number of currently active operations available in latest versions of modules. This is not affected by time filters
  */
  'latest'?: number;
  /**
  * the number of orderable operations that were created within the time frame
  */
  'orderable'?: number;
  /**
  * the number of ordered operations that were created within the time frame
  */
  'ordered'?: number;
  /**
  * the number of active operations that were created within the time frame
  */
  'active'?: number;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "latest",
      "baseName": "latest",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "orderable",
      "baseName": "orderable",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "ordered",
      "baseName": "ordered",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    },
    {
      "name": "active",
      "baseName": "active",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return CatalogSummaryReportOperations.attributeTypeMap;
  }

  static newInstance(obj: any): CatalogSummaryReportOperations {
    return ObjectSerializer.deserialize(obj, 'CatalogSummaryReportOperations');
  }

  constructor(latest?: number, orderable?: number, ordered?: number, active?: number) {
    this.latest = latest;
    this.orderable = orderable;
    this.ordered = ordered;
    this.active = active;
  }
}

