/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { OrderType } from './OrderType.js';
import { OrderTypeDef } from './OrderType.js';
import { CreateCatalogingOrderAllOf } from './CreateCatalogingOrderAllOf.js';
import { Priority } from './Priority.js';
import { CreateOrder } from './CreateOrder.js';
import { PriorityDef } from './Priority.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* A request to catalog an existing product. The product must be in the `verified` status in order to be elligible for ordering.
*/
export class CreateCatalogingOrder extends CreateOrder {
  /**
  * The id of a the product we want to be cataloged.
  */
  'productId': UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "productId",
      "baseName": "productId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return super.getAttributeTypeMap().concat(CreateCatalogingOrder.attributeTypeMap);
  }

  static newInstance(obj: any): CreateCatalogingOrder {
    return ObjectSerializer.deserialize(obj, 'CreateCatalogingOrder');
  }

  constructor(type: OrderTypeDef, name: string, productId: UUID, priority?: PriorityDef, description?: string, context?: { [key: string]: any; }, ) {
    super(type, name, priority, description, context);
    this.productId = productId;
  }
}

