/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ModuleConnectionProfile } from './ModuleConnectionProfile.js';
import { ModuleRepository } from './ModuleRepository.js';
import { Semver, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* A report containing information about a given module and module version.
*/
export class ModuleDependencyReport {
  /**
  * The ID to use for the module
  */
  'moduleId': UUID;
  /**
  * The name of the module
  */
  'name': string;
  /**
  * The name of the publisher of this module
  */
  'publisher': string;
  /**
  * A unique, human-friendly identifier for this module
  */
  'key': string;
  /**
  * The ID to use for the module version
  */
  'moduleVersionId': UUID;
  /**
  * The module version
  */
  'version': Semver;
  'repository': ModuleRepository;
  /**
  * Whether the module support files service
  */
  'fileSupport': boolean;
  /**
  * Whether the module support data producing
  */
  'dataSupport': boolean;
  /**
  * A long description of the module
  */
  'description'?: string;
  /**
  * A URI for a logo for this module
  */
  'imageUrl'?: URL;
  'connectionProfile'?: ModuleConnectionProfile;
  /**
  * URL to release notes for this version
  */
  'releaseNotes'?: URL;
  /**
  * URL to a knowledge base for this version
  */
  'knowledgeBase'?: URL;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "moduleId",
      "baseName": "moduleId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "publisher",
      "baseName": "publisher",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "key",
      "baseName": "key",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "moduleVersionId",
      "baseName": "moduleVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "version",
      "baseName": "version",
      // false
      // Semver
      // Semver
      "type": "Semver",
      "format": "semver"
    },
    {
      "name": "repository",
      "baseName": "repository",
      // false
      // ModuleRepository
      // ModuleRepository
      "type": "ModuleRepository",
      "format": ""
    },
    {
      "name": "fileSupport",
      "baseName": "fileSupport",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "dataSupport",
      "baseName": "dataSupport",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "connectionProfile",
      "baseName": "connectionProfile",
      // false
      // ModuleConnectionProfile
      // ModuleConnectionProfile
      "type": "ModuleConnectionProfile",
      "format": ""
    },
    {
      "name": "releaseNotes",
      "baseName": "releaseNotes",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "knowledgeBase",
      "baseName": "knowledgeBase",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    }  ];

  static getAttributeTypeMap() {
    return ModuleDependencyReport.attributeTypeMap;
  }

  static newInstance(obj: any): ModuleDependencyReport {
    return ObjectSerializer.deserialize(obj, 'ModuleDependencyReport');
  }

  constructor(moduleId: UUID, name: string, publisher: string, key: string, moduleVersionId: UUID, version: Semver, repository: ModuleRepository, fileSupport: boolean, dataSupport: boolean, description?: string, imageUrl?: URL, connectionProfile?: ModuleConnectionProfile, releaseNotes?: URL, knowledgeBase?: URL) {
    this.moduleId = moduleId;
    this.name = name;
    this.publisher = publisher;
    this.key = key;
    this.moduleVersionId = moduleVersionId;
    this.version = version;
    this.repository = repository;
    this.fileSupport = fileSupport;
    this.dataSupport = dataSupport;
    this.description = description;
    this.imageUrl = imageUrl;
    this.connectionProfile = connectionProfile;
    this.releaseNotes = releaseNotes;
    this.knowledgeBase = knowledgeBase;
  }
}

