/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { CatalogPublishStatusEnumDef } from './CatalogPublishStatusEnum.js';
import { ResourceTypeEnum } from './ResourceTypeEnum.js';
import { ResourceTypeEnumDef } from './ResourceTypeEnum.js';
import { StoreProductAllOf } from './StoreProductAllOf.js';
import { CatalogPublishStatusEnum } from './CatalogPublishStatusEnum.js';
import { Product } from './Product.js';
import { ProductVersion } from './ProductVersion.js';
import { Tag } from './Tag.js';
import { Nmtoken, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class StoreProduct {
  /**
  * Unique identifier
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  'status': CatalogPublishStatusEnumDef;
  'latestVersionId': UUID;
  'latestVersion': ProductVersion;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  /**
  * An external URL to this resource in the outside world
  */
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  /**
  * A resource id which acts as a boundary/container for this resource.
  */
  'boundaryId'?: UUID;
  'packageCode'?: string;
  'artifactId'?: UUID;
  'parentType'?: ResourceTypeEnumDef;
  /**
  * the vendor code
  */
  'vendorCode'?: string;
  /**
  * the suite code
  */
  'suiteCode'?: string;
  /**
  * A unique product package name of the form vendorCode.suiteCode.productCode.
  */
  'packageName'?: string;
  'tags'?: Array<Tag>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // CatalogPublishStatusEnum
      // CatalogPublishStatusEnumDef
      "type": "CatalogPublishStatusEnum",
      "format": ""
    },
    {
      "name": "latestVersionId",
      "baseName": "latestVersionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "latestVersion",
      "baseName": "latestVersion",
      // false
      // ProductVersion
      // ProductVersion
      "type": "ProductVersion",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "packageCode",
      "baseName": "packageCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "artifactId",
      "baseName": "artifactId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "parentType",
      "baseName": "parentType",
      // false
      // ResourceTypeEnum
      // ResourceTypeEnumDef
      "type": "ResourceTypeEnum",
      "format": ""
    },
    {
      "name": "vendorCode",
      "baseName": "vendorCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "suiteCode",
      "baseName": "suiteCode",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "packageName",
      "baseName": "packageName",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "tags",
      "baseName": "tags",
      // false
      // Array&lt;Tag&gt;
      // Array&lt;Tag&gt;
      "type": "Array<Tag>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return StoreProduct.attributeTypeMap;
  }

  static newInstance(obj: any): StoreProduct {
    return ObjectSerializer.deserialize(obj, 'StoreProduct');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, status: CatalogPublishStatusEnumDef, latestVersionId: UUID, latestVersion: ProductVersion, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, boundaryId?: UUID, packageCode?: string, artifactId?: UUID, parentType?: ResourceTypeEnumDef, vendorCode?: string, suiteCode?: string, packageName?: string, tags?: Array<Tag>) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.status = status;
    this.latestVersionId = latestVersionId;
    this.latestVersion = latestVersion;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.boundaryId = boundaryId;
    this.packageCode = packageCode;
    this.artifactId = artifactId;
    this.parentType = parentType;
    this.vendorCode = vendorCode;
    this.suiteCode = suiteCode;
    this.packageName = packageName;
    this.tags = tags;
  }
}

