/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Payload to allow adding a tag to a Resource by either ID or name.
*/
export class AddTag {
  /**
  * The ID of the tag
  */
  'id': UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return AddTag.attributeTypeMap;
  }

  static newInstance(obj: any): AddTag {
    return ObjectSerializer.deserialize(obj, 'AddTag');
  }

  constructor(id: UUID, ) {
    this.id = id;
  }
}

