/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { SecretMode } from './SecretMode.js';
import { SecretModeDef } from './SecretMode.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class CreateSecret {
  /**
  * The name of the secret
  */
  'name': string;
  /**
  * The ID of the `ConnectionProfile` this secret adheres to. This ID comes from Hub Store
  */
  'connectionProfileId': UUID;
  /**
  * Long description for the secret
  */
  'description'?: string;
  'boundaryId'?: UUID;
  /**
  * The secret object containing keys matching the `ConnectionProfile` and values which are secret nodes paths.
  */
  'profile'?: { [key: string]: any; };
  'mode'?: SecretModeDef;
  /**
  * Flag indicating whether or not this Secret can be used by other Connections
  */
  'shared'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "connectionProfileId",
      "baseName": "connectionProfileId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "profile",
      "baseName": "profile",
      // false
      // { [key: string]: any; }
      // { [key: string]: any; }
      "type": "{ [key: string]: any; }",
      "format": ""
    },
    {
      "name": "mode",
      "baseName": "mode",
      // false
      // SecretMode
      // SecretModeDef
      "type": "SecretMode",
      "format": ""
    },
    {
      "name": "shared",
      "baseName": "shared",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return CreateSecret.attributeTypeMap;
  }

  static newInstance(obj: any): CreateSecret {
    return ObjectSerializer.deserialize(obj, 'CreateSecret');
  }

  constructor(name: string, connectionProfileId: UUID, description?: string, boundaryId?: UUID, profile?: { [key: string]: any; }, mode?: SecretModeDef, shared?: boolean) {
    this.name = name;
    this.connectionProfileId = connectionProfileId;
    this.description = description;
    this.boundaryId = boundaryId;
    this.profile = profile;
    this.mode = mode;
    this.shared = shared;
  }
}

