/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { InvalidInputErrorAllOf } from './InvalidInputErrorAllOf.js';
import { ErrorModelBase } from './ErrorModelBase.js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Error indicating the given input was invalid
*/
export class InvalidInputError {
  /**
  * A unique message key for this error. This is used both for discrimination and i18n
  */
  'key': string;
  /**
  * The error message. This may contain substitutions of the form `{key}` where `key` maps to a key in the `args` list.
  */
  'template': string;
  /**
  * Timestamp when this error was generated
  */
  'timestamp': Date;
  /**
  * An HTTP status code to use for this error when transmitting it over HTTP
  */
  'statusCode': number;
  /**
  * The type of object the value is invalid for
  */
  'type': string;
  /**
  * The invalid value provided
  */
  'value': string;
  /**
  * The stack trace, if available, for this error.
  */
  'stack'?: string;
  /**
  * Examples of correct values
  */
  'examples'?: Array<string>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "key",
      "baseName": "key",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "template",
      "baseName": "template",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "timestamp",
      "baseName": "timestamp",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "statusCode",
      "baseName": "statusCode",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "value",
      "baseName": "value",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "stack",
      "baseName": "stack",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "examples",
      "baseName": "examples",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return InvalidInputError.attributeTypeMap;
  }

  static newInstance(obj: any): InvalidInputError {
    return ObjectSerializer.deserialize(obj, 'InvalidInputError');
  }

  constructor(key: string, template: string, timestamp: Date, statusCode: number, type: string, value: string, stack?: string, examples?: Array<string>) {
    this.key = key;
    this.template = template;
    this.timestamp = timestamp;
    this.statusCode = statusCode;
    this.type = type;
    this.value = value;
    this.stack = stack;
    this.examples = examples;
  }
}

