/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { RegistrationStatus } from './RegistrationStatus.js';
import { RegistrationStatusDef } from './RegistrationStatus.js';
import { HubTagView } from './HubTagView.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class RegistrationExtendedAllOf {
  /**
  * Number of nodes claimed using this registration
  */
  'nodeCount': number;
  'status': RegistrationStatusDef;
  'tags': Array<HubTagView>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "nodeCount",
      "baseName": "nodeCount",
      // false
      // number
      // number
      "type": "number",
      "format": "int32"
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // RegistrationStatus
      // RegistrationStatusDef
      "type": "RegistrationStatus",
      "format": ""
    },
    {
      "name": "tags",
      "baseName": "tags",
      // false
      // Array&lt;HubTagView&gt;
      // Array&lt;HubTagView&gt;
      "type": "Array<HubTagView>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return RegistrationExtendedAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): RegistrationExtendedAllOf {
    return ObjectSerializer.deserialize(obj, 'RegistrationExtendedAllOf');
  }

  constructor(nodeCount: number, status: RegistrationStatusDef, tags: Array<HubTagView>, ) {
    this.nodeCount = nodeCount;
    this.status = status;
    this.tags = tags;
  }
}

