/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class ResultsColumnOptionsFilterCustomStub {
  'id': UUID;
  'name': string;
  'customFields'?: { [key: string]: any; };

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "customFields",
      "baseName": "customFields",
      // false
      // { [key: string]: any; }
      // { [key: string]: any; }
      "type": "{ [key: string]: any; }",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return ResultsColumnOptionsFilterCustomStub.attributeTypeMap;
  }

  static newInstance(obj: any): ResultsColumnOptionsFilterCustomStub {
    return ObjectSerializer.deserialize(obj, 'ResultsColumnOptionsFilterCustomStub');
  }

  constructor(id: UUID, name: string, customFields?: { [key: string]: any; }) {
    this.id = id;
    this.name = name;
    this.customFields = customFields;
  }
}

