/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { SchemasRoleStatus } from './SchemasRoleStatus.js';
import { SchemasRoleTypeEnumDef } from './SchemasRoleTypeEnum.js';
import { SchemasRoleTypeEnum } from './SchemasRoleTypeEnum.js';
import { SchemasRoleStatusDef } from './SchemasRoleStatus.js';
import { IdNameOwnerIdTypeImageUrlObject } from './IdNameOwnerIdTypeImageUrlObject.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class RoleViewAllOf {
  'roleType': SchemasRoleTypeEnumDef;
  'boundaryIds': Array<UUID>;
  'principals': Array<IdNameOwnerIdTypeImageUrlObject>;
  'status'?: SchemasRoleStatusDef;
  /**
  * The total number of principals in this role
  */
  'principalsCount'?: number;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "roleType",
      "baseName": "roleType",
      // false
      // SchemasRoleTypeEnum
      // SchemasRoleTypeEnumDef
      "type": "SchemasRoleTypeEnum",
      "format": ""
    },
    {
      "name": "boundaryIds",
      "baseName": "boundaryIds",
      // false
      // Array&lt;UUID&gt;
      // Array&lt;UUID&gt;
      "type": "Array<UUID>",
      "format": "uuid"
    },
    {
      "name": "principals",
      "baseName": "principals",
      // false
      // Array&lt;IdNameOwnerIdTypeImageUrlObject&gt;
      // Array&lt;IdNameOwnerIdTypeImageUrlObject&gt;
      "type": "Array<IdNameOwnerIdTypeImageUrlObject>",
      "format": ""
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // SchemasRoleStatus
      // SchemasRoleStatusDef
      "type": "SchemasRoleStatus",
      "format": ""
    },
    {
      "name": "principalsCount",
      "baseName": "principalsCount",
      // false
      // number
      // number
      "type": "number",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return RoleViewAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): RoleViewAllOf {
    return ObjectSerializer.deserialize(obj, 'RoleViewAllOf');
  }

  constructor(roleType: SchemasRoleTypeEnumDef, boundaryIds: Array<UUID>, principals: Array<IdNameOwnerIdTypeImageUrlObject>, status?: SchemasRoleStatusDef, principalsCount?: number) {
    this.roleType = roleType;
    this.boundaryIds = boundaryIds;
    this.principals = principals;
    this.status = status;
    this.principalsCount = principalsCount;
  }
}

