/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { Nmtoken } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class RoleAccessRuleSearchOptions {
  'resourceTypes'?: Array<Nmtoken>;
  'permissions'?: Array<Nmtoken>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "resourceTypes",
      "baseName": "resourceTypes",
      // false
      // Array&lt;Nmtoken&gt;
      // Array&lt;Nmtoken&gt;
      "type": "Array<Nmtoken>",
      "format": "nmtoken"
    },
    {
      "name": "permissions",
      "baseName": "permissions",
      // false
      // Array&lt;Nmtoken&gt;
      // Array&lt;Nmtoken&gt;
      "type": "Array<Nmtoken>",
      "format": "nmtoken"
    }  ];

  static getAttributeTypeMap() {
    return RoleAccessRuleSearchOptions.attributeTypeMap;
  }

  static newInstance(obj: any): RoleAccessRuleSearchOptions {
    return ObjectSerializer.deserialize(obj, 'RoleAccessRuleSearchOptions');
  }

  constructor(resourceTypes?: Array<Nmtoken>, permissions?: Array<Nmtoken>) {
    this.resourceTypes = resourceTypes;
    this.permissions = permissions;
  }
}

