/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { Nmtoken, UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* A generic tag for an object
*/
export class SchemasTag {
  /**
  * ID for this tag
  */
  'id': UUID;
  /**
  * Name of this tag
  */
  'name': string;
  /**
  * The ID of the owner of this Tag
  */
  'ownerId': UUID;
  /**
  * Type of this tag
  */
  'type': Nmtoken;
  /**
  * A longer description of the tag
  */
  'description'?: string;
  'created'?: Date | null;
  'deleted'?: Date | null;
  'updated'?: Date | null;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    }  ];

  static getAttributeTypeMap() {
    return SchemasTag.attributeTypeMap;
  }

  static newInstance(obj: any): SchemasTag {
    return ObjectSerializer.deserialize(obj, 'SchemasTag');
  }

  constructor(id: UUID, name: string, ownerId: UUID, type: Nmtoken, description?: string, created?: Date, deleted?: Date, updated?: Date) {
    this.id = id;
    this.name = name;
    this.ownerId = ownerId;
    this.type = type;
    this.description = description;
    this.created = created;
    this.deleted = deleted;
    this.updated = updated;
  }
}

