/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { GroupAllOf } from './GroupAllOf.js';
import { BoundaryGroupTypeDef } from './BoundaryGroupType.js';
import { SchemasPrincipalStatus } from './SchemasPrincipalStatus.js';
import { SchemasPrincipalTypeDef } from './SchemasPrincipalType.js';
import { SchemasPrincipalType } from './SchemasPrincipalType.js';
import { SchemasPrincipalOriginDef } from './SchemasPrincipalOrigin.js';
import { GroupTypeDef } from './GroupType.js';
import { GroupType } from './GroupType.js';
import { SchemasPrincipal } from './SchemasPrincipal.js';
import { BoundaryGroupType } from './BoundaryGroupType.js';
import { SchemasPrincipalStatusDef } from './SchemasPrincipalStatus.js';
import { SchemasPrincipalOrigin } from './SchemasPrincipalOrigin.js';
import { UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Schema for a Hydra Group
*/
export class SchemasGroup extends SchemasPrincipal {
  'groupType': GroupTypeDef;
  'boundaryId'?: UUID;
  'boundaryGroupType'?: BoundaryGroupTypeDef;
  /**
  * URL to an avatar for the given Group
  */
  'avatarUrl'?: URL;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "groupType",
      "baseName": "groupType",
      // false
      // GroupType
      // GroupTypeDef
      "type": "GroupType",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "boundaryGroupType",
      "baseName": "boundaryGroupType",
      // false
      // BoundaryGroupType
      // BoundaryGroupTypeDef
      "type": "BoundaryGroupType",
      "format": ""
    },
    {
      "name": "avatarUrl",
      "baseName": "avatarUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    }  ];

  static getAttributeTypeMap() {
    return super.getAttributeTypeMap().concat(SchemasGroup.attributeTypeMap);
  }

  static newInstance(obj: any): SchemasGroup {
    return ObjectSerializer.deserialize(obj, 'SchemasGroup');
  }

  constructor(id: UUID, ownerId: UUID, name: string, type: SchemasPrincipalTypeDef, status: SchemasPrincipalStatusDef, enabled: boolean, origin: SchemasPrincipalOriginDef, groupType: GroupTypeDef, created?: Date, deleted?: Date, updated?: Date, externalId?: string, boundaryId?: UUID, boundaryGroupType?: BoundaryGroupTypeDef, avatarUrl?: URL) {
    super(id, ownerId, name, type, status, enabled, origin, created, deleted, updated, externalId);
    this.groupType = groupType;
    this.boundaryId = boundaryId;
    this.boundaryGroupType = boundaryGroupType;
    this.avatarUrl = avatarUrl;
  }
}

