/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { ConnectionDegradedReason } from './ConnectionDegradedReason.js';
import { AdminStatus } from './AdminStatus.js';
import { ConnectionOperationalStatusDef } from './ConnectionOperationalStatus.js';
import { ConnectionOperationalStatus } from './ConnectionOperationalStatus.js';
import { ScopeInfo } from './ScopeInfo.js';
import { ConnectionDegradedReasonDef } from './ConnectionDegradedReason.js';
import { NodeView } from './NodeView.js';
import { ConnectionDownReason } from './ConnectionDownReason.js';
import { HubTagView } from './HubTagView.js';
import { AdminStatusDef } from './AdminStatus.js';
import { Secret } from './Secret.js';
import { Scope } from './Scope.js';
import { ConnectionDownReasonDef } from './ConnectionDownReason.js';
import { ScopeViewAllOf } from './ScopeViewAllOf.js';
import { ConnectionView } from './ConnectionView.js';
import { DeploymentView } from './DeploymentView.js';
import { Nmtoken, UUID, URL } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class ScopeView {
  /**
  * ID of the Deployment
  */
  'id': UUID;
  /**
  * Short name
  */
  'name': string;
  /**
  * The type of resource this is
  */
  'type': Nmtoken;
  /**
  * The owner of this resource. This is a reference to a principal.
  */
  'ownerId': UUID;
  /**
  * The timestamp when this resource was created
  */
  'created': Date;
  /**
  * The timestamp when this resource was last updated
  */
  'updated': Date;
  /**
  * The ID of the deployment this connection belongs to
  */
  'deploymentId': UUID;
  /**
  * The ID of the `Connection` which this `Scope` uses
  */
  'connectionId': UUID;
  'status': ConnectionOperationalStatusDef;
  'adminStatus': AdminStatusDef;
  /**
  * A long description
  */
  'description'?: string;
  /**
  * The parent of this resource. This is a reference to another Resource.
  */
  'parentId'?: UUID;
  /**
  * Timestamp when the link was deleted, if it has been soft-deleted
  */
  'deleted'?: Date;
  /**
  * A URL to an image representing this resource
  */
  'imageUrl'?: URL;
  /**
  * An external URL to this resource in the outside world
  */
  'url'?: URL;
  /**
  * Alternate names by which this resource may be known
  */
  'aliases'?: Array<string>;
  /**
  * A resource id which acts as a boundary/container for this resource.
  */
  'boundaryId'?: UUID;
  /**
  * Additional parameters for the connection profile
  */
  'params'?: { [key: string]: string; };
  /**
  * True if this is the default scope
  */
  'isDefault'?: boolean;
  /**
  * A message corresponding to the last status update, if any.
  */
  'statusMessage'?: string;
  /**
  * Last time this deployment was used
  */
  'lastUse'?: Date;
  /**
  * Whether or not the last use was successful
  */
  'lastUseSuccess'?: boolean;
  'downReason'?: Array<ConnectionDownReasonDef>;
  'degradedReason'?: Array<ConnectionDegradedReasonDef>;
  'connectionProfile'?: { [key: string]: string; };
  'connectionProfileId'?: UUID;
  'deployment'?: DeploymentView;
  'connection'?: ConnectionView;
  'secret'?: Secret;
  'node'?: NodeView;
  /**
  * The ID of the node this Scope is a part of
  */
  'nodeId'?: UUID;
  /**
  * All tags applied to this Scope
  */
  'tags'?: Array<HubTagView>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "type",
      "baseName": "type",
      // false
      // Nmtoken
      // Nmtoken
      "type": "Nmtoken",
      "format": "nmtoken"
    },
    {
      "name": "ownerId",
      "baseName": "ownerId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "created",
      "baseName": "created",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "updated",
      "baseName": "updated",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "deploymentId",
      "baseName": "deploymentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "connectionId",
      "baseName": "connectionId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "status",
      "baseName": "status",
      // false
      // ConnectionOperationalStatus
      // ConnectionOperationalStatusDef
      "type": "ConnectionOperationalStatus",
      "format": ""
    },
    {
      "name": "adminStatus",
      "baseName": "adminStatus",
      // false
      // AdminStatus
      // AdminStatusDef
      "type": "AdminStatus",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "parentId",
      "baseName": "parentId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deleted",
      "baseName": "deleted",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "imageUrl",
      "baseName": "imageUrl",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "url",
      "baseName": "url",
      // false
      // URL
      // URL
      "type": "URL",
      "format": "url"
    },
    {
      "name": "aliases",
      "baseName": "aliases",
      // false
      // Array&lt;string&gt;
      // Array&lt;string&gt;
      "type": "Array<string>",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "params",
      "baseName": "params",
      // false
      // { [key: string]: string; }
      // { [key: string]: string; }
      "type": "{ [key: string]: string; }",
      "format": ""
    },
    {
      "name": "isDefault",
      "baseName": "isDefault",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "statusMessage",
      "baseName": "statusMessage",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "lastUse",
      "baseName": "lastUse",
      // false
      // Date
      // Date
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "lastUseSuccess",
      "baseName": "lastUseSuccess",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "downReason",
      "baseName": "downReason",
      // false
      // Array&lt;ConnectionDownReason&gt;
      // Array&lt;ConnectionDownReasonDef&gt;
      "type": "Array<ConnectionDownReason>",
      "format": ""
    },
    {
      "name": "degradedReason",
      "baseName": "degradedReason",
      // false
      // Array&lt;ConnectionDegradedReason&gt;
      // Array&lt;ConnectionDegradedReasonDef&gt;
      "type": "Array<ConnectionDegradedReason>",
      "format": ""
    },
    {
      "name": "connectionProfile",
      "baseName": "connectionProfile",
      // false
      // { [key: string]: string; }
      // { [key: string]: string; }
      "type": "{ [key: string]: string; }",
      "format": ""
    },
    {
      "name": "connectionProfileId",
      "baseName": "connectionProfileId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deployment",
      "baseName": "deployment",
      // false
      // DeploymentView
      // DeploymentView
      "type": "DeploymentView",
      "format": ""
    },
    {
      "name": "connection",
      "baseName": "connection",
      // false
      // ConnectionView
      // ConnectionView
      "type": "ConnectionView",
      "format": ""
    },
    {
      "name": "secret",
      "baseName": "secret",
      // false
      // Secret
      // Secret
      "type": "Secret",
      "format": ""
    },
    {
      "name": "node",
      "baseName": "node",
      // false
      // NodeView
      // NodeView
      "type": "NodeView",
      "format": ""
    },
    {
      "name": "nodeId",
      "baseName": "nodeId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "tags",
      "baseName": "tags",
      // false
      // Array&lt;HubTagView&gt;
      // Array&lt;HubTagView&gt;
      "type": "Array<HubTagView>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return ScopeView.attributeTypeMap;
  }

  static newInstance(obj: any): ScopeView {
    return ObjectSerializer.deserialize(obj, 'ScopeView');
  }

  constructor(id: UUID, name: string, type: Nmtoken, ownerId: UUID, created: Date, updated: Date, deploymentId: UUID, connectionId: UUID, status: ConnectionOperationalStatusDef, adminStatus: AdminStatusDef, description?: string, parentId?: UUID, deleted?: Date, imageUrl?: URL, url?: URL, aliases?: Array<string>, boundaryId?: UUID, params?: { [key: string]: string; }, isDefault?: boolean, statusMessage?: string, lastUse?: Date, lastUseSuccess?: boolean, downReason?: Array<ConnectionDownReasonDef>, degradedReason?: Array<ConnectionDegradedReasonDef>, connectionProfile?: { [key: string]: string; }, connectionProfileId?: UUID, deployment?: DeploymentView, connection?: ConnectionView, secret?: Secret, node?: NodeView, nodeId?: UUID, tags?: Array<HubTagView>) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.ownerId = ownerId;
    this.created = created;
    this.updated = updated;
    this.deploymentId = deploymentId;
    this.connectionId = connectionId;
    this.status = status;
    this.adminStatus = adminStatus;
    this.description = description;
    this.parentId = parentId;
    this.deleted = deleted;
    this.imageUrl = imageUrl;
    this.url = url;
    this.aliases = aliases;
    this.boundaryId = boundaryId;
    this.params = params;
    this.isDefault = isDefault;
    this.statusMessage = statusMessage;
    this.lastUse = lastUse;
    this.lastUseSuccess = lastUseSuccess;
    this.downReason = downReason;
    this.degradedReason = degradedReason;
    this.connectionProfile = connectionProfile;
    this.connectionProfileId = connectionProfileId;
    this.deployment = deployment;
    this.connection = connection;
    this.secret = secret;
    this.node = node;
    this.nodeId = nodeId;
    this.tags = tags;
  }
}

