/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { Secret } from './Secret.js';
import { NodeView } from './NodeView.js';
import { HubTagView } from './HubTagView.js';
import { ConnectionView } from './ConnectionView.js';
import { DeploymentView } from './DeploymentView.js';
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export class ScopeViewAllOf {
  'connectionProfile'?: { [key: string]: string; };
  'connectionProfileId'?: UUID;
  'deployment'?: DeploymentView;
  'connection'?: ConnectionView;
  'secret'?: Secret;
  'node'?: NodeView;
  /**
  * The ID of the node this Scope is a part of
  */
  'nodeId'?: UUID;
  /**
  * All tags applied to this Scope
  */
  'tags'?: Array<HubTagView>;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "connectionProfile",
      "baseName": "connectionProfile",
      // false
      // { [key: string]: string; }
      // { [key: string]: string; }
      "type": "{ [key: string]: string; }",
      "format": ""
    },
    {
      "name": "connectionProfileId",
      "baseName": "connectionProfileId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "deployment",
      "baseName": "deployment",
      // false
      // DeploymentView
      // DeploymentView
      "type": "DeploymentView",
      "format": ""
    },
    {
      "name": "connection",
      "baseName": "connection",
      // false
      // ConnectionView
      // ConnectionView
      "type": "ConnectionView",
      "format": ""
    },
    {
      "name": "secret",
      "baseName": "secret",
      // false
      // Secret
      // Secret
      "type": "Secret",
      "format": ""
    },
    {
      "name": "node",
      "baseName": "node",
      // false
      // NodeView
      // NodeView
      "type": "NodeView",
      "format": ""
    },
    {
      "name": "nodeId",
      "baseName": "nodeId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "tags",
      "baseName": "tags",
      // false
      // Array&lt;HubTagView&gt;
      // Array&lt;HubTagView&gt;
      "type": "Array<HubTagView>",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return ScopeViewAllOf.attributeTypeMap;
  }

  static newInstance(obj: any): ScopeViewAllOf {
    return ObjectSerializer.deserialize(obj, 'ScopeViewAllOf');
  }

  constructor(connectionProfile?: { [key: string]: string; }, connectionProfileId?: UUID, deployment?: DeploymentView, connection?: ConnectionView, secret?: Secret, node?: NodeView, nodeId?: UUID, tags?: Array<HubTagView>) {
    this.connectionProfile = connectionProfile;
    this.connectionProfileId = connectionProfileId;
    this.deployment = deployment;
    this.connection = connection;
    this.secret = secret;
    this.node = node;
    this.nodeId = nodeId;
    this.tags = tags;
  }
}

