/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { SecretsManagerRequiredEnvVars } from './SecretsManagerRequiredEnvVars.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class SecretsManagerAuthMethods {
  'name': string;
  'requiredEnvVars': Array<SecretsManagerRequiredEnvVars>;
  'optionalEnvVars': Array<SecretsManagerRequiredEnvVars>;
  'description'?: string;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "requiredEnvVars",
      "baseName": "requiredEnvVars",
      // false
      // Array&lt;SecretsManagerRequiredEnvVars&gt;
      // Array&lt;SecretsManagerRequiredEnvVars&gt;
      "type": "Array<SecretsManagerRequiredEnvVars>",
      "format": ""
    },
    {
      "name": "optionalEnvVars",
      "baseName": "optionalEnvVars",
      // false
      // Array&lt;SecretsManagerRequiredEnvVars&gt;
      // Array&lt;SecretsManagerRequiredEnvVars&gt;
      "type": "Array<SecretsManagerRequiredEnvVars>",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return SecretsManagerAuthMethods.attributeTypeMap;
  }

  static newInstance(obj: any): SecretsManagerAuthMethods {
    return ObjectSerializer.deserialize(obj, 'SecretsManagerAuthMethods');
  }

  constructor(name: string, requiredEnvVars: Array<SecretsManagerRequiredEnvVars>, optionalEnvVars: Array<SecretsManagerRequiredEnvVars>, description?: string) {
    this.name = name;
    this.requiredEnvVars = requiredEnvVars;
    this.optionalEnvVars = optionalEnvVars;
    this.description = description;
  }
}

