/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AdminStatus } from './AdminStatus.js';
import { AdminStatusDef } from './AdminStatus.js';
import { ObjectSerializer, RequestFile } from './index.js';

export class UpdateNode {
  /**
  * The name of the node
  */
  'name'?: string;
  /**
  * The description of the node
  */
  'description'?: string;
  'adminStatus'?: AdminStatusDef;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "name",
      "baseName": "name",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      // false
      // string
      // string
      "type": "string",
      "format": ""
    },
    {
      "name": "adminStatus",
      "baseName": "adminStatus",
      // false
      // AdminStatus
      // AdminStatusDef
      "type": "AdminStatus",
      "format": ""
    }  ];

  static getAttributeTypeMap() {
    return UpdateNode.attributeTypeMap;
  }

  static newInstance(obj: any): UpdateNode {
    return ObjectSerializer.deserialize(obj, 'UpdateNode');
  }

  constructor(name?: string, description?: string, adminStatus?: AdminStatusDef) {
    this.name = name;
    this.description = description;
    this.adminStatus = adminStatus;
  }
}

