/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { AxiosInstance } from 'axios';
import qs from 'qs';
import { ModuleVersionInfo, ModuleVersionScope } from '../model/index.js';
import { URL, EnumValue, IllegalArgumentError, PagedResults, Int32, UUID, CoreError, ParameterRequiredError, UnexpectedError, HttpMethod } from '@zerobias-org/types-core-js';
import { RequestFile, ObjectSerializer } from '../model/index.js';

// Helper to serialize core types (UUID, Nmtoken, URL, etc.) and EnumValues for query params
// All @zerobias-org/types-core-js types implement toJSON() for proper serialization
function serializeQueryParams(obj: any): any {
  if (obj === null || obj === undefined) return obj;
  if (typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(serializeQueryParams);
  // Core types and EnumValues all have toJSON() - use it for serialization
  if (typeof obj.toJSON === 'function') {
    return obj.toJSON();
  }
  // Recursively process plain object properties
  const result: any = {};
  for (const key of Object.keys(obj)) {
    result[key] = serializeQueryParams(obj[key]);
  }
  return result;
}

export namespace ModuleVersionApi {
}

/**
 * ModuleVersionApi - interface
 * @export
 * @interface ModuleVersionApi
 */
export interface ModuleVersionApi {
  /**
   * 
   * @summary Retrieves a module version by id
   * @param {UUID} moduleVersionId 
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.get('00000000-0000-0000-0000-000000000000');
   * ```
   * @openapi operation=getModuleVersion path=/moduleVersions/{moduleVersionId} method=GET
   * @memberof ModuleVersionApi
   */
  get(moduleVersionId: UUID): Promise<ModuleVersionInfo>;

  /**
   * 
   * @summary Retrieves a list of scopes for a module version by id
   * @param {UUID} moduleVersionId 
   * @param {number} [pageNumber] The requested page. This value is 1-indexed.
   * @param {number} [pageSize] The number of items in each page of data.
   * @param {string} [pageToken] Opaque cursor for cursor-based pagination. When provided, pageNumber is ignored. Use the token from the previous response&#39;s pageToken header to get the next page.
   * @param {*} [options] Override http request option.
   * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
   * @example
   * ```typescript
   * const result = await api.listModuleVersionScopes('00000000-0000-0000-0000-000000000000', 1, 1, 'pageToken');
   * ```
   * @openapi operation=listModuleVersionScopes path=/moduleVersions/{moduleVersionId}/scopes method=GET
   * @memberof ModuleVersionApi
   */
  listModuleVersionScopes(moduleVersionId: UUID, pageNumber?: number, pageSize?: number, pageToken?: string): Promise<PagedResults<ModuleVersionScope>>;

}

/**
 * ModuleVersionProducerApi - interface
 * Producer interface for ModuleVersion
 * @export
 * @interface ModuleVersionProducerApi
 */
export interface ModuleVersionProducerApi {
  /**
  * 
  * @summary Retrieves a module version by id
  * @param {UUID} moduleVersionId 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=getModuleVersion path=/moduleVersions/{moduleVersionId} method=GET
  * @memberof ModuleVersion
  */
  get(moduleVersionId: UUID): Promise<ModuleVersionInfo>;
  /**
  * 
  * @summary Retrieves a list of scopes for a module version by id
  * @param {UUID} moduleVersionId 
  * @param {*} [options] Override http request option.
  * @throws {@link @zerobias-org/types-core-js#ParameterRequiredError} if any required parameter is not provided
  * @openapi operation=listModuleVersionScopes path=/moduleVersions/{moduleVersionId}/scopes method=GET
  * @memberof ModuleVersion
  */
  listModuleVersionScopes(results: PagedResults<ModuleVersionScope>, moduleVersionId: UUID): Promise<void>;
}

export class ModuleVersionApiMappingImpl implements ModuleVersionApi {
  private producer: ModuleVersionProducerApi;
  constructor(producer: ModuleVersionProducerApi) {
    this.producer = producer;
  }

  /**
   * 
   * @summary Retrieves a module version by id
   * @param moduleVersionId 
   * @openapi operation=getModuleVersion path=/moduleVersions/{moduleVersionId} method=GET
   */
  public async get(moduleVersionId: UUID): Promise<ModuleVersionInfo> {
    // verify required parameter 'moduleVersionId' is not null or undefined
    if (moduleVersionId === null || moduleVersionId === undefined) {
      throw new ParameterRequiredError('moduleVersionId');
    }
    return this.producer.get(moduleVersionId);
  }
  /**
   * 
   * @summary Retrieves a list of scopes for a module version by id
   * @param moduleVersionId 
   * @param pageNumber The requested page. This value is 1-indexed.
   * @param pageSize The number of items in each page of data.
   * @param pageToken Opaque cursor for cursor-based pagination. When provided, pageNumber is ignored. Use the token from the previous response&#39;s pageToken header to get the next page.
   * @openapi operation=listModuleVersionScopes path=/moduleVersions/{moduleVersionId}/scopes method=GET
   */
  public async listModuleVersionScopes(moduleVersionId: UUID, pageNumber: number = 1, pageSize: number = 50, pageToken?: string): Promise<PagedResults<ModuleVersionScope>> {
    // verify required parameter 'moduleVersionId' is not null or undefined
    if (moduleVersionId === null || moduleVersionId === undefined) {
      throw new ParameterRequiredError('moduleVersionId');
    }
    if (pageNumber) {
      await Int32.parse(pageNumber);
    }
    if (pageSize) {
      await Int32.parse(pageSize);
    }
    const bag = new PagedResults<ModuleVersionScope>();
    bag.pageNumber = pageNumber;
    bag.pageSize = pageSize;
    bag.pageToken = pageToken;
    await this.producer.listModuleVersionScopes(bag, moduleVersionId);
    if (bag.items === null || bag.items === undefined) {
      throw new UnexpectedError("Producers must return 'items' for PagedResults queries");
    }
    return bag;
  }
}

/**
 * Wrap producer with mapping implementation
 */
export function wrapModuleVersionProducer(producer: ModuleVersionProducerApi): ModuleVersionApi {
  return new ModuleVersionApiMappingImpl(producer);
}

/**
 * ModuleVersionApiHttpImpl - Direct HTTP implementation
 *
 * Makes direct HTTP calls to the API using Axios.
 * Used by SDK clients for platform service access.
 */
export class ModuleVersionApiHttpImpl implements ModuleVersionProducerApi {
  private client: AxiosInstance;
  private headers: Record<string, string>;

  constructor(client: AxiosInstance, headers: Record<string, string> = {}) {
    this.client = client;
    this.headers = headers;
  }

  async get(moduleVersionId: UUID): Promise<ModuleVersionInfo> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  let _path = '/moduleVersions/{moduleVersionId}';
  _path = _path.replace('{moduleVersionId}', encodeURIComponent(String(moduleVersionId)));
  return this.client.get(
    _path,
    { params: _queryParams, paramsSerializer: (params) => qs.stringify(serializeQueryParams(params), { skipNulls: true }) })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      return ObjectSerializer.deserialize(response.data, 'ModuleVersionInfo')
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
  async listModuleVersionScopes(results: PagedResults<ModuleVersionScope>, moduleVersionId: UUID): Promise<void> {
  const _queryParams = {
      
  };
  const _bodyParams = {
      
  };
  const _body = {
      moduleVersionId,
  };
  let _path = '/moduleVersions/{moduleVersionId}/scopes';
  _path = _path.replace('{moduleVersionId}', encodeURIComponent(String(moduleVersionId)));
  return this.client.get(
    _path,
    {
      params: {
        ..._body,
        pageNumber: results.pageNumber,pageToken: results.pageToken,
        pageSize: results.pageSize,
      },
      paramsSerializer: (params) => qs.stringify(serializeQueryParams(params), { skipNulls: true }),
    })
    .then((response) => {
      // BaseApiClient uses validateStatus: () => true, so we must check status manually
      if (response.status >= 400) {
        throw CoreError.deserialize(response.data);
      }
      results.items = ObjectSerializer.deserialize(response.data, 'Array<ModuleVersionScope>');
      results.count = response.headers.count ? Number(response.headers.count) : -1;
      results.pageToken = response.headers.pagetoken ?? response.headers.pageToken;
      results.headers = this.headers;
      results.baseUrl = new URL(`${this.client.getUri()}${_path}`);
      results.httpMethod = HttpMethod.Get;
      results.body = _body;
      results.mapper = (obj) => ObjectSerializer.deserialize(obj, 'ModuleVersionScope');
    })
    .catch((error) => {
      if (error.data) {
        throw CoreError.deserialize(error.data);
      } else {
        throw error;
      }
    });
  }
}
