/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { EnumValue, IllegalArgumentError } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

export const DataloaderEventStatus = {
  /**  */
  Queued: EnumValue.instance('DataloaderEventStatus', 'Queued', 'queued'),
  /**  */
  Running: EnumValue.instance('DataloaderEventStatus', 'Running', 'running'),
  /**  */
  Failed: EnumValue.instance('DataloaderEventStatus', 'Failed', 'failed'),
  /**  */
  Completed: EnumValue.instance('DataloaderEventStatus', 'Completed', 'completed'),

  from(val: string | number): EnumValue {
    if (DataloaderEventStatus[val]) {
      return DataloaderEventStatus[val];
    }
    const byValue = DataloaderEventStatus.values.find((v) => v.value === val);
    if (byValue) {
      return byValue;
    }
    throw new IllegalArgumentError(`${val} is not a valid DataloaderEventStatus`);
  },

  get values(): EnumValue[] {
    return Object
      .keys(DataloaderEventStatus)
      .filter((k) => k !== 'values' && k !== 'from')
      .map((t) => DataloaderEventStatus[t]);
  }
} as const;

export type DataloaderEventStatusDef = typeof DataloaderEventStatus[keyof typeof DataloaderEventStatus];
