/* eslint-disable */
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
import { UUID } from '@zerobias-org/types-core-js';
import { ObjectSerializer, RequestFile } from './index.js';

/**
* Body for cleanup event
*/
export class CleanupBody {
  'dynamodbCleanup': boolean;
  'boundaryId'?: UUID;
  'orgId'?: UUID;

  static readonly discriminator: string | undefined = undefined;

  static attributeTypeMap: ReadonlyArray<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "dynamodbCleanup",
      "baseName": "dynamodbCleanup",
      // false
      // boolean
      // boolean
      "type": "boolean",
      "format": ""
    },
    {
      "name": "boundaryId",
      "baseName": "boundaryId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    },
    {
      "name": "orgId",
      "baseName": "orgId",
      // false
      // UUID
      // UUID
      "type": "UUID",
      "format": "uuid"
    }  ];

  static getAttributeTypeMap() {
    return CleanupBody.attributeTypeMap;
  }

  static newInstance(obj: any): CleanupBody {
    return ObjectSerializer.deserialize(obj, 'CleanupBody');
  }

  constructor(dynamodbCleanup: boolean, boundaryId?: UUID, orgId?: UUID) {
    this.dynamodbCleanup = dynamodbCleanup;
    this.boundaryId = boundaryId;
    this.orgId = orgId;
  }
}

