openapi: 3.0.3
info:
  description: Schema for the @zerobias-org/util-secrets-manager package
  version: ''
  title: '@zerobias-org/util-secrets-manager'
paths: {}
components:
  schemas:
    SecretNode:
      type: object
      title: A key in a secrets manager
      description: Representation of a node in a secrets manager's tree
      required:
        - path
        - type
        - writable
        - active
      properties:
        path:
          description: The path to the node
          type: string
          example: vault.ci.github
        type:
          description: The type of node this is. Nodes have other nodes below them; Secrets are leaf nodes
          type: string
          enum:
            - Node
            - Secret
          example: Secret
        writable:
          description: |-
            Flag indicating whether or not nodes in this tree are writable. This is a general  indicator of writeability to the secrets provider; it is NOT checked on a per-node basis. So whereas you may be able to write to the given secrets manager, you may not have permission to write to a given node. This will only be discovered once you attempt a write, as we are not attempting to write to each node.
            In short, this is a best-case indicator rather than an exact indicator.
          type: boolean
        writeSuccess:
          description: |-
            Flag indicating whether or not nodes in this tree were successfully able to write.
            This is an exact indicator if this node is writable.
          type: boolean
        writeError:
          description: If writeSucces is false, this should be populated with the error that occured on validate
          type: string
        connectError:
          description: If unable to connect to secret manager this should be populated with the error that occured
          type: string
        active:
          description: Flag indicating whether or not nodes in this tree are active. This is a general indicator that there are missing or invalid env variables on the system.
          type: boolean
